// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/all.hpp -- aggregator: every messages/<Msg>.hpp + the builder_registry (data-model.md Entity 5); replaces Builders.hpp.
#pragma once
#include "messages/IOI.hpp"
#include "messages/Advertisement.hpp"
#include "messages/ExecutionReport.hpp"
#include "messages/OrderCancelReject.hpp"
#include "messages/DerivativeSecurityList.hpp"
#include "messages/NewOrderMultileg.hpp"
#include "messages/MultilegOrderCancelReplace.hpp"
#include "messages/TradeCaptureReportRequest.hpp"
#include "messages/TradeCaptureReport.hpp"
#include "messages/OrderMassStatusRequest.hpp"
#include "messages/QuoteRequestReject.hpp"
#include "messages/RFQRequest.hpp"
#include "messages/QuoteStatusReport.hpp"
#include "messages/QuoteResponse.hpp"
#include "messages/Confirmation.hpp"
#include "messages/PositionMaintenanceRequest.hpp"
#include "messages/PositionMaintenanceReport.hpp"
#include "messages/RequestForPositions.hpp"
#include "messages/RequestForPositionsAck.hpp"
#include "messages/PositionReport.hpp"
#include "messages/TradeCaptureReportRequestAck.hpp"
#include "messages/TradeCaptureReportAck.hpp"
#include "messages/AllocationReport.hpp"
#include "messages/AllocationReportAck.hpp"
#include "messages/ConfirmationAck.hpp"
#include "messages/SettlementInstructionRequest.hpp"
#include "messages/AssignmentReport.hpp"
#include "messages/CollateralRequest.hpp"
#include "messages/CollateralAssignment.hpp"
#include "messages/CollateralResponse.hpp"
#include "messages/News.hpp"
#include "messages/CollateralReport.hpp"
#include "messages/CollateralInquiry.hpp"
#include "messages/NetworkCounterpartySystemStatusRequest.hpp"
#include "messages/NetworkCounterpartySystemStatusResponse.hpp"
#include "messages/UserRequest.hpp"
#include "messages/UserResponse.hpp"
#include "messages/CollateralInquiryAck.hpp"
#include "messages/ConfirmationRequest.hpp"
#include "messages/TradingSessionListRequest.hpp"
#include "messages/TradingSessionList.hpp"
#include "messages/SecurityListUpdateReport.hpp"
#include "messages/AdjustedPositionReport.hpp"
#include "messages/AllocationInstructionAlert.hpp"
#include "messages/ExecutionAck.hpp"
#include "messages/ContraryIntentionReport.hpp"
#include "messages/SecurityDefinitionUpdateReport.hpp"
#include "messages/SettlementObligationReport.hpp"
#include "messages/DerivativeSecurityListUpdateReport.hpp"
#include "messages/TradingSessionListUpdateReport.hpp"
#include "messages/MarketDefinitionRequest.hpp"
#include "messages/MarketDefinition.hpp"
#include "messages/MarketDefinitionUpdateReport.hpp"
#include "messages/ApplicationMessageRequest.hpp"
#include "messages/ApplicationMessageRequestAck.hpp"
#include "messages/ApplicationMessageReport.hpp"
#include "messages/OrderMassActionReport.hpp"
#include "messages/Email.hpp"
#include "messages/OrderMassActionRequest.hpp"
#include "messages/UserNotification.hpp"
#include "messages/StreamAssignmentRequest.hpp"
#include "messages/StreamAssignmentReport.hpp"
#include "messages/StreamAssignmentReportACK.hpp"
#include "messages/PartyDetailsListRequest.hpp"
#include "messages/PartyDetailsListReport.hpp"
#include "messages/MarginRequirementInquiry.hpp"
#include "messages/MarginRequirementInquiryAck.hpp"
#include "messages/MarginRequirementReport.hpp"
#include "messages/PartyDetailsListUpdateReport.hpp"
#include "messages/PartyRiskLimitsRequest.hpp"
#include "messages/PartyRiskLimitsReport.hpp"
#include "messages/SecurityMassStatusRequest.hpp"
#include "messages/SecurityMassStatus.hpp"
#include "messages/AccountSummaryReport.hpp"
#include "messages/PartyRiskLimitsUpdateReport.hpp"
#include "messages/PartyRiskLimitsDefinitionRequest.hpp"
#include "messages/PartyRiskLimitsDefinitionRequestAck.hpp"
#include "messages/PartyEntitlementsRequest.hpp"
#include "messages/PartyEntitlementsReport.hpp"
#include "messages/QuoteAck.hpp"
#include "messages/PartyDetailsDefinitionRequest.hpp"
#include "messages/PartyDetailsDefinitionRequestAck.hpp"
#include "messages/PartyEntitlementsUpdateReport.hpp"
#include "messages/NewOrderSingle.hpp"
#include "messages/PartyEntitlementsDefinitionRequest.hpp"
#include "messages/PartyEntitlementsDefinitionRequestAck.hpp"
#include "messages/TradeMatchReport.hpp"
#include "messages/TradeMatchReportAck.hpp"
#include "messages/PartyRiskLimitsReportAck.hpp"
#include "messages/PartyRiskLimitCheckRequest.hpp"
#include "messages/PartyRiskLimitCheckRequestAck.hpp"
#include "messages/PartyActionRequest.hpp"
#include "messages/PartyActionReport.hpp"
#include "messages/MassOrder.hpp"
#include "messages/MassOrderAck.hpp"
#include "messages/PositionTransferInstruction.hpp"
#include "messages/PositionTransferInstructionAck.hpp"
#include "messages/PositionTransferReport.hpp"
#include "messages/MarketDataStatisticsRequest.hpp"
#include "messages/MarketDataStatisticsReport.hpp"
#include "messages/CollateralReportAck.hpp"
#include "messages/MarketDataReport.hpp"
#include "messages/CrossRequest.hpp"
#include "messages/CrossRequestAck.hpp"
#include "messages/AllocationInstructionAlertRequest.hpp"
#include "messages/AllocationInstructionAlertRequestAck.hpp"
#include "messages/TradeAggregationRequest.hpp"
#include "messages/TradeAggregationReport.hpp"
#include "messages/PayManagementRequest.hpp"
#include "messages/PayManagementRequestAck.hpp"
#include "messages/NewOrderList.hpp"
#include "messages/PayManagementReport.hpp"
#include "messages/PayManagementReportAck.hpp"
#include "messages/SettlementStatusRequest.hpp"
#include "messages/SettlementStatusRequestAck.hpp"
#include "messages/SettlementStatusReport.hpp"
#include "messages/SettlementStatusReportAck.hpp"
#include "messages/SecurityRiskMetricsReport.hpp"
#include "messages/AlgoCertificateRequest.hpp"
#include "messages/AlgoCertificateRequestAck.hpp"
#include "messages/AlgoCertificateReport.hpp"
#include "messages/AlgoCertificateReportAck.hpp"
#include "messages/TestSuiteDefinitionRequest.hpp"
#include "messages/TestSuiteDefinitionRequestAck.hpp"
#include "messages/TestActionRequest.hpp"
#include "messages/TestActionRequestAck.hpp"
#include "messages/TestActionReport.hpp"
#include "messages/MarketDataAck.hpp"
#include "messages/SecurityStatusAck.hpp"
#include "messages/TradingSessionStatusAck.hpp"
#include "messages/OrderCancelRequest.hpp"
#include "messages/OrderCancelReplaceRequest.hpp"
#include "messages/OrderStatusRequest.hpp"
#include "messages/AllocationInstruction.hpp"
#include "messages/ListCancelRequest.hpp"
#include "messages/ListExecute.hpp"
#include "messages/ListStatusRequest.hpp"
#include "messages/ListStatus.hpp"
#include "messages/AllocationInstructionAck.hpp"
#include "messages/DontKnowTrade.hpp"
#include "messages/QuoteRequest.hpp"
#include "messages/Quote.hpp"
#include "messages/SettlementInstructions.hpp"
#include "messages/MarketDataRequest.hpp"
#include "messages/MarketDataSnapshotFullRefresh.hpp"
#include "messages/MarketDataIncrementalRefresh.hpp"
#include "messages/MarketDataRequestReject.hpp"
#include "messages/QuoteCancel.hpp"
#include "messages/QuoteStatusRequest.hpp"
#include "messages/MassQuoteAck.hpp"
#include "messages/SecurityDefinitionRequest.hpp"
#include "messages/SecurityDefinition.hpp"
#include "messages/SecurityStatusRequest.hpp"
#include "messages/SecurityStatus.hpp"
#include "messages/TradingSessionStatusRequest.hpp"
#include "messages/TradingSessionStatus.hpp"
#include "messages/MassQuote.hpp"
#include "messages/BusinessMessageReject.hpp"
#include "messages/BidRequest.hpp"
#include "messages/BidResponse.hpp"
#include "messages/ListStrikePrice.hpp"
#include "messages/RegistrationInstructions.hpp"
#include "messages/RegistrationInstructionsResponse.hpp"
#include "messages/OrderMassCancelRequest.hpp"
#include "messages/OrderMassCancelReport.hpp"
#include "messages/NewOrderCross.hpp"
#include "messages/CrossOrderCancelReplaceRequest.hpp"
#include "messages/CrossOrderCancelRequest.hpp"
#include "messages/SecurityTypeRequest.hpp"
#include "messages/SecurityTypes.hpp"
#include "messages/SecurityListRequest.hpp"
#include "messages/SecurityList.hpp"
#include "messages/DerivativeSecurityListRequest.hpp"
#include <array>
#include <string_view>

namespace fixpp::vlatest {

struct builder_registry_entry { ::std::string_view msg_type; };
inline constexpr ::std::array<builder_registry_entry, 173> builder_registry = {{
    {"6"},
    {"7"},
    {"8"},
    {"9"},
    {"AA"},
    {"AB"},
    {"AC"},
    {"AD"},
    {"AE"},
    {"AF"},
    {"AG"},
    {"AH"},
    {"AI"},
    {"AJ"},
    {"AK"},
    {"AL"},
    {"AM"},
    {"AN"},
    {"AO"},
    {"AP"},
    {"AQ"},
    {"AR"},
    {"AS"},
    {"AT"},
    {"AU"},
    {"AV"},
    {"AW"},
    {"AX"},
    {"AY"},
    {"AZ"},
    {"B"},
    {"BA"},
    {"BB"},
    {"BC"},
    {"BD"},
    {"BE"},
    {"BF"},
    {"BG"},
    {"BH"},
    {"BI"},
    {"BJ"},
    {"BK"},
    {"BL"},
    {"BM"},
    {"BN"},
    {"BO"},
    {"BP"},
    {"BQ"},
    {"BR"},
    {"BS"},
    {"BT"},
    {"BU"},
    {"BV"},
    {"BW"},
    {"BX"},
    {"BY"},
    {"BZ"},
    {"C"},
    {"CA"},
    {"CB"},
    {"CC"},
    {"CD"},
    {"CE"},
    {"CF"},
    {"CG"},
    {"CH"},
    {"CI"},
    {"CJ"},
    {"CK"},
    {"CL"},
    {"CM"},
    {"CN"},
    {"CO"},
    {"CQ"},
    {"CR"},
    {"CS"},
    {"CT"},
    {"CU"},
    {"CV"},
    {"CW"},
    {"CX"},
    {"CY"},
    {"CZ"},
    {"D"},
    {"DA"},
    {"DB"},
    {"DC"},
    {"DD"},
    {"DE"},
    {"DF"},
    {"DG"},
    {"DH"},
    {"DI"},
    {"DJ"},
    {"DK"},
    {"DL"},
    {"DM"},
    {"DN"},
    {"DO"},
    {"DP"},
    {"DQ"},
    {"DR"},
    {"DS"},
    {"DT"},
    {"DU"},
    {"DV"},
    {"DW"},
    {"DX"},
    {"DY"},
    {"DZ"},
    {"E"},
    {"EA"},
    {"EB"},
    {"EC"},
    {"ED"},
    {"EE"},
    {"EF"},
    {"EG"},
    {"EH"},
    {"EI"},
    {"EJ"},
    {"EK"},
    {"EL"},
    {"EM"},
    {"EN"},
    {"EO"},
    {"EP"},
    {"EQ"},
    {"ER"},
    {"ES"},
    {"F"},
    {"G"},
    {"H"},
    {"J"},
    {"K"},
    {"L"},
    {"M"},
    {"N"},
    {"P"},
    {"Q"},
    {"R"},
    {"S"},
    {"T"},
    {"V"},
    {"W"},
    {"X"},
    {"Y"},
    {"Z"},
    {"a"},
    {"b"},
    {"c"},
    {"d"},
    {"e"},
    {"f"},
    {"g"},
    {"h"},
    {"i"},
    {"j"},
    {"k"},
    {"l"},
    {"m"},
    {"o"},
    {"p"},
    {"q"},
    {"r"},
    {"s"},
    {"t"},
    {"u"},
    {"v"},
    {"w"},
    {"x"},
    {"y"},
    {"z"},
}};

}  // namespace fixpp::vlatest
