// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v42/groups/G_268_1Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::v42::groups {

struct G_268_1Args {
    ::std::optional<char> md_entry_type{};
    ::std::optional<::fixpp::decimal_t> md_entry_px{};
    ::std::optional<::std::string_view> currency{};
    ::std::optional<::fixpp::decimal_t> md_entry_size{};
    ::std::optional<::std::string_view> md_entry_date{};
    ::std::optional<::std::string_view> md_entry_time{};
    ::std::optional<char> tick_direction{};
    ::std::optional<::std::string_view> md_mkt{};
    ::std::optional<::std::string_view> trading_session_id{};
    ::std::optional<::std::string_view> quote_condition{};
    ::std::optional<::std::string_view> trade_condition{};
    ::std::optional<::std::string_view> md_entry_originator{};
    ::std::optional<::std::string_view> location_id{};
    ::std::optional<::std::string_view> desk_id{};
    ::std::optional<char> open_close_settle_flag{};
    ::std::optional<char> time_in_force{};
    ::std::optional<::std::string_view> expire_date{};
    ::std::optional<::std::string_view> expire_time{};
    ::std::optional<::fixpp::decimal_t> min_qty{};
    ::std::optional<::std::string_view> exec_inst{};
    ::std::optional<::std::int64_t> seller_days{};
    ::std::optional<::std::string_view> order_id{};
    ::std::optional<::std::string_view> quote_entry_id{};
    ::std::optional<::std::string_view> md_entry_buyer{};
    ::std::optional<::std::string_view> md_entry_seller{};
    ::std::optional<::std::int64_t> number_of_orders{};
    ::std::optional<::std::int64_t> md_entry_position_no{};
    ::std::optional<::std::string_view> text{};
    ::std::optional<::std::string_view> encoded_text{};
};

}  // namespace fixpp::v42::groups
