// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v42/groups/G_78_1Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::v42::groups {

struct G_78_1Args {
    ::std::optional<::std::string_view> alloc_account{};
    ::std::optional<::fixpp::decimal_t> alloc_shares{};
};

}  // namespace fixpp::v42::groups
