// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v50sp2/messages/AllocationInstructionAlertRequest.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include "../groups/G_453Args.hpp"
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::v50sp2 {

struct AllocationInstructionAlertRequestArgs {
    ::std::optional<::std::string_view> trade_date{};
    ::std::optional<::std::span<const groups::G_453Args>> party_i_ds{};
    ::std::optional<::std::string_view> alloc_group_id{};
    ::std::optional<::std::string_view> avg_px_group_id{};
    ::std::optional<::std::string_view> alloc_request_id{};
};

}  // namespace fixpp::v50sp2

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_AllocationInstructionAlertRequest)
#include "AllocationInstructionAlertRequest.builder.inl"
#else
namespace fixpp::v50sp2 {
::fixpp::core::expected_t<::std::span<::std::byte>> build_AllocationInstructionAlertRequest(::std::span<::std::byte> out, AllocationInstructionAlertRequestArgs const& args) noexcept;
}  // namespace fixpp::v50sp2
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_AllocationInstructionAlertRequest)
#include "AllocationInstructionAlertRequest.validator.inl"
#else
namespace fixpp::v50sp2 {
::fixpp::core::expected_t<void> validate_AllocationInstructionAlertRequest(AllocationInstructionAlertRequestArgs const& args) noexcept;
}  // namespace fixpp::v50sp2
#endif
