// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v50sp2/messages/ApplicationMessageRequest.validator.inl -- inline validate_ body + this message's own top-level traits (data-model.md Entity 3).
#pragma once
#include "ApplicationMessageRequest.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool ApplicationMessageRequestArgs_required_1346(::fixpp::v50sp2::ApplicationMessageRequestArgs const& a) noexcept { return a.appl_req_id.has_value(); }
inline bool ApplicationMessageRequestArgs_required_1347(::fixpp::v50sp2::ApplicationMessageRequestArgs const& a) noexcept { return a.appl_req_type.has_value(); }
inline ::std::optional<::std::size_t> ApplicationMessageRequestArgs_count_party_i_ds(::fixpp::v50sp2::ApplicationMessageRequestArgs const& a) noexcept { if (!a.party_i_ds) { return ::std::nullopt; } return a.party_i_ds->size(); }
inline ::fixpp::core::expected_t<void> ApplicationMessageRequestArgs_validate_entry_party_i_ds(::fixpp::v50sp2::ApplicationMessageRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.party_i_ds)[i]); }
inline ::std::optional<::std::size_t> ApplicationMessageRequestArgs_count_appl_i_ds(::fixpp::v50sp2::ApplicationMessageRequestArgs const& a) noexcept { if (!a.appl_i_ds) { return ::std::nullopt; } return a.appl_i_ds->size(); }
inline ::fixpp::core::expected_t<void> ApplicationMessageRequestArgs_validate_entry_appl_i_ds(::fixpp::v50sp2::ApplicationMessageRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.appl_i_ds)[i]); }
template <> struct writer_traits<::fixpp::v50sp2::ApplicationMessageRequestArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::v50sp2::ApplicationMessageRequestArgs>, 2> required_checks = {{
        {1346, &ApplicationMessageRequestArgs_required_1346},
        {1347, &ApplicationMessageRequestArgs_required_1347},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::v50sp2::ApplicationMessageRequestArgs>, 2> group_checks = {{
        {false, &ApplicationMessageRequestArgs_count_party_i_ds, &ApplicationMessageRequestArgs_validate_entry_party_i_ds},
        {false, &ApplicationMessageRequestArgs_count_appl_i_ds, &ApplicationMessageRequestArgs_validate_entry_appl_i_ds},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::v50sp2 {

inline ::fixpp::core::expected_t<void> validate_ApplicationMessageRequest(ApplicationMessageRequestArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::v50sp2
