// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v50sp2/messages/ApplicationMessageReport.validator.cpp -- external-linkage validate_ definition + this message's own top-level traits (data-model.md Entity 4), compiled only into fixpp_validators_<ver>.
#include "ApplicationMessageReport.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool ApplicationMessageReportArgs_required_1356(::fixpp::v50sp2::ApplicationMessageReportArgs const& a) noexcept { return a.appl_report_id.has_value(); }
inline bool ApplicationMessageReportArgs_required_1426(::fixpp::v50sp2::ApplicationMessageReportArgs const& a) noexcept { return a.appl_report_type.has_value(); }
inline ::std::optional<::std::size_t> ApplicationMessageReportArgs_count_appl_i_ds(::fixpp::v50sp2::ApplicationMessageReportArgs const& a) noexcept { if (!a.appl_i_ds) { return ::std::nullopt; } return a.appl_i_ds->size(); }
inline ::fixpp::core::expected_t<void> ApplicationMessageReportArgs_validate_entry_appl_i_ds(::fixpp::v50sp2::ApplicationMessageReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.appl_i_ds)[i]); }
template <> struct writer_traits<::fixpp::v50sp2::ApplicationMessageReportArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::v50sp2::ApplicationMessageReportArgs>, 2> required_checks = {{
        {1356, &ApplicationMessageReportArgs_required_1356},
        {1426, &ApplicationMessageReportArgs_required_1426},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::v50sp2::ApplicationMessageReportArgs>, 1> group_checks = {{
        {false, &ApplicationMessageReportArgs_count_appl_i_ds, &ApplicationMessageReportArgs_validate_entry_appl_i_ds},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::v50sp2 {

::fixpp::core::expected_t<void> validate_ApplicationMessageReport(ApplicationMessageReportArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::v50sp2
