// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v50sp2/messages/ConfirmationRequest.validator.inl -- inline validate_ body + this message's own top-level traits (data-model.md Entity 3).
#pragma once
#include "ConfirmationRequest.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool ConfirmationRequestArgs_required_60(::fixpp::v50sp2::ConfirmationRequestArgs const& a) noexcept { return a.transact_time.has_value(); }
inline bool ConfirmationRequestArgs_required_773(::fixpp::v50sp2::ConfirmationRequestArgs const& a) noexcept { return a.confirm_type.has_value(); }
inline bool ConfirmationRequestArgs_required_859(::fixpp::v50sp2::ConfirmationRequestArgs const& a) noexcept { return a.confirm_req_id.has_value(); }
inline ::std::optional<::std::size_t> ConfirmationRequestArgs_count_orders(::fixpp::v50sp2::ConfirmationRequestArgs const& a) noexcept { if (!a.orders) { return ::std::nullopt; } return a.orders->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationRequestArgs_validate_entry_orders(::fixpp::v50sp2::ConfirmationRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.orders)[i]); }
template <> struct writer_traits<::fixpp::v50sp2::ConfirmationRequestArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::v50sp2::ConfirmationRequestArgs>, 3> required_checks = {{
        {60, &ConfirmationRequestArgs_required_60},
        {773, &ConfirmationRequestArgs_required_773},
        {859, &ConfirmationRequestArgs_required_859},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::v50sp2::ConfirmationRequestArgs>, 1> group_checks = {{
        {false, &ConfirmationRequestArgs_count_orders, &ConfirmationRequestArgs_validate_entry_orders},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::v50sp2 {

inline ::fixpp::core::expected_t<void> validate_ConfirmationRequest(ConfirmationRequestArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::v50sp2
