// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v50sp2/messages/CrossOrderCancelRequest.validator.cpp -- external-linkage validate_ definition + this message's own top-level traits (data-model.md Entity 4), compiled only into fixpp_validators_<ver>.
#include "CrossOrderCancelRequest.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool CrossOrderCancelRequestArgs_required_60(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { return a.transact_time.has_value(); }
inline bool CrossOrderCancelRequestArgs_required_548(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { return a.cross_id.has_value(); }
inline bool CrossOrderCancelRequestArgs_required_549(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { return a.cross_type.has_value(); }
inline bool CrossOrderCancelRequestArgs_required_550(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { return a.cross_prioritization.has_value(); }
inline bool CrossOrderCancelRequestArgs_required_551(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { return a.orig_cross_id.has_value(); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_security_alt_id(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.security_alt_id) { return ::std::nullopt; } return a.security_alt_id->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_security_alt_id(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.security_alt_id)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_sides(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.sides) { return ::std::nullopt; } return a.sides->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_sides(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.sides)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_legs(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.legs) { return ::std::nullopt; } return a.legs->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_legs(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.legs)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_underlyings(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.underlyings) { return ::std::nullopt; } return a.underlyings->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_underlyings(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.underlyings)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_events(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.events) { return ::std::nullopt; } return a.events->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_events(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.events)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_instrument_parties(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.instrument_parties) { return ::std::nullopt; } return a.instrument_parties->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_instrument_parties(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.instrument_parties)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_root_party_i_ds(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.root_party_i_ds) { return ::std::nullopt; } return a.root_party_i_ds->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_root_party_i_ds(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.root_party_i_ds)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_complex_events(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.complex_events) { return ::std::nullopt; } return a.complex_events->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_complex_events(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.complex_events)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_secondary_asset_classes(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.secondary_asset_classes) { return ::std::nullopt; } return a.secondary_asset_classes->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_secondary_asset_classes(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.secondary_asset_classes)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_asset_attributes(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.asset_attributes) { return ::std::nullopt; } return a.asset_attributes->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_asset_attributes(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.asset_attributes)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_additional_terms(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.additional_terms) { return ::std::nullopt; } return a.additional_terms->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_additional_terms(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.additional_terms)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_cash_settl_terms(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.cash_settl_terms) { return ::std::nullopt; } return a.cash_settl_terms->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_cash_settl_terms(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.cash_settl_terms)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_streams(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.streams) { return ::std::nullopt; } return a.streams->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_streams(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.streams)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_provisions(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.provisions) { return ::std::nullopt; } return a.provisions->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_provisions(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.provisions)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_protection_terms(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.protection_terms) { return ::std::nullopt; } return a.protection_terms->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_protection_terms(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.protection_terms)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_physical_settl_terms(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.physical_settl_terms) { return ::std::nullopt; } return a.physical_settl_terms->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_physical_settl_terms(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.physical_settl_terms)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_business_centers(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.business_centers) { return ::std::nullopt; } return a.business_centers->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_business_centers(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.business_centers)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_market_disruption_events(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.market_disruption_events) { return ::std::nullopt; } return a.market_disruption_events->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_market_disruption_events(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.market_disruption_events)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_market_disruption_fallbacks(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.market_disruption_fallbacks) { return ::std::nullopt; } return a.market_disruption_fallbacks->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_market_disruption_fallbacks(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.market_disruption_fallbacks)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_market_disruption_fallback_reference_prices(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.market_disruption_fallback_reference_prices) { return ::std::nullopt; } return a.market_disruption_fallback_reference_prices->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_market_disruption_fallback_reference_prices(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.market_disruption_fallback_reference_prices)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_option_exercise_business_centers(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.option_exercise_business_centers) { return ::std::nullopt; } return a.option_exercise_business_centers->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_option_exercise_business_centers(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.option_exercise_business_centers)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_option_exercise_dates(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.option_exercise_dates) { return ::std::nullopt; } return a.option_exercise_dates->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_option_exercise_dates(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.option_exercise_dates)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_option_exercise_expiration_date_business_centers(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.option_exercise_expiration_date_business_centers) { return ::std::nullopt; } return a.option_exercise_expiration_date_business_centers->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_option_exercise_expiration_date_business_centers(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.option_exercise_expiration_date_business_centers)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_option_exercise_expiration_dates(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.option_exercise_expiration_dates) { return ::std::nullopt; } return a.option_exercise_expiration_dates->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_option_exercise_expiration_dates(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.option_exercise_expiration_dates)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_pricing_date_business_centers(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.pricing_date_business_centers) { return ::std::nullopt; } return a.pricing_date_business_centers->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_pricing_date_business_centers(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.pricing_date_business_centers)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_extraordinary_events(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.extraordinary_events) { return ::std::nullopt; } return a.extraordinary_events->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_extraordinary_events(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.extraordinary_events)[i]); }
inline ::std::optional<::std::size_t> CrossOrderCancelRequestArgs_count_settl_method_election_date_business_centers(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a) noexcept { if (!a.settl_method_election_date_business_centers) { return ::std::nullopt; } return a.settl_method_election_date_business_centers->size(); }
inline ::fixpp::core::expected_t<void> CrossOrderCancelRequestArgs_validate_entry_settl_method_election_date_business_centers(::fixpp::v50sp2::CrossOrderCancelRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.settl_method_election_date_business_centers)[i]); }
template <> struct writer_traits<::fixpp::v50sp2::CrossOrderCancelRequestArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::v50sp2::CrossOrderCancelRequestArgs>, 5> required_checks = {{
        {60, &CrossOrderCancelRequestArgs_required_60},
        {548, &CrossOrderCancelRequestArgs_required_548},
        {549, &CrossOrderCancelRequestArgs_required_549},
        {550, &CrossOrderCancelRequestArgs_required_550},
        {551, &CrossOrderCancelRequestArgs_required_551},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::v50sp2::CrossOrderCancelRequestArgs>, 27> group_checks = {{
        {false, &CrossOrderCancelRequestArgs_count_security_alt_id, &CrossOrderCancelRequestArgs_validate_entry_security_alt_id},
        {false, &CrossOrderCancelRequestArgs_count_sides, &CrossOrderCancelRequestArgs_validate_entry_sides},
        {false, &CrossOrderCancelRequestArgs_count_legs, &CrossOrderCancelRequestArgs_validate_entry_legs},
        {false, &CrossOrderCancelRequestArgs_count_underlyings, &CrossOrderCancelRequestArgs_validate_entry_underlyings},
        {false, &CrossOrderCancelRequestArgs_count_events, &CrossOrderCancelRequestArgs_validate_entry_events},
        {false, &CrossOrderCancelRequestArgs_count_instrument_parties, &CrossOrderCancelRequestArgs_validate_entry_instrument_parties},
        {false, &CrossOrderCancelRequestArgs_count_root_party_i_ds, &CrossOrderCancelRequestArgs_validate_entry_root_party_i_ds},
        {false, &CrossOrderCancelRequestArgs_count_complex_events, &CrossOrderCancelRequestArgs_validate_entry_complex_events},
        {false, &CrossOrderCancelRequestArgs_count_secondary_asset_classes, &CrossOrderCancelRequestArgs_validate_entry_secondary_asset_classes},
        {false, &CrossOrderCancelRequestArgs_count_asset_attributes, &CrossOrderCancelRequestArgs_validate_entry_asset_attributes},
        {false, &CrossOrderCancelRequestArgs_count_additional_terms, &CrossOrderCancelRequestArgs_validate_entry_additional_terms},
        {false, &CrossOrderCancelRequestArgs_count_cash_settl_terms, &CrossOrderCancelRequestArgs_validate_entry_cash_settl_terms},
        {false, &CrossOrderCancelRequestArgs_count_streams, &CrossOrderCancelRequestArgs_validate_entry_streams},
        {false, &CrossOrderCancelRequestArgs_count_provisions, &CrossOrderCancelRequestArgs_validate_entry_provisions},
        {false, &CrossOrderCancelRequestArgs_count_protection_terms, &CrossOrderCancelRequestArgs_validate_entry_protection_terms},
        {false, &CrossOrderCancelRequestArgs_count_physical_settl_terms, &CrossOrderCancelRequestArgs_validate_entry_physical_settl_terms},
        {false, &CrossOrderCancelRequestArgs_count_business_centers, &CrossOrderCancelRequestArgs_validate_entry_business_centers},
        {false, &CrossOrderCancelRequestArgs_count_market_disruption_events, &CrossOrderCancelRequestArgs_validate_entry_market_disruption_events},
        {false, &CrossOrderCancelRequestArgs_count_market_disruption_fallbacks, &CrossOrderCancelRequestArgs_validate_entry_market_disruption_fallbacks},
        {false, &CrossOrderCancelRequestArgs_count_market_disruption_fallback_reference_prices, &CrossOrderCancelRequestArgs_validate_entry_market_disruption_fallback_reference_prices},
        {false, &CrossOrderCancelRequestArgs_count_option_exercise_business_centers, &CrossOrderCancelRequestArgs_validate_entry_option_exercise_business_centers},
        {false, &CrossOrderCancelRequestArgs_count_option_exercise_dates, &CrossOrderCancelRequestArgs_validate_entry_option_exercise_dates},
        {false, &CrossOrderCancelRequestArgs_count_option_exercise_expiration_date_business_centers, &CrossOrderCancelRequestArgs_validate_entry_option_exercise_expiration_date_business_centers},
        {false, &CrossOrderCancelRequestArgs_count_option_exercise_expiration_dates, &CrossOrderCancelRequestArgs_validate_entry_option_exercise_expiration_dates},
        {false, &CrossOrderCancelRequestArgs_count_pricing_date_business_centers, &CrossOrderCancelRequestArgs_validate_entry_pricing_date_business_centers},
        {false, &CrossOrderCancelRequestArgs_count_extraordinary_events, &CrossOrderCancelRequestArgs_validate_entry_extraordinary_events},
        {false, &CrossOrderCancelRequestArgs_count_settl_method_election_date_business_centers, &CrossOrderCancelRequestArgs_validate_entry_settl_method_election_date_business_centers},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::v50sp2 {

::fixpp::core::expected_t<void> validate_CrossOrderCancelRequest(CrossOrderCancelRequestArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::v50sp2
