// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v50sp2/messages/OrderCancelReject.validator.cpp -- external-linkage validate_ definition + this message's own top-level traits (data-model.md Entity 4), compiled only into fixpp_validators_<ver>.
#include "OrderCancelReject.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool OrderCancelRejectArgs_required_11(::fixpp::v50sp2::OrderCancelRejectArgs const& a) noexcept { return a.cl_ord_id.has_value(); }
inline bool OrderCancelRejectArgs_required_37(::fixpp::v50sp2::OrderCancelRejectArgs const& a) noexcept { return a.order_id.has_value(); }
inline bool OrderCancelRejectArgs_required_39(::fixpp::v50sp2::OrderCancelRejectArgs const& a) noexcept { return a.ord_status.has_value(); }
inline bool OrderCancelRejectArgs_required_434(::fixpp::v50sp2::OrderCancelRejectArgs const& a) noexcept { return a.cxl_rej_response_to.has_value(); }
inline ::std::optional<::std::size_t> OrderCancelRejectArgs_count_party_i_ds(::fixpp::v50sp2::OrderCancelRejectArgs const& a) noexcept { if (!a.party_i_ds) { return ::std::nullopt; } return a.party_i_ds->size(); }
inline ::fixpp::core::expected_t<void> OrderCancelRejectArgs_validate_entry_party_i_ds(::fixpp::v50sp2::OrderCancelRejectArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.party_i_ds)[i]); }
template <> struct writer_traits<::fixpp::v50sp2::OrderCancelRejectArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::v50sp2::OrderCancelRejectArgs>, 4> required_checks = {{
        {11, &OrderCancelRejectArgs_required_11},
        {37, &OrderCancelRejectArgs_required_37},
        {39, &OrderCancelRejectArgs_required_39},
        {434, &OrderCancelRejectArgs_required_434},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::v50sp2::OrderCancelRejectArgs>, 1> group_checks = {{
        {false, &OrderCancelRejectArgs_count_party_i_ds, &OrderCancelRejectArgs_validate_entry_party_i_ds},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::v50sp2 {

::fixpp::core::expected_t<void> validate_OrderCancelReject(OrderCancelRejectArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::v50sp2
