// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v50sp2/messages/PartyDetailsListRequest.validator.inl -- inline validate_ body + this message's own top-level traits (data-model.md Entity 3).
#pragma once
#include "PartyDetailsListRequest.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool PartyDetailsListRequestArgs_required_1505(::fixpp::v50sp2::PartyDetailsListRequestArgs const& a) noexcept { return a.party_details_list_request_id.has_value(); }
inline ::std::optional<::std::size_t> PartyDetailsListRequestArgs_count_party_i_ds(::fixpp::v50sp2::PartyDetailsListRequestArgs const& a) noexcept { if (!a.party_i_ds) { return ::std::nullopt; } return a.party_i_ds->size(); }
inline ::fixpp::core::expected_t<void> PartyDetailsListRequestArgs_validate_entry_party_i_ds(::fixpp::v50sp2::PartyDetailsListRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.party_i_ds)[i]); }
inline ::std::optional<::std::size_t> PartyDetailsListRequestArgs_count_requested_party_roles(::fixpp::v50sp2::PartyDetailsListRequestArgs const& a) noexcept { if (!a.requested_party_roles) { return ::std::nullopt; } return a.requested_party_roles->size(); }
inline ::fixpp::core::expected_t<void> PartyDetailsListRequestArgs_validate_entry_requested_party_roles(::fixpp::v50sp2::PartyDetailsListRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.requested_party_roles)[i]); }
inline ::std::optional<::std::size_t> PartyDetailsListRequestArgs_count_party_relationships(::fixpp::v50sp2::PartyDetailsListRequestArgs const& a) noexcept { if (!a.party_relationships) { return ::std::nullopt; } return a.party_relationships->size(); }
inline ::fixpp::core::expected_t<void> PartyDetailsListRequestArgs_validate_entry_party_relationships(::fixpp::v50sp2::PartyDetailsListRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.party_relationships)[i]); }
inline ::std::optional<::std::size_t> PartyDetailsListRequestArgs_count_requesting_party_i_ds(::fixpp::v50sp2::PartyDetailsListRequestArgs const& a) noexcept { if (!a.requesting_party_i_ds) { return ::std::nullopt; } return a.requesting_party_i_ds->size(); }
inline ::fixpp::core::expected_t<void> PartyDetailsListRequestArgs_validate_entry_requesting_party_i_ds(::fixpp::v50sp2::PartyDetailsListRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.requesting_party_i_ds)[i]); }
template <> struct writer_traits<::fixpp::v50sp2::PartyDetailsListRequestArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::v50sp2::PartyDetailsListRequestArgs>, 1> required_checks = {{
        {1505, &PartyDetailsListRequestArgs_required_1505},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::v50sp2::PartyDetailsListRequestArgs>, 4> group_checks = {{
        {false, &PartyDetailsListRequestArgs_count_party_i_ds, &PartyDetailsListRequestArgs_validate_entry_party_i_ds},
        {false, &PartyDetailsListRequestArgs_count_requested_party_roles, &PartyDetailsListRequestArgs_validate_entry_requested_party_roles},
        {false, &PartyDetailsListRequestArgs_count_party_relationships, &PartyDetailsListRequestArgs_validate_entry_party_relationships},
        {false, &PartyDetailsListRequestArgs_count_requesting_party_i_ds, &PartyDetailsListRequestArgs_validate_entry_requesting_party_i_ds},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::v50sp2 {

inline ::fixpp::core::expected_t<void> validate_PartyDetailsListRequest(PartyDetailsListRequestArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::v50sp2
