// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v50sp2/messages/SettlementInstructionRequest.builder.inl -- inline build_ body (data-model.md Entity 3); no validator symbol (SC-003).
#pragma once
#include "SettlementInstructionRequest.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::v50sp2 {

inline ::fixpp::core::expected_t<::std::span<::std::byte>> build_SettlementInstructionRequest(::std::span<::std::byte> out, SettlementInstructionRequestArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"AV"};
    if (args.side) {
        auto r = bb.field(54, *args.side);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.transact_time) {
        auto r = bb.field(60, *args.transact_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.alloc_account) {
        auto r = bb.field(79, *args.alloc_account);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.settl_currency) {
        auto r = bb.field(120, *args.settl_currency);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.expire_time) {
        auto r = bb.field(126, *args.expire_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_type) {
        auto r = bb.field(167, *args.security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.effective_time) {
        auto r = bb.field(168, *args.effective_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.stand_inst_db_type) {
        auto r = bb.field(169, *args.stand_inst_db_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.stand_inst_db_name) {
        auto r = bb.field(170, *args.stand_inst_db_name);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.stand_inst_db_id) {
        auto r = bb.field(171, *args.stand_inst_db_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.party_i_ds) {
        auto gh0 = bb.group_begin(453, 448);
        if (!gh0) return ::std::unexpected(gh0.error());
        for (auto const& item0 : *args.party_i_ds) {
            auto en0 = gh0->add_entry();
            if (!en0) return ::std::unexpected(en0.error());
            auto& eh0 = *en0;
    if (item0.party_id) {
        auto r = eh0.set_string(448, *item0.party_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_id_source) {
        auto r = eh0.set_char(447, *item0.party_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_role) {
        auto r = eh0.set_int(452, *item0.party_role);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_role_qualifier) {
        auto r = eh0.set_int(2376, *item0.party_role_qualifier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.party_sub_i_ds) {
        auto gh1 = eh0.group_begin(802, 523);
        if (!gh1) return ::std::unexpected(gh1.error());
        for (auto const& item1 : *item0.party_sub_i_ds) {
            auto en1 = gh1->add_entry();
            if (!en1) return ::std::unexpected(en1.error());
            auto& eh1 = *en1;
    if (item1.party_sub_id) {
        auto r = eh1.set_string(523, *item1.party_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item1.party_sub_id_type) {
        auto r = eh1.set_int(803, *item1.party_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge1 = bb.group_end(*gh1);
        if (!ge1) return ::std::unexpected(ge1.error());
    }
        }
        auto ge0 = bb.group_end(*gh0);
        if (!ge0) return ::std::unexpected(ge0.error());
    }
    if (args.product) {
        auto r = bb.field(460, *args.product);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.cfi_code) {
        auto r = bb.field(461, *args.cfi_code);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.alloc_acct_id_source) {
        auto r = bb.field(661, *args.alloc_acct_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.last_update_time) {
        auto r = bb.field(779, *args.last_update_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.settl_inst_req_id) {
        auto r = bb.field(791, *args.settl_inst_req_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.upi_code) {
        auto r = bb.field(2891, *args.upi_code);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.settl_currency_code_source) {
        auto r = bb.field(2899, *args.settl_currency_code_source);
        if (!r) return ::std::unexpected(r.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::v50sp2
