// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v50sp2/messages/SettlementObligationReport.validator.cpp -- external-linkage validate_ definition + this message's own top-level traits (data-model.md Entity 4), compiled only into fixpp_validators_<ver>.
#include "SettlementObligationReport.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool SettlementObligationReportArgs_required_1159(::fixpp::v50sp2::SettlementObligationReportArgs const& a) noexcept { return a.settl_oblig_mode.has_value(); }
inline bool SettlementObligationReportArgs_required_1160(::fixpp::v50sp2::SettlementObligationReportArgs const& a) noexcept { return a.settl_oblig_msg_id.has_value(); }
inline ::std::optional<::std::size_t> SettlementObligationReportArgs_count_settl_oblig(::fixpp::v50sp2::SettlementObligationReportArgs const& a) noexcept { if (!a.settl_oblig) { return ::std::nullopt; } return a.settl_oblig->size(); }
inline ::fixpp::core::expected_t<void> SettlementObligationReportArgs_validate_entry_settl_oblig(::fixpp::v50sp2::SettlementObligationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.settl_oblig)[i]); }
template <> struct writer_traits<::fixpp::v50sp2::SettlementObligationReportArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::v50sp2::SettlementObligationReportArgs>, 2> required_checks = {{
        {1159, &SettlementObligationReportArgs_required_1159},
        {1160, &SettlementObligationReportArgs_required_1160},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::v50sp2::SettlementObligationReportArgs>, 1> group_checks = {{
        {false, &SettlementObligationReportArgs_count_settl_oblig, &SettlementObligationReportArgs_validate_entry_settl_oblig},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::v50sp2 {

::fixpp::core::expected_t<void> validate_SettlementObligationReport(SettlementObligationReportArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::v50sp2
