// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v50sp2/messages/TradeAggregationReport.validator.inl -- inline validate_ body + this message's own top-level traits (data-model.md Entity 3).
#pragma once
#include "TradeAggregationReport.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool TradeAggregationReportArgs_required_2790(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { return a.trade_aggregation_request_status.has_value(); }
inline bool TradeAggregationReportArgs_required_2792(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { return a.trade_aggregation_report_id.has_value(); }
inline ::std::optional<::std::size_t> TradeAggregationReportArgs_count_security_alt_id(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { if (!a.security_alt_id) { return ::std::nullopt; } return a.security_alt_id->size(); }
inline ::fixpp::core::expected_t<void> TradeAggregationReportArgs_validate_entry_security_alt_id(::fixpp::v50sp2::TradeAggregationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.security_alt_id)[i]); }
inline ::std::optional<::std::size_t> TradeAggregationReportArgs_count_events(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { if (!a.events) { return ::std::nullopt; } return a.events->size(); }
inline ::fixpp::core::expected_t<void> TradeAggregationReportArgs_validate_entry_events(::fixpp::v50sp2::TradeAggregationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.events)[i]); }
inline ::std::optional<::std::size_t> TradeAggregationReportArgs_count_instrument_parties(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { if (!a.instrument_parties) { return ::std::nullopt; } return a.instrument_parties->size(); }
inline ::fixpp::core::expected_t<void> TradeAggregationReportArgs_validate_entry_instrument_parties(::fixpp::v50sp2::TradeAggregationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.instrument_parties)[i]); }
inline ::std::optional<::std::size_t> TradeAggregationReportArgs_count_complex_events(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { if (!a.complex_events) { return ::std::nullopt; } return a.complex_events->size(); }
inline ::fixpp::core::expected_t<void> TradeAggregationReportArgs_validate_entry_complex_events(::fixpp::v50sp2::TradeAggregationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.complex_events)[i]); }
inline ::std::optional<::std::size_t> TradeAggregationReportArgs_count_secondary_asset_classes(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { if (!a.secondary_asset_classes) { return ::std::nullopt; } return a.secondary_asset_classes->size(); }
inline ::fixpp::core::expected_t<void> TradeAggregationReportArgs_validate_entry_secondary_asset_classes(::fixpp::v50sp2::TradeAggregationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.secondary_asset_classes)[i]); }
inline ::std::optional<::std::size_t> TradeAggregationReportArgs_count_asset_attributes(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { if (!a.asset_attributes) { return ::std::nullopt; } return a.asset_attributes->size(); }
inline ::fixpp::core::expected_t<void> TradeAggregationReportArgs_validate_entry_asset_attributes(::fixpp::v50sp2::TradeAggregationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.asset_attributes)[i]); }
inline ::std::optional<::std::size_t> TradeAggregationReportArgs_count_additional_terms(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { if (!a.additional_terms) { return ::std::nullopt; } return a.additional_terms->size(); }
inline ::fixpp::core::expected_t<void> TradeAggregationReportArgs_validate_entry_additional_terms(::fixpp::v50sp2::TradeAggregationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.additional_terms)[i]); }
inline ::std::optional<::std::size_t> TradeAggregationReportArgs_count_cash_settl_terms(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { if (!a.cash_settl_terms) { return ::std::nullopt; } return a.cash_settl_terms->size(); }
inline ::fixpp::core::expected_t<void> TradeAggregationReportArgs_validate_entry_cash_settl_terms(::fixpp::v50sp2::TradeAggregationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.cash_settl_terms)[i]); }
inline ::std::optional<::std::size_t> TradeAggregationReportArgs_count_streams(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { if (!a.streams) { return ::std::nullopt; } return a.streams->size(); }
inline ::fixpp::core::expected_t<void> TradeAggregationReportArgs_validate_entry_streams(::fixpp::v50sp2::TradeAggregationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.streams)[i]); }
inline ::std::optional<::std::size_t> TradeAggregationReportArgs_count_provisions(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { if (!a.provisions) { return ::std::nullopt; } return a.provisions->size(); }
inline ::fixpp::core::expected_t<void> TradeAggregationReportArgs_validate_entry_provisions(::fixpp::v50sp2::TradeAggregationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.provisions)[i]); }
inline ::std::optional<::std::size_t> TradeAggregationReportArgs_count_protection_terms(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { if (!a.protection_terms) { return ::std::nullopt; } return a.protection_terms->size(); }
inline ::fixpp::core::expected_t<void> TradeAggregationReportArgs_validate_entry_protection_terms(::fixpp::v50sp2::TradeAggregationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.protection_terms)[i]); }
inline ::std::optional<::std::size_t> TradeAggregationReportArgs_count_physical_settl_terms(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { if (!a.physical_settl_terms) { return ::std::nullopt; } return a.physical_settl_terms->size(); }
inline ::fixpp::core::expected_t<void> TradeAggregationReportArgs_validate_entry_physical_settl_terms(::fixpp::v50sp2::TradeAggregationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.physical_settl_terms)[i]); }
inline ::std::optional<::std::size_t> TradeAggregationReportArgs_count_business_centers(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { if (!a.business_centers) { return ::std::nullopt; } return a.business_centers->size(); }
inline ::fixpp::core::expected_t<void> TradeAggregationReportArgs_validate_entry_business_centers(::fixpp::v50sp2::TradeAggregationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.business_centers)[i]); }
inline ::std::optional<::std::size_t> TradeAggregationReportArgs_count_market_disruption_events(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { if (!a.market_disruption_events) { return ::std::nullopt; } return a.market_disruption_events->size(); }
inline ::fixpp::core::expected_t<void> TradeAggregationReportArgs_validate_entry_market_disruption_events(::fixpp::v50sp2::TradeAggregationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.market_disruption_events)[i]); }
inline ::std::optional<::std::size_t> TradeAggregationReportArgs_count_market_disruption_fallbacks(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { if (!a.market_disruption_fallbacks) { return ::std::nullopt; } return a.market_disruption_fallbacks->size(); }
inline ::fixpp::core::expected_t<void> TradeAggregationReportArgs_validate_entry_market_disruption_fallbacks(::fixpp::v50sp2::TradeAggregationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.market_disruption_fallbacks)[i]); }
inline ::std::optional<::std::size_t> TradeAggregationReportArgs_count_market_disruption_fallback_reference_prices(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { if (!a.market_disruption_fallback_reference_prices) { return ::std::nullopt; } return a.market_disruption_fallback_reference_prices->size(); }
inline ::fixpp::core::expected_t<void> TradeAggregationReportArgs_validate_entry_market_disruption_fallback_reference_prices(::fixpp::v50sp2::TradeAggregationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.market_disruption_fallback_reference_prices)[i]); }
inline ::std::optional<::std::size_t> TradeAggregationReportArgs_count_option_exercise_business_centers(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { if (!a.option_exercise_business_centers) { return ::std::nullopt; } return a.option_exercise_business_centers->size(); }
inline ::fixpp::core::expected_t<void> TradeAggregationReportArgs_validate_entry_option_exercise_business_centers(::fixpp::v50sp2::TradeAggregationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.option_exercise_business_centers)[i]); }
inline ::std::optional<::std::size_t> TradeAggregationReportArgs_count_option_exercise_dates(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { if (!a.option_exercise_dates) { return ::std::nullopt; } return a.option_exercise_dates->size(); }
inline ::fixpp::core::expected_t<void> TradeAggregationReportArgs_validate_entry_option_exercise_dates(::fixpp::v50sp2::TradeAggregationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.option_exercise_dates)[i]); }
inline ::std::optional<::std::size_t> TradeAggregationReportArgs_count_option_exercise_expiration_date_business_centers(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { if (!a.option_exercise_expiration_date_business_centers) { return ::std::nullopt; } return a.option_exercise_expiration_date_business_centers->size(); }
inline ::fixpp::core::expected_t<void> TradeAggregationReportArgs_validate_entry_option_exercise_expiration_date_business_centers(::fixpp::v50sp2::TradeAggregationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.option_exercise_expiration_date_business_centers)[i]); }
inline ::std::optional<::std::size_t> TradeAggregationReportArgs_count_option_exercise_expiration_dates(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { if (!a.option_exercise_expiration_dates) { return ::std::nullopt; } return a.option_exercise_expiration_dates->size(); }
inline ::fixpp::core::expected_t<void> TradeAggregationReportArgs_validate_entry_option_exercise_expiration_dates(::fixpp::v50sp2::TradeAggregationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.option_exercise_expiration_dates)[i]); }
inline ::std::optional<::std::size_t> TradeAggregationReportArgs_count_pricing_date_business_centers(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { if (!a.pricing_date_business_centers) { return ::std::nullopt; } return a.pricing_date_business_centers->size(); }
inline ::fixpp::core::expected_t<void> TradeAggregationReportArgs_validate_entry_pricing_date_business_centers(::fixpp::v50sp2::TradeAggregationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.pricing_date_business_centers)[i]); }
inline ::std::optional<::std::size_t> TradeAggregationReportArgs_count_extraordinary_events(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { if (!a.extraordinary_events) { return ::std::nullopt; } return a.extraordinary_events->size(); }
inline ::fixpp::core::expected_t<void> TradeAggregationReportArgs_validate_entry_extraordinary_events(::fixpp::v50sp2::TradeAggregationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.extraordinary_events)[i]); }
inline ::std::optional<::std::size_t> TradeAggregationReportArgs_count_settl_method_election_date_business_centers(::fixpp::v50sp2::TradeAggregationReportArgs const& a) noexcept { if (!a.settl_method_election_date_business_centers) { return ::std::nullopt; } return a.settl_method_election_date_business_centers->size(); }
inline ::fixpp::core::expected_t<void> TradeAggregationReportArgs_validate_entry_settl_method_election_date_business_centers(::fixpp::v50sp2::TradeAggregationReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.settl_method_election_date_business_centers)[i]); }
template <> struct writer_traits<::fixpp::v50sp2::TradeAggregationReportArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::v50sp2::TradeAggregationReportArgs>, 2> required_checks = {{
        {2790, &TradeAggregationReportArgs_required_2790},
        {2792, &TradeAggregationReportArgs_required_2792},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::v50sp2::TradeAggregationReportArgs>, 23> group_checks = {{
        {false, &TradeAggregationReportArgs_count_security_alt_id, &TradeAggregationReportArgs_validate_entry_security_alt_id},
        {false, &TradeAggregationReportArgs_count_events, &TradeAggregationReportArgs_validate_entry_events},
        {false, &TradeAggregationReportArgs_count_instrument_parties, &TradeAggregationReportArgs_validate_entry_instrument_parties},
        {false, &TradeAggregationReportArgs_count_complex_events, &TradeAggregationReportArgs_validate_entry_complex_events},
        {false, &TradeAggregationReportArgs_count_secondary_asset_classes, &TradeAggregationReportArgs_validate_entry_secondary_asset_classes},
        {false, &TradeAggregationReportArgs_count_asset_attributes, &TradeAggregationReportArgs_validate_entry_asset_attributes},
        {false, &TradeAggregationReportArgs_count_additional_terms, &TradeAggregationReportArgs_validate_entry_additional_terms},
        {false, &TradeAggregationReportArgs_count_cash_settl_terms, &TradeAggregationReportArgs_validate_entry_cash_settl_terms},
        {false, &TradeAggregationReportArgs_count_streams, &TradeAggregationReportArgs_validate_entry_streams},
        {false, &TradeAggregationReportArgs_count_provisions, &TradeAggregationReportArgs_validate_entry_provisions},
        {false, &TradeAggregationReportArgs_count_protection_terms, &TradeAggregationReportArgs_validate_entry_protection_terms},
        {false, &TradeAggregationReportArgs_count_physical_settl_terms, &TradeAggregationReportArgs_validate_entry_physical_settl_terms},
        {false, &TradeAggregationReportArgs_count_business_centers, &TradeAggregationReportArgs_validate_entry_business_centers},
        {false, &TradeAggregationReportArgs_count_market_disruption_events, &TradeAggregationReportArgs_validate_entry_market_disruption_events},
        {false, &TradeAggregationReportArgs_count_market_disruption_fallbacks, &TradeAggregationReportArgs_validate_entry_market_disruption_fallbacks},
        {false, &TradeAggregationReportArgs_count_market_disruption_fallback_reference_prices, &TradeAggregationReportArgs_validate_entry_market_disruption_fallback_reference_prices},
        {false, &TradeAggregationReportArgs_count_option_exercise_business_centers, &TradeAggregationReportArgs_validate_entry_option_exercise_business_centers},
        {false, &TradeAggregationReportArgs_count_option_exercise_dates, &TradeAggregationReportArgs_validate_entry_option_exercise_dates},
        {false, &TradeAggregationReportArgs_count_option_exercise_expiration_date_business_centers, &TradeAggregationReportArgs_validate_entry_option_exercise_expiration_date_business_centers},
        {false, &TradeAggregationReportArgs_count_option_exercise_expiration_dates, &TradeAggregationReportArgs_validate_entry_option_exercise_expiration_dates},
        {false, &TradeAggregationReportArgs_count_pricing_date_business_centers, &TradeAggregationReportArgs_validate_entry_pricing_date_business_centers},
        {false, &TradeAggregationReportArgs_count_extraordinary_events, &TradeAggregationReportArgs_validate_entry_extraordinary_events},
        {false, &TradeAggregationReportArgs_count_settl_method_election_date_business_centers, &TradeAggregationReportArgs_validate_entry_settl_method_election_date_business_centers},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::v50sp2 {

inline ::fixpp::core::expected_t<void> validate_TradeAggregationReport(TradeAggregationReportArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::v50sp2
