// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v44/groups/G_146_2Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include "G_454Args.hpp"
#include "G_864Args.hpp"
#include "G_711_1Args.hpp"
#include "G_232Args.hpp"
#include "G_555_5Args.hpp"
#include "G_735Args.hpp"
#include "G_453Args.hpp"
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::v44::groups {

struct G_146_2Args {
    ::std::optional<::std::string_view> symbol{};
    ::std::optional<::std::string_view> symbol_sfx{};
    ::std::optional<::std::string_view> security_id{};
    ::std::optional<::std::string_view> security_id_source{};
    ::std::optional<::std::span<const G_454Args>> security_alt_id{};
    ::std::optional<::std::int64_t> product{};
    ::std::optional<::std::string_view> cfi_code{};
    ::std::optional<::std::string_view> security_type{};
    ::std::optional<::std::string_view> security_sub_type{};
    ::std::optional<::std::string_view> maturity_month_year{};
    ::std::optional<::std::string_view> maturity_date{};
    ::std::optional<::std::int64_t> put_or_call{};
    ::std::optional<::std::string_view> coupon_payment_date{};
    ::std::optional<::std::string_view> issue_date{};
    ::std::optional<::std::string_view> repo_collateral_security_type{};
    ::std::optional<::std::int64_t> repurchase_term{};
    ::std::optional<::fixpp::decimal_t> repurchase_rate{};
    ::std::optional<::fixpp::decimal_t> factor{};
    ::std::optional<::std::string_view> credit_rating{};
    ::std::optional<::std::string_view> instr_registry{};
    ::std::optional<::std::string_view> country_of_issue{};
    ::std::optional<::std::string_view> state_or_province_of_issue{};
    ::std::optional<::std::string_view> locale_of_issue{};
    ::std::optional<::std::string_view> redemption_date{};
    ::std::optional<::fixpp::decimal_t> strike_price{};
    ::std::optional<::std::string_view> strike_currency{};
    ::std::optional<char> opt_attribute{};
    ::std::optional<::fixpp::decimal_t> contract_multiplier{};
    ::std::optional<::fixpp::decimal_t> coupon_rate{};
    ::std::optional<::std::string_view> security_exchange{};
    ::std::optional<::std::string_view> issuer{};
    ::std::optional<::std::string_view> encoded_issuer{};
    ::std::optional<::std::string_view> security_desc{};
    ::std::optional<::std::string_view> encoded_security_desc{};
    ::std::optional<::std::string_view> pool{};
    ::std::optional<::std::string_view> contract_settl_month{};
    ::std::optional<::std::int64_t> cp_program{};
    ::std::optional<::std::string_view> cp_reg_type{};
    ::std::optional<::std::span<const G_864Args>> events{};
    ::std::optional<::std::string_view> dated_date{};
    ::std::optional<::std::string_view> interest_accrual_date{};
    ::std::optional<::std::string_view> agreement_desc{};
    ::std::optional<::std::string_view> agreement_id{};
    ::std::optional<::std::string_view> agreement_date{};
    ::std::optional<::std::string_view> agreement_currency{};
    ::std::optional<::std::int64_t> termination_type{};
    ::std::optional<::std::string_view> start_date{};
    ::std::optional<::std::string_view> end_date{};
    ::std::optional<::std::int64_t> delivery_type{};
    ::std::optional<::fixpp::decimal_t> margin_ratio{};
    ::std::optional<::std::span<const G_711_1Args>> underlyings{};
    ::std::optional<::fixpp::decimal_t> prev_close_px{};
    ::std::optional<::std::int64_t> quote_request_type{};
    ::std::optional<::std::int64_t> quote_type{};
    ::std::optional<::std::string_view> trading_session_id{};
    ::std::optional<::std::string_view> trading_session_sub_id{};
    ::std::optional<::std::string_view> trade_origination_date{};
    ::std::optional<char> side{};
    ::std::optional<::std::int64_t> qty_type{};
    ::std::optional<::fixpp::decimal_t> order_qty{};
    ::std::optional<::fixpp::decimal_t> cash_order_qty{};
    ::std::optional<::fixpp::decimal_t> order_percent{};
    ::std::optional<char> rounding_direction{};
    ::std::optional<::fixpp::decimal_t> rounding_modulus{};
    ::std::optional<char> settl_type{};
    ::std::optional<::std::string_view> settl_date{};
    ::std::optional<::std::string_view> settl_date2{};
    ::std::optional<::fixpp::decimal_t> order_qty2{};
    ::std::optional<::std::string_view> currency{};
    ::std::optional<::std::span<const G_232Args>> stipulations{};
    ::std::optional<::std::string_view> account{};
    ::std::optional<::std::int64_t> acct_id_source{};
    ::std::optional<::std::int64_t> account_type{};
    ::std::optional<::std::span<const G_555_5Args>> legs{};
    ::std::optional<::std::span<const G_735Args>> quote_qualifiers{};
    ::std::optional<::std::int64_t> quote_price_type{};
    ::std::optional<char> ord_type{};
    ::std::optional<::std::string_view> expire_time{};
    ::std::optional<::std::string_view> transact_time{};
    ::std::optional<::fixpp::decimal_t> spread{};
    ::std::optional<::std::string_view> benchmark_curve_currency{};
    ::std::optional<::std::string_view> benchmark_curve_name{};
    ::std::optional<::std::string_view> benchmark_curve_point{};
    ::std::optional<::fixpp::decimal_t> benchmark_price{};
    ::std::optional<::std::int64_t> benchmark_price_type{};
    ::std::optional<::std::string_view> benchmark_security_id{};
    ::std::optional<::std::string_view> benchmark_security_id_source{};
    ::std::optional<::std::int64_t> price_type{};
    ::std::optional<::fixpp::decimal_t> price{};
    ::std::optional<::fixpp::decimal_t> price2{};
    ::std::optional<::std::string_view> yield_type{};
    ::std::optional<::fixpp::decimal_t> yield{};
    ::std::optional<::std::string_view> yield_calc_date{};
    ::std::optional<::std::string_view> yield_redemption_date{};
    ::std::optional<::fixpp::decimal_t> yield_redemption_price{};
    ::std::optional<::std::int64_t> yield_redemption_price_type{};
    ::std::optional<::std::span<const G_453Args>> party_i_ds{};
};

}  // namespace fixpp::v44::groups
