// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v44/groups/G_552_2Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include "G_453Args.hpp"
#include "G_78_5Args.hpp"
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::v44::groups {

struct G_552_2Args {
    ::std::optional<char> side{};
    ::std::optional<::std::string_view> cl_ord_id{};
    ::std::optional<::std::string_view> secondary_cl_ord_id{};
    ::std::optional<::std::string_view> cl_ord_link_id{};
    ::std::optional<::std::span<const G_453Args>> party_i_ds{};
    ::std::optional<::std::string_view> trade_origination_date{};
    ::std::optional<::std::string_view> trade_date{};
    ::std::optional<::std::string_view> account{};
    ::std::optional<::std::int64_t> acct_id_source{};
    ::std::optional<::std::int64_t> account_type{};
    ::std::optional<char> day_booking_inst{};
    ::std::optional<char> booking_unit{};
    ::std::optional<char> prealloc_method{};
    ::std::optional<::std::string_view> alloc_id{};
    ::std::optional<::std::span<const G_78_5Args>> allocs{};
    ::std::optional<::std::int64_t> qty_type{};
    ::std::optional<::fixpp::decimal_t> order_qty{};
    ::std::optional<::fixpp::decimal_t> cash_order_qty{};
    ::std::optional<::fixpp::decimal_t> order_percent{};
    ::std::optional<char> rounding_direction{};
    ::std::optional<::fixpp::decimal_t> rounding_modulus{};
    ::std::optional<::fixpp::decimal_t> commission{};
    ::std::optional<char> comm_type{};
    ::std::optional<::std::string_view> comm_currency{};
    ::std::optional<char> fund_renew_waiv{};
    ::std::optional<char> order_capacity{};
    ::std::optional<::std::string_view> order_restrictions{};
    ::std::optional<::std::int64_t> cust_order_capacity{};
    ::std::optional<bool> forex_req{};
    ::std::optional<::std::string_view> settl_currency{};
    ::std::optional<::std::int64_t> booking_type{};
    ::std::optional<::std::string_view> text{};
    ::std::optional<::std::string_view> encoded_text{};
    ::std::optional<char> position_effect{};
    ::std::optional<::std::int64_t> covered_or_uncovered{};
    ::std::optional<char> cash_margin{};
    ::std::optional<::std::string_view> clearing_fee_indicator{};
    ::std::optional<bool> solicited_flag{};
    ::std::optional<::std::string_view> side_compliance_id{};
};

}  // namespace fixpp::v44::groups
