// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v42/all.hpp -- aggregator: every messages/<Msg>.hpp + the builder_registry (data-model.md Entity 5); replaces Builders.hpp.
#pragma once
#include "messages/IOI.hpp"
#include "messages/Advertisement.hpp"
#include "messages/ExecutionReport.hpp"
#include "messages/OrderCancelReject.hpp"
#include "messages/News.hpp"
#include "messages/Email.hpp"
#include "messages/NewOrderSingle.hpp"
#include "messages/NewOrderList.hpp"
#include "messages/OrderCancelRequest.hpp"
#include "messages/OrderCancelReplaceRequest.hpp"
#include "messages/OrderStatusRequest.hpp"
#include "messages/Allocation.hpp"
#include "messages/ListCancelRequest.hpp"
#include "messages/ListExecute.hpp"
#include "messages/ListStatusRequest.hpp"
#include "messages/ListStatus.hpp"
#include "messages/AllocationInstructionAck.hpp"
#include "messages/DontKnowTrade.hpp"
#include "messages/QuoteRequest.hpp"
#include "messages/Quote.hpp"
#include "messages/SettlementInstructions.hpp"
#include "messages/MarketDataRequest.hpp"
#include "messages/MarketDataSnapshotFullRefresh.hpp"
#include "messages/MarketDataIncrementalRefresh.hpp"
#include "messages/MarketDataRequestReject.hpp"
#include "messages/QuoteCancel.hpp"
#include "messages/QuoteStatusRequest.hpp"
#include "messages/QuoteAcknowledgement.hpp"
#include "messages/SecurityDefinitionRequest.hpp"
#include "messages/SecurityDefinition.hpp"
#include "messages/SecurityStatusRequest.hpp"
#include "messages/SecurityStatus.hpp"
#include "messages/TradingSessionStatusRequest.hpp"
#include "messages/TradingSessionStatus.hpp"
#include "messages/MassQuote.hpp"
#include "messages/BusinessMessageReject.hpp"
#include "messages/BidRequest.hpp"
#include "messages/BidResponse.hpp"
#include "messages/ListStrikePrice.hpp"
#include <array>
#include <string_view>

namespace fixpp::v42 {

struct builder_registry_entry { ::std::string_view msg_type; };
inline constexpr ::std::array<builder_registry_entry, 39> builder_registry = {{
    {"6"},
    {"7"},
    {"8"},
    {"9"},
    {"B"},
    {"C"},
    {"D"},
    {"E"},
    {"F"},
    {"G"},
    {"H"},
    {"J"},
    {"K"},
    {"L"},
    {"M"},
    {"N"},
    {"P"},
    {"Q"},
    {"R"},
    {"S"},
    {"T"},
    {"V"},
    {"W"},
    {"X"},
    {"Y"},
    {"Z"},
    {"a"},
    {"b"},
    {"c"},
    {"d"},
    {"e"},
    {"f"},
    {"g"},
    {"h"},
    {"i"},
    {"j"},
    {"k"},
    {"l"},
    {"m"},
}};

}  // namespace fixpp::v42
