// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/groups/G_1499_2Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include "G_453Args.hpp"
#include "G_146_8Args.hpp"
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest::groups {

struct G_1499_2Args {
    ::std::optional<::std::span<const G_453Args>> party_i_ds{};
    ::std::optional<::std::span<const G_146_8Args>> related_sym{};
};

}  // namespace fixpp::vlatest::groups
