// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/groups/G_1892Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include "G_948Args.hpp"
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest::groups {

struct G_1892Args {
    ::std::optional<::std::string_view> leg_ref_id{};
    ::std::optional<::std::string_view> leg_exec_id{};
    ::std::optional<::std::string_view> leg_exec_ref_id{};
    ::std::optional<::std::string_view> leg_trade_id{};
    ::std::optional<::std::string_view> leg_trade_report_id{};
    ::std::optional<::fixpp::decimal_t> leg_order_qty{};
    ::std::optional<char> leg_position_effect{};
    ::std::optional<::std::int64_t> leg_covered_or_uncovered{};
    ::std::optional<::std::span<const G_948Args>> nested3_party_i_ds{};
    ::std::optional<::fixpp::decimal_t> leg_last_px{};
    ::std::optional<::std::int64_t> leg_price_type{};
    ::std::optional<::std::string_view> leg_settl_currency{};
    ::std::optional<::std::string_view> leg_settl_currency_code_source{};
    ::std::optional<::std::int64_t> leg_short_sale_exemption_reason{};
    ::std::optional<::fixpp::decimal_t> leg_last_qty{};
    ::std::optional<::std::int64_t> leg_qty_type{};
};

}  // namespace fixpp::vlatest::groups
