// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/groups/G_1971Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest::groups {

struct G_1971Args {
    ::std::optional<::std::string_view> side_regulatory_trade_id{};
    ::std::optional<::std::string_view> side_regulatory_trade_id_source{};
    ::std::optional<::std::int64_t> side_regulatory_trade_id_event{};
    ::std::optional<::std::int64_t> side_regulatory_trade_id_type{};
    ::std::optional<::std::string_view> side_regulatory_leg_ref_id{};
    ::std::optional<::std::int64_t> side_regulatory_trade_id_scope{};
};

}  // namespace fixpp::vlatest::groups
