// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/groups/G_3126Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest::groups {

struct G_3126Args {
    ::std::optional<::std::string_view> test_suite_parameter_name{};
    ::std::optional<::std::int64_t> test_suite_parameter_type{};
    ::std::optional<::std::string_view> test_suite_parameter_value{};
};

}  // namespace fixpp::vlatest::groups
