// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/groups/G_41422Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include "G_41425Args.hpp"
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest::groups {

struct G_41422Args {
    ::std::optional<::std::int64_t> leg_delivery_schedule_settl_day{};
    ::std::optional<::std::int64_t> leg_delivery_schedule_settl_total_hours{};
    ::std::optional<::std::span<const G_41425Args>> leg_delivery_schedule_settl_times{};
};

}  // namespace fixpp::vlatest::groups
