// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/groups/G_41344Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include "G_41342Args.hpp"
#include "G_42306Args.hpp"
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest::groups {

struct G_41344Args {
    ::std::optional<::std::string_view> leg_cash_settl_currency{};
    ::std::optional<::std::int64_t> leg_cas_settl_valuation_first_business_day_offset{};
    ::std::optional<::std::int64_t> leg_cash_settl_valuation_subsequent_business_days_offset{};
    ::std::optional<::std::int64_t> leg_cash_settl_num_of_valuation_dates{};
    ::std::optional<::std::string_view> leg_cash_settl_valuation_time{};
    ::std::optional<::std::string_view> leg_cash_settl_business_center{};
    ::std::optional<::std::int64_t> leg_cash_settl_quote_method{};
    ::std::optional<::fixpp::decimal_t> leg_cash_settl_quote_amount{};
    ::std::optional<::std::string_view> leg_cash_settl_quote_currency{};
    ::std::optional<::fixpp::decimal_t> leg_cash_settl_minimum_quote_amount{};
    ::std::optional<::std::string_view> leg_cash_settl_minimum_quote_currency{};
    ::std::optional<::std::span<const G_41342Args>> leg_cash_settl_dealers{};
    ::std::optional<::std::string_view> leg_cash_settl_price_source{};
    ::std::optional<::std::int64_t> leg_cash_settl_price_default{};
    ::std::optional<::std::int64_t> leg_cash_settl_business_days{};
    ::std::optional<::fixpp::decimal_t> leg_cash_settl_amount{};
    ::std::optional<::std::string_view> leg_cash_settl_date_unadjusted{};
    ::std::optional<::std::int64_t> leg_cash_settl_date_business_day_convention{};
    ::std::optional<::std::span<const G_42306Args>> leg_cash_settl_date_business_centers{};
    ::std::optional<::std::int64_t> leg_cash_settl_date_relative_to{};
    ::std::optional<::std::int64_t> leg_cash_settl_date_offset_period{};
    ::std::optional<::std::string_view> leg_cash_settl_date_offset_unit{};
    ::std::optional<::std::int64_t> leg_cash_settl_date_offset_day_type{};
    ::std::optional<::std::string_view> leg_cash_settl_date_adjusted{};
    ::std::optional<::fixpp::decimal_t> leg_cash_settl_recovery_factor{};
    ::std::optional<bool> leg_cash_settl_fixed_term_indicator{};
    ::std::optional<bool> leg_cash_settl_accrued_interest_indicator{};
    ::std::optional<::std::int64_t> leg_cash_settl_valuation_method{};
    ::std::optional<::std::string_view> leg_cash_settl_term_xid{};
};

}  // namespace fixpp::vlatest::groups
