// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v42/messages/ListStrikePrice.builder.inl -- inline build_ body (data-model.md Entity 3); no validator symbol (SC-003).
#pragma once
#include "ListStrikePrice.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::v42 {

inline ::fixpp::core::expected_t<::std::span<::std::byte>> build_ListStrikePrice(::std::span<::std::byte> out, ListStrikePriceArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"m"};
    if (args.list_id) {
        auto r = bb.field(66, *args.list_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.tot_no_strikes) {
        auto r = bb.field(422, *args.tot_no_strikes);
        if (!r) return ::std::unexpected(r.error());
    }
    {
        auto gh0 = bb.group_begin(428, 55);
        if (!gh0) return ::std::unexpected(gh0.error());
        for (auto const& item0 : args.strikes) {
            auto en0 = gh0->add_entry();
            if (!en0) return ::std::unexpected(en0.error());
            auto& eh0 = *en0;
    if (item0.symbol) {
        auto r = eh0.set_string(55, *item0.symbol);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.symbol_sfx) {
        auto r = eh0.set_string(65, *item0.symbol_sfx);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.security_id) {
        auto r = eh0.set_string(48, *item0.security_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.id_source) {
        auto r = eh0.set_string(22, *item0.id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.security_type) {
        auto r = eh0.set_string(167, *item0.security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.maturity_month_year) {
        auto r = eh0.set_string(200, *item0.maturity_month_year);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.maturity_day) {
        auto r = eh0.set_int(205, *item0.maturity_day);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.put_or_call) {
        auto r = eh0.set_int(201, *item0.put_or_call);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.strike_price) {
        auto r = eh0.set_decimal(202, *item0.strike_price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.opt_attribute) {
        auto r = eh0.set_char(206, *item0.opt_attribute);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.contract_multiplier) {
        auto r = eh0.set_decimal(231, *item0.contract_multiplier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.coupon_rate) {
        auto r = eh0.set_decimal(223, *item0.coupon_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.security_exchange) {
        auto r = eh0.set_string(207, *item0.security_exchange);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.issuer) {
        auto r = eh0.set_string(106, *item0.issuer);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.encoded_issuer) {
        auto r_len = eh0.set_int(348, static_cast<::std::int64_t>(item0.encoded_issuer->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = eh0.set_string(349, *item0.encoded_issuer);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (item0.security_desc) {
        auto r = eh0.set_string(107, *item0.security_desc);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.encoded_security_desc) {
        auto r_len = eh0.set_int(350, static_cast<::std::int64_t>(item0.encoded_security_desc->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = eh0.set_string(351, *item0.encoded_security_desc);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (item0.prev_close_px) {
        auto r = eh0.set_decimal(140, *item0.prev_close_px);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.cl_ord_id) {
        auto r = eh0.set_string(11, *item0.cl_ord_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.side) {
        auto r = eh0.set_char(54, *item0.side);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.price) {
        auto r = eh0.set_decimal(44, *item0.price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.currency) {
        auto r = eh0.set_string(15, *item0.currency);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.text) {
        auto r = eh0.set_string(58, *item0.text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.encoded_text) {
        auto r_len = eh0.set_int(354, static_cast<::std::int64_t>(item0.encoded_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = eh0.set_string(355, *item0.encoded_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
        }
        auto ge0 = bb.group_end(*gh0);
        if (!ge0) return ::std::unexpected(ge0.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::v42
