// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v42/messages/MarketDataRequestReject.validator.inl -- inline validate_ body + this message's own top-level traits (data-model.md Entity 3).
#pragma once
#include "MarketDataRequestReject.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool MarketDataRequestRejectArgs_required_262(::fixpp::v42::MarketDataRequestRejectArgs const& a) noexcept { return a.md_req_id.has_value(); }
template <> struct writer_traits<::fixpp::v42::MarketDataRequestRejectArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::v42::MarketDataRequestRejectArgs>, 1> required_checks = {{
        {262, &MarketDataRequestRejectArgs_required_262},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::v42::MarketDataRequestRejectArgs>, 0> group_checks = {};
};

}  // namespace fixpp::wire

namespace fixpp::v42 {

inline ::fixpp::core::expected_t<void> validate_MarketDataRequestReject(MarketDataRequestRejectArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::v42
