// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v42/messages/MarketDataSnapshotFullRefresh.builder.cpp -- external-linkage build_ definition (data-model.md Entity 4), compiled only into fixpp_builders_<ver>; no validator symbol (SC-003).
#include "MarketDataSnapshotFullRefresh.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::v42 {

::fixpp::core::expected_t<::std::span<::std::byte>> build_MarketDataSnapshotFullRefresh(::std::span<::std::byte> out, MarketDataSnapshotFullRefreshArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"W"};
    if (args.id_source) {
        auto r = bb.field(22, *args.id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_id) {
        auto r = bb.field(48, *args.security_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.symbol) {
        auto r = bb.field(55, *args.symbol);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.symbol_sfx) {
        auto r = bb.field(65, *args.symbol_sfx);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.issuer) {
        auto r = bb.field(106, *args.issuer);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_desc) {
        auto r = bb.field(107, *args.security_desc);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_type) {
        auto r = bb.field(167, *args.security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.maturity_month_year) {
        auto r = bb.field(200, *args.maturity_month_year);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.put_or_call) {
        auto r = bb.field(201, *args.put_or_call);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.strike_price) {
        auto r = bb.field(202, *args.strike_price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.maturity_day) {
        auto r = bb.field(205, *args.maturity_day);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.opt_attribute) {
        auto r = bb.field(206, *args.opt_attribute);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_exchange) {
        auto r = bb.field(207, *args.security_exchange);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.coupon_rate) {
        auto r = bb.field(223, *args.coupon_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.contract_multiplier) {
        auto r = bb.field(231, *args.contract_multiplier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.md_req_id) {
        auto r = bb.field(262, *args.md_req_id);
        if (!r) return ::std::unexpected(r.error());
    }
    {
        auto gh0 = bb.group_begin(268, 269);
        if (!gh0) return ::std::unexpected(gh0.error());
        for (auto const& item0 : args.md_entries) {
            auto en0 = gh0->add_entry();
            if (!en0) return ::std::unexpected(en0.error());
            auto& eh0 = *en0;
    if (item0.md_entry_type) {
        auto r = eh0.set_char(269, *item0.md_entry_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.md_entry_px) {
        auto r = eh0.set_decimal(270, *item0.md_entry_px);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.currency) {
        auto r = eh0.set_string(15, *item0.currency);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.md_entry_size) {
        auto r = eh0.set_decimal(271, *item0.md_entry_size);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.md_entry_date) {
        auto r = eh0.set_string(272, *item0.md_entry_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.md_entry_time) {
        auto r = eh0.set_string(273, *item0.md_entry_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.tick_direction) {
        auto r = eh0.set_char(274, *item0.tick_direction);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.md_mkt) {
        auto r = eh0.set_string(275, *item0.md_mkt);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.trading_session_id) {
        auto r = eh0.set_string(336, *item0.trading_session_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.quote_condition) {
        auto r = eh0.set_string(276, *item0.quote_condition);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.trade_condition) {
        auto r = eh0.set_string(277, *item0.trade_condition);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.md_entry_originator) {
        auto r = eh0.set_string(282, *item0.md_entry_originator);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.location_id) {
        auto r = eh0.set_string(283, *item0.location_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.desk_id) {
        auto r = eh0.set_string(284, *item0.desk_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.open_close_settle_flag) {
        auto r = eh0.set_char(286, *item0.open_close_settle_flag);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.time_in_force) {
        auto r = eh0.set_char(59, *item0.time_in_force);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.expire_date) {
        auto r = eh0.set_string(432, *item0.expire_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.expire_time) {
        auto r = eh0.set_string(126, *item0.expire_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.min_qty) {
        auto r = eh0.set_decimal(110, *item0.min_qty);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.exec_inst) {
        auto r = eh0.set_string(18, *item0.exec_inst);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.seller_days) {
        auto r = eh0.set_int(287, *item0.seller_days);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.order_id) {
        auto r = eh0.set_string(37, *item0.order_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.quote_entry_id) {
        auto r = eh0.set_string(299, *item0.quote_entry_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.md_entry_buyer) {
        auto r = eh0.set_string(288, *item0.md_entry_buyer);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.md_entry_seller) {
        auto r = eh0.set_string(289, *item0.md_entry_seller);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.number_of_orders) {
        auto r = eh0.set_int(346, *item0.number_of_orders);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.md_entry_position_no) {
        auto r = eh0.set_int(290, *item0.md_entry_position_no);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.text) {
        auto r = eh0.set_string(58, *item0.text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.encoded_text) {
        auto r_len = eh0.set_int(354, static_cast<::std::int64_t>(item0.encoded_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = eh0.set_string(355, *item0.encoded_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
        }
        auto ge0 = bb.group_end(*gh0);
        if (!ge0) return ::std::unexpected(ge0.error());
    }
    if (args.financial_status) {
        auto r = bb.field(291, *args.financial_status);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.corporate_action) {
        auto r = bb.field(292, *args.corporate_action);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_issuer) {
        auto r_len = bb.field(348, static_cast<::std::int64_t>(args.encoded_issuer->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(349, *args.encoded_issuer);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.encoded_security_desc) {
        auto r_len = bb.field(350, static_cast<::std::int64_t>(args.encoded_security_desc->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(351, *args.encoded_security_desc);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.total_volume_traded) {
        auto r = bb.field(387, *args.total_volume_traded);
        if (!r) return ::std::unexpected(r.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::v42
