// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v42/messages/NewOrderSingle.validator.inl -- inline validate_ body + this message's own top-level traits (data-model.md Entity 3).
#pragma once
#include "NewOrderSingle.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool NewOrderSingleArgs_required_11(::fixpp::v42::NewOrderSingleArgs const& a) noexcept { return a.cl_ord_id.has_value(); }
inline bool NewOrderSingleArgs_required_21(::fixpp::v42::NewOrderSingleArgs const& a) noexcept { return a.handl_inst.has_value(); }
inline bool NewOrderSingleArgs_required_40(::fixpp::v42::NewOrderSingleArgs const& a) noexcept { return a.ord_type.has_value(); }
inline bool NewOrderSingleArgs_required_54(::fixpp::v42::NewOrderSingleArgs const& a) noexcept { return a.side.has_value(); }
inline bool NewOrderSingleArgs_required_55(::fixpp::v42::NewOrderSingleArgs const& a) noexcept { return a.symbol.has_value(); }
inline bool NewOrderSingleArgs_required_60(::fixpp::v42::NewOrderSingleArgs const& a) noexcept { return a.transact_time.has_value(); }
inline ::std::optional<::std::size_t> NewOrderSingleArgs_count_allocs(::fixpp::v42::NewOrderSingleArgs const& a) noexcept { if (!a.allocs) { return ::std::nullopt; } return a.allocs->size(); }
inline ::fixpp::core::expected_t<void> NewOrderSingleArgs_validate_entry_allocs(::fixpp::v42::NewOrderSingleArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.allocs)[i]); }
inline ::std::optional<::std::size_t> NewOrderSingleArgs_count_trading_sessions(::fixpp::v42::NewOrderSingleArgs const& a) noexcept { if (!a.trading_sessions) { return ::std::nullopt; } return a.trading_sessions->size(); }
inline ::fixpp::core::expected_t<void> NewOrderSingleArgs_validate_entry_trading_sessions(::fixpp::v42::NewOrderSingleArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.trading_sessions)[i]); }
template <> struct writer_traits<::fixpp::v42::NewOrderSingleArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::v42::NewOrderSingleArgs>, 6> required_checks = {{
        {11, &NewOrderSingleArgs_required_11},
        {21, &NewOrderSingleArgs_required_21},
        {40, &NewOrderSingleArgs_required_40},
        {54, &NewOrderSingleArgs_required_54},
        {55, &NewOrderSingleArgs_required_55},
        {60, &NewOrderSingleArgs_required_60},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::v42::NewOrderSingleArgs>, 2> group_checks = {{
        {false, &NewOrderSingleArgs_count_allocs, &NewOrderSingleArgs_validate_entry_allocs},
        {false, &NewOrderSingleArgs_count_trading_sessions, &NewOrderSingleArgs_validate_entry_trading_sessions},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::v42 {

inline ::fixpp::core::expected_t<void> validate_NewOrderSingle(NewOrderSingleArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::v42
