// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v42/messages/NewOrderList.builder.cpp -- external-linkage build_ definition (data-model.md Entity 4), compiled only into fixpp_builders_<ver>; no validator symbol (SC-003).
#include "NewOrderList.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::v42 {

::fixpp::core::expected_t<::std::span<::std::byte>> build_NewOrderList(::std::span<::std::byte> out, NewOrderListArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"E"};
    if (args.list_id) {
        auto r = bb.field(66, *args.list_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.tot_no_orders) {
        auto r = bb.field(68, *args.tot_no_orders);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.list_exec_inst) {
        auto r = bb.field(69, *args.list_exec_inst);
        if (!r) return ::std::unexpected(r.error());
    }
    {
        auto gh0 = bb.group_begin(73, 11);
        if (!gh0) return ::std::unexpected(gh0.error());
        for (auto const& item0 : args.orders) {
            auto en0 = gh0->add_entry();
            if (!en0) return ::std::unexpected(en0.error());
            auto& eh0 = *en0;
    if (item0.cl_ord_id) {
        auto r = eh0.set_string(11, *item0.cl_ord_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.list_seq_no) {
        auto r = eh0.set_int(67, *item0.list_seq_no);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.settl_inst_mode) {
        auto r = eh0.set_char(160, *item0.settl_inst_mode);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.client_id) {
        auto r = eh0.set_string(109, *item0.client_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.exec_broker) {
        auto r = eh0.set_string(76, *item0.exec_broker);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.account) {
        auto r = eh0.set_string(1, *item0.account);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.allocs) {
        auto gh1 = eh0.group_begin(78, 79);
        if (!gh1) return ::std::unexpected(gh1.error());
        for (auto const& item1 : *item0.allocs) {
            auto en1 = gh1->add_entry();
            if (!en1) return ::std::unexpected(en1.error());
            auto& eh1 = *en1;
    if (item1.alloc_account) {
        auto r = eh1.set_string(79, *item1.alloc_account);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item1.alloc_shares) {
        auto r = eh1.set_decimal(80, *item1.alloc_shares);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge1 = bb.group_end(*gh1);
        if (!ge1) return ::std::unexpected(ge1.error());
    }
    if (item0.settlmnt_typ) {
        auto r = eh0.set_char(63, *item0.settlmnt_typ);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.fut_sett_date) {
        auto r = eh0.set_string(64, *item0.fut_sett_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.handl_inst) {
        auto r = eh0.set_char(21, *item0.handl_inst);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.exec_inst) {
        auto r = eh0.set_string(18, *item0.exec_inst);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.min_qty) {
        auto r = eh0.set_decimal(110, *item0.min_qty);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.max_floor) {
        auto r = eh0.set_decimal(111, *item0.max_floor);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.ex_destination) {
        auto r = eh0.set_string(100, *item0.ex_destination);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.trading_sessions) {
        auto gh2 = eh0.group_begin(386, 336);
        if (!gh2) return ::std::unexpected(gh2.error());
        for (auto const& item2 : *item0.trading_sessions) {
            auto en2 = gh2->add_entry();
            if (!en2) return ::std::unexpected(en2.error());
            auto& eh2 = *en2;
    if (item2.trading_session_id) {
        auto r = eh2.set_string(336, *item2.trading_session_id);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge2 = bb.group_end(*gh2);
        if (!ge2) return ::std::unexpected(ge2.error());
    }
    if (item0.process_code) {
        auto r = eh0.set_char(81, *item0.process_code);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.symbol) {
        auto r = eh0.set_string(55, *item0.symbol);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.symbol_sfx) {
        auto r = eh0.set_string(65, *item0.symbol_sfx);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.security_id) {
        auto r = eh0.set_string(48, *item0.security_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.id_source) {
        auto r = eh0.set_string(22, *item0.id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.security_type) {
        auto r = eh0.set_string(167, *item0.security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.maturity_month_year) {
        auto r = eh0.set_string(200, *item0.maturity_month_year);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.maturity_day) {
        auto r = eh0.set_int(205, *item0.maturity_day);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.put_or_call) {
        auto r = eh0.set_int(201, *item0.put_or_call);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.strike_price) {
        auto r = eh0.set_decimal(202, *item0.strike_price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.opt_attribute) {
        auto r = eh0.set_char(206, *item0.opt_attribute);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.contract_multiplier) {
        auto r = eh0.set_decimal(231, *item0.contract_multiplier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.coupon_rate) {
        auto r = eh0.set_decimal(223, *item0.coupon_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.security_exchange) {
        auto r = eh0.set_string(207, *item0.security_exchange);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.issuer) {
        auto r = eh0.set_string(106, *item0.issuer);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.encoded_issuer) {
        auto r_len = eh0.set_int(348, static_cast<::std::int64_t>(item0.encoded_issuer->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = eh0.set_string(349, *item0.encoded_issuer);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (item0.security_desc) {
        auto r = eh0.set_string(107, *item0.security_desc);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.encoded_security_desc) {
        auto r_len = eh0.set_int(350, static_cast<::std::int64_t>(item0.encoded_security_desc->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = eh0.set_string(351, *item0.encoded_security_desc);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (item0.prev_close_px) {
        auto r = eh0.set_decimal(140, *item0.prev_close_px);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.side) {
        auto r = eh0.set_char(54, *item0.side);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.side_value_ind) {
        auto r = eh0.set_int(401, *item0.side_value_ind);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.locate_reqd) {
        auto r = eh0.set_char(114, (*item0.locate_reqd) ? 'Y' : 'N');
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.transact_time) {
        auto r = eh0.set_string(60, *item0.transact_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.order_qty) {
        auto r = eh0.set_decimal(38, *item0.order_qty);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.cash_order_qty) {
        auto r = eh0.set_decimal(152, *item0.cash_order_qty);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.ord_type) {
        auto r = eh0.set_char(40, *item0.ord_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.price) {
        auto r = eh0.set_decimal(44, *item0.price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.stop_px) {
        auto r = eh0.set_decimal(99, *item0.stop_px);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.currency) {
        auto r = eh0.set_string(15, *item0.currency);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.compliance_id) {
        auto r = eh0.set_string(376, *item0.compliance_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.solicited_flag) {
        auto r = eh0.set_char(377, (*item0.solicited_flag) ? 'Y' : 'N');
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.io_iid) {
        auto r = eh0.set_string(23, *item0.io_iid);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.quote_id) {
        auto r = eh0.set_string(117, *item0.quote_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.time_in_force) {
        auto r = eh0.set_char(59, *item0.time_in_force);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.effective_time) {
        auto r = eh0.set_string(168, *item0.effective_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.expire_date) {
        auto r = eh0.set_string(432, *item0.expire_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.expire_time) {
        auto r = eh0.set_string(126, *item0.expire_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.gt_booking_inst) {
        auto r = eh0.set_int(427, *item0.gt_booking_inst);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.commission) {
        auto r = eh0.set_decimal(12, *item0.commission);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.comm_type) {
        auto r = eh0.set_char(13, *item0.comm_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.rule80_a) {
        auto r = eh0.set_char(47, *item0.rule80_a);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.forex_req) {
        auto r = eh0.set_char(121, (*item0.forex_req) ? 'Y' : 'N');
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.settl_currency) {
        auto r = eh0.set_string(120, *item0.settl_currency);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.text) {
        auto r = eh0.set_string(58, *item0.text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.encoded_text) {
        auto r_len = eh0.set_int(354, static_cast<::std::int64_t>(item0.encoded_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = eh0.set_string(355, *item0.encoded_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (item0.fut_sett_date2) {
        auto r = eh0.set_string(193, *item0.fut_sett_date2);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.order_qty2) {
        auto r = eh0.set_decimal(192, *item0.order_qty2);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.open_close) {
        auto r = eh0.set_char(77, *item0.open_close);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.covered_or_uncovered) {
        auto r = eh0.set_int(203, *item0.covered_or_uncovered);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.customer_or_firm) {
        auto r = eh0.set_int(204, *item0.customer_or_firm);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.max_show) {
        auto r = eh0.set_decimal(210, *item0.max_show);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.peg_difference) {
        auto r = eh0.set_decimal(211, *item0.peg_difference);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.discretion_inst) {
        auto r = eh0.set_char(388, *item0.discretion_inst);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.discretion_offset) {
        auto r = eh0.set_decimal(389, *item0.discretion_offset);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.clearing_firm) {
        auto r = eh0.set_string(439, *item0.clearing_firm);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.clearing_account) {
        auto r = eh0.set_string(440, *item0.clearing_account);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge0 = bb.group_end(*gh0);
        if (!ge0) return ::std::unexpected(ge0.error());
    }
    if (args.encoded_list_exec_inst) {
        auto r_len = bb.field(352, static_cast<::std::int64_t>(args.encoded_list_exec_inst->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(353, *args.encoded_list_exec_inst);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.bid_id) {
        auto r = bb.field(390, *args.bid_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.client_bid_id) {
        auto r = bb.field(391, *args.client_bid_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.bid_type) {
        auto r = bb.field(394, *args.bid_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.prog_rpt_reqs) {
        auto r = bb.field(414, *args.prog_rpt_reqs);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.prog_period_interval) {
        auto r = bb.field(415, *args.prog_period_interval);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.list_exec_inst_type) {
        auto r = bb.field(433, *args.list_exec_inst_type);
        if (!r) return ::std::unexpected(r.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::v42
