// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v42/messages/OrderCancelRequest.builder.cpp -- external-linkage build_ definition (data-model.md Entity 4), compiled only into fixpp_builders_<ver>; no validator symbol (SC-003).
#include "OrderCancelRequest.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::v42 {

::fixpp::core::expected_t<::std::span<::std::byte>> build_OrderCancelRequest(::std::span<::std::byte> out, OrderCancelRequestArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"F"};
    if (args.account) {
        auto r = bb.field(1, *args.account);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.cl_ord_id) {
        auto r = bb.field(11, *args.cl_ord_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.id_source) {
        auto r = bb.field(22, *args.id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.order_id) {
        auto r = bb.field(37, *args.order_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.order_qty) {
        auto r = bb.field(38, *args.order_qty);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.orig_cl_ord_id) {
        auto r = bb.field(41, *args.orig_cl_ord_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_id) {
        auto r = bb.field(48, *args.security_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.side) {
        auto r = bb.field(54, *args.side);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.symbol) {
        auto r = bb.field(55, *args.symbol);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.text) {
        auto r = bb.field(58, *args.text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.transact_time) {
        auto r = bb.field(60, *args.transact_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.symbol_sfx) {
        auto r = bb.field(65, *args.symbol_sfx);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.list_id) {
        auto r = bb.field(66, *args.list_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.exec_broker) {
        auto r = bb.field(76, *args.exec_broker);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.issuer) {
        auto r = bb.field(106, *args.issuer);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_desc) {
        auto r = bb.field(107, *args.security_desc);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.client_id) {
        auto r = bb.field(109, *args.client_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.cash_order_qty) {
        auto r = bb.field(152, *args.cash_order_qty);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_type) {
        auto r = bb.field(167, *args.security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.maturity_month_year) {
        auto r = bb.field(200, *args.maturity_month_year);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.put_or_call) {
        auto r = bb.field(201, *args.put_or_call);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.strike_price) {
        auto r = bb.field(202, *args.strike_price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.maturity_day) {
        auto r = bb.field(205, *args.maturity_day);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.opt_attribute) {
        auto r = bb.field(206, *args.opt_attribute);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_exchange) {
        auto r = bb.field(207, *args.security_exchange);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.coupon_rate) {
        auto r = bb.field(223, *args.coupon_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.contract_multiplier) {
        auto r = bb.field(231, *args.contract_multiplier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_issuer) {
        auto r_len = bb.field(348, static_cast<::std::int64_t>(args.encoded_issuer->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(349, *args.encoded_issuer);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.encoded_security_desc) {
        auto r_len = bb.field(350, static_cast<::std::int64_t>(args.encoded_security_desc->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(351, *args.encoded_security_desc);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.encoded_text) {
        auto r_len = bb.field(354, static_cast<::std::int64_t>(args.encoded_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(355, *args.encoded_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.compliance_id) {
        auto r = bb.field(376, *args.compliance_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.solicited_flag) {
        auto r = bb.field(377, (*args.solicited_flag) ? 'Y' : 'N');
        if (!r) return ::std::unexpected(r.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::v42
