// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v42/messages/SecurityDefinition.builder.inl -- inline build_ body (data-model.md Entity 3); no validator symbol (SC-003).
#pragma once
#include "SecurityDefinition.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::v42 {

inline ::fixpp::core::expected_t<::std::span<::std::byte>> build_SecurityDefinition(::std::span<::std::byte> out, SecurityDefinitionArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"d"};
    if (args.currency) {
        auto r = bb.field(15, *args.currency);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.id_source) {
        auto r = bb.field(22, *args.id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_id) {
        auto r = bb.field(48, *args.security_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.symbol) {
        auto r = bb.field(55, *args.symbol);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.text) {
        auto r = bb.field(58, *args.text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.symbol_sfx) {
        auto r = bb.field(65, *args.symbol_sfx);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.issuer) {
        auto r = bb.field(106, *args.issuer);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_desc) {
        auto r = bb.field(107, *args.security_desc);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.related_sym) {
        auto gh0 = bb.group_begin(146, 311);
        if (!gh0) return ::std::unexpected(gh0.error());
        for (auto const& item0 : *args.related_sym) {
            auto en0 = gh0->add_entry();
            if (!en0) return ::std::unexpected(en0.error());
            auto& eh0 = *en0;
    if (item0.underlying_symbol) {
        auto r = eh0.set_string(311, *item0.underlying_symbol);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.underlying_symbol_sfx) {
        auto r = eh0.set_string(312, *item0.underlying_symbol_sfx);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.underlying_security_id) {
        auto r = eh0.set_string(309, *item0.underlying_security_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.underlying_id_source) {
        auto r = eh0.set_string(305, *item0.underlying_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.underlying_security_type) {
        auto r = eh0.set_string(310, *item0.underlying_security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.underlying_maturity_month_year) {
        auto r = eh0.set_string(313, *item0.underlying_maturity_month_year);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.underlying_maturity_day) {
        auto r = eh0.set_int(314, *item0.underlying_maturity_day);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.underlying_put_or_call) {
        auto r = eh0.set_int(315, *item0.underlying_put_or_call);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.underlying_strike_price) {
        auto r = eh0.set_decimal(316, *item0.underlying_strike_price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.underlying_opt_attribute) {
        auto r = eh0.set_char(317, *item0.underlying_opt_attribute);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.underlying_contract_multiplier) {
        auto r = eh0.set_decimal(436, *item0.underlying_contract_multiplier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.underlying_coupon_rate) {
        auto r = eh0.set_decimal(435, *item0.underlying_coupon_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.underlying_security_exchange) {
        auto r = eh0.set_string(308, *item0.underlying_security_exchange);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.underlying_issuer) {
        auto r = eh0.set_string(306, *item0.underlying_issuer);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.encoded_underlying_issuer) {
        auto r_len = eh0.set_int(362, static_cast<::std::int64_t>(item0.encoded_underlying_issuer->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = eh0.set_string(363, *item0.encoded_underlying_issuer);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (item0.underlying_security_desc) {
        auto r = eh0.set_string(307, *item0.underlying_security_desc);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.encoded_underlying_security_desc) {
        auto r_len = eh0.set_int(364, static_cast<::std::int64_t>(item0.encoded_underlying_security_desc->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = eh0.set_string(365, *item0.encoded_underlying_security_desc);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (item0.ratio_qty) {
        auto r = eh0.set_decimal(319, *item0.ratio_qty);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.side) {
        auto r = eh0.set_char(54, *item0.side);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.underlying_currency) {
        auto r = eh0.set_string(318, *item0.underlying_currency);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge0 = bb.group_end(*gh0);
        if (!ge0) return ::std::unexpected(ge0.error());
    }
    if (args.security_type) {
        auto r = bb.field(167, *args.security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.maturity_month_year) {
        auto r = bb.field(200, *args.maturity_month_year);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.put_or_call) {
        auto r = bb.field(201, *args.put_or_call);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.strike_price) {
        auto r = bb.field(202, *args.strike_price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.maturity_day) {
        auto r = bb.field(205, *args.maturity_day);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.opt_attribute) {
        auto r = bb.field(206, *args.opt_attribute);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_exchange) {
        auto r = bb.field(207, *args.security_exchange);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.coupon_rate) {
        auto r = bb.field(223, *args.coupon_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.contract_multiplier) {
        auto r = bb.field(231, *args.contract_multiplier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_req_id) {
        auto r = bb.field(320, *args.security_req_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_response_id) {
        auto r = bb.field(322, *args.security_response_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_response_type) {
        auto r = bb.field(323, *args.security_response_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.trading_session_id) {
        auto r = bb.field(336, *args.trading_session_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_issuer) {
        auto r_len = bb.field(348, static_cast<::std::int64_t>(args.encoded_issuer->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(349, *args.encoded_issuer);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.encoded_security_desc) {
        auto r_len = bb.field(350, static_cast<::std::int64_t>(args.encoded_security_desc->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(351, *args.encoded_security_desc);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.encoded_text) {
        auto r_len = bb.field(354, static_cast<::std::int64_t>(args.encoded_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(355, *args.encoded_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.total_num_securities) {
        auto r = bb.field(393, *args.total_num_securities);
        if (!r) return ::std::unexpected(r.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::v42
