// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v42/messages/SecurityStatus.validator.cpp -- external-linkage validate_ definition + this message's own top-level traits (data-model.md Entity 4), compiled only into fixpp_validators_<ver>.
#include "SecurityStatus.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool SecurityStatusArgs_required_55(::fixpp::v42::SecurityStatusArgs const& a) noexcept { return a.symbol.has_value(); }
template <> struct writer_traits<::fixpp::v42::SecurityStatusArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::v42::SecurityStatusArgs>, 1> required_checks = {{
        {55, &SecurityStatusArgs_required_55},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::v42::SecurityStatusArgs>, 0> group_checks = {};
};

}  // namespace fixpp::wire

namespace fixpp::v42 {

::fixpp::core::expected_t<void> validate_SecurityStatus(SecurityStatusArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::v42
