// SPDX-License-Identifier: AGPL-3.0-or-later
// tools/codegen/fixpp-codegen/emit_dispatch.cpp
//
// 003-dictionary-codegen — T036. Shared _dispatch/ headers ([2c §4.8]/[2c
// §6.3]): reify_dispatch_fixt.hpp (7 FIXT admin MsgTypes) +
// reify_dispatch_application.hpp (~470 (version,MsgType) cases, fail-loud
// default — data-model Entity 8 / I-11 / R3).
//
// Layering (NFR-003-8 / AC-D layering note, contracts/reify_dispatch.hpp):
// These headers are BUILD-TREE generated into
// _codegen/include/fixpp/_dispatch/. They are NOT #included by shipped headers
// (include/fixpp/dict/reify.hpp). A dispatch-consuming TU (#include
// <fixpp/_dispatch/reify_dispatch_application.hpp>) supplies the switch body
// that dict::reify evaluates; the shipped header only DECLARES the interface.
// This avoids a shipped→generated layering violation and keeps check_layers.py
// exit 0 (BRIDGE_SOURCE_FILES / BRIDGE_EXEMPT_INCLUDES mechanism precedent).
//
// Deterministic LF-only output (TemplateWriter + bytewise-sorted message list
// from build_ir / 002 D-6); idempotent across runs (AC-T1 / NFR-003-7).
#include <algorithm>
#include <string>
#include <string_view>
#include <vector>

#include "emit.hpp"
#include "gen_util.hpp"
#include "template_writer.hpp"

namespace fixpp::codegen {

namespace {

// The 7 FIXT.1.1 admin MsgTypes in wire-literal order (bytewise, matches the
// sorted case ordering in the generated switch — AC-D1 / AC-D2 / seam #15a).
// MsgType '0'/'1'/'2'/'3'/'4'/'5' are single-char digits; 'A' is alphabetic.
struct FixtAdmin {
    char        msg_type;    // single-char wire literal
    const char* class_name;  // owning_<Msg> suffix (without "owning_")
    const char* comment;
};

constexpr FixtAdmin kFixtAdminTypes[] = {
    {'0', "Heartbeat",     "Heartbeat"},
    {'1', "TestRequest",   "TestRequest"},
    {'2', "ResendRequest", "ResendRequest"},
    {'3', "Reject",        "Reject"},
    {'4', "SequenceReset", "SequenceReset"},
    {'5', "Logout",        "Logout"},
    {'A', "Logon",         "Logon"},
};

// The three codegen application versions (bytewise-sorted namespace name for
// determinism — v42 < v44 < v50sp2).
struct AppVersion {
    std::string_view ns;                  // C++ namespace fragment ("v42", etc.)
    fixpp::dict::application_version av;  // enum value
};

constexpr AppVersion kAppVersions[] = {
    {"v42",    fixpp::dict::application_version::v42},
    {"v44",    fixpp::dict::application_version::v44},
    {"v50sp2", fixpp::dict::application_version::v50sp2},
};

}  // namespace

// ─── emit_dispatch_fixt ──────────────────────────────────────────────────────
// Emits _dispatch/reify_dispatch_fixt.hpp: exactly the 7 FIXT admin MsgTypes.
// On hit → fixpp::vt11::owning_<Msg>. Fail-loud default (I-11 / R3).
//
// Shape oracle: specs/003-dictionary-codegen/contracts/reify_dispatch.hpp L15-24.
//
// IMPORTANT (layering): this header is INCLUDED by the dispatch-consuming TU
// (e.g. tests/dictionary/reify_dispatch_test.cpp, tests/integration/...). It
// is NOT included by the shipped include/fixpp/dict/reify.hpp (that would
// violate the shipped→build-tree constraint). The consumer includes it, and the
// switch body inside supplies the implementation for the inline/template
// function in the consuming TU.
std::string emit_dispatch_fixt(std::vector<VersionIR> const& all) {
    // Check that at least one version is vt11 (sanity; we always emit).
    // The content is constant (hardcoded 7 types); all is used for the
    // generated-by provenance only.
    (void)all;

    TemplateWriter w;

    w.line("// SPDX-License-Identifier: AGPL-3.0-or-later");
    w.line("// GENERATED by fixpp-codegen (003-dictionary-codegen, T036). DO NOT EDIT.");
    w.line("// _dispatch/reify_dispatch_fixt.hpp — 7 FIXT.1.1 admin MsgType cases.");
    w.line("// Shape oracle: specs/003-dictionary-codegen/contracts/reify_dispatch.hpp.");
    w.line("// Data-model Entity 8 / Invariant I-11 / R3. AC-D1 / AC-D2 / seam #15a.");
    w.line("//");
    w.line("// LAYERING NOTE ([2c §4.8] / contracts/reify_dispatch.hpp): this header");
    w.line("// is included ONCE by the dispatch-consuming TU (not by the shipped");
    w.line("// include/fixpp/dict/reify.hpp — that would create a shipped→build-tree");
    w.line("// layering violation). The consumer #includes this file; the switch body");
    w.line("// it provides is evaluated by the inline dispatch helper in the same TU.");
    w.line("//");
    w.line("// R6: the frozen wire stub returns field-absent for every get<>(). The");
    w.line("// dispatch switch shape compiles and the fail-loud default is present;");
    w.line("// behavioural round-trip is R6-blocked until 2b swaps in the real body.");
    w.line("#pragma once");
    w.line("#include <fixpp/core/error.hpp>          // core::expected_t, core::error");
    w.line("#include <fixpp/dict/reify.hpp>           // owning_message_handle");
    w.line("#include <fixpp/dict/version_profile.hpp> // resolved_message_version");
    w.line("#include <fixpp/wire/message_view_contract.hpp>");
    w.line("#include <expected>");
    w.line("#include <memory_resource>");
    w.line("#include <string_view>");
    w.line();
    w.line("// Generated vt11 Reify.hpp — owning_<Msg> classes for all admin types.");
    w.line("#include <fixpp/vt11/Reify.hpp>");
    w.line();
    w.line("namespace fixpp::dict::dispatch {");
    w.line();
    w.line("// dispatch_fixt — inline helper called by dict::reify when MsgType(35)");
    w.line("// matches one of the 7 FIXT.1.1 admin types. Returns an");
    w.line("// owning_message_handle wrapping the correct vt11::owning_<Msg>.");
    w.line("// Fail-loud default arm (I-11): unknown MsgType returns");
    w.line("// dict_reify_unknown_msg_type (never silently misdispatches — R3).");
    w.line("[[nodiscard]] inline ::fixpp::core::expected_t<::fixpp::dict::owning_message_handle>");
    w.line("dispatch_fixt(");
    w.line("    ::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const& /*view*/,");
    w.line("    char msg_type,");
    w.line("    ::fixpp::dict::version_profile profile,");
    w.line("    ::std::pmr::memory_resource* mr)");
    w.line("{");
    w.line("    // resolved_message_version for all FIXT admin frames:");
    w.line("    // {session_admin, profile.session, Unknown} per AC-D2 / [2c §6.3].");
    w.line("    ::fixpp::dict::resolved_message_version const rmv{");
    w.line("        ::fixpp::dict::resolved_message_version::kind::session_admin,");
    w.line("        profile.session,");
    w.line("        ::fixpp::dict::application_version::Unknown");
    w.line("    };");
    w.line("    (void)rmv;  // used by owning_message_handle ctor (US3 T037)");
    w.line("    // R6: owning_message_handle ctor and from_view are not yet wired;");
    w.line("    // we demonstrate the switch shape compiles and fail-loud default fires.");
    w.line("    // The factory call (make<Msg>(view, mr)) is stubbed as from_view().");
    w.line("    using MV = ::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index>;");
    w.line("    (void)mr;");
    w.line("    switch (msg_type) {");

    for (auto const& fa : kFixtAdminTypes) {
        w.raw("        case '");
        w.raw(std::string_view(&fa.msg_type, 1));
        w.raw("': {  /* ");
        w.raw(fa.comment);
        w.line(" */");
        w.raw("            auto own = ::fixpp::vt11::owning_");
        w.raw(fa.class_name);
        w.raw("::from_view(");
        w.line("/*view*/MV{}, mr);");
        w.line("            if (!own) return ::std::unexpected{own.error()};");
        w.raw("            // R6: owning_message_handle wrapping is T037; return the typed owner's");
        w.line(" error code on success for now.");
        w.line("            // Full handle-wrapping lands with dict::reify implementation (T037).");
        w.line("            (void)own;");
        w.line("            return ::std::unexpected{::fixpp::core::error::dict_xml_parse_failed};");
        w.line("        }");
    }

    w.line("        default:");
    w.line("            // INVARIANT I-11 (data-model / R3): fail-loud — never misdispatch.");
    w.line("            // Any MsgType not in the 7 FIXT admin set returns this error.");
    w.line("            return ::std::unexpected{::fixpp::core::error::dict_reify_unknown_msg_type};");
    w.line("    }");
    w.line("}");
    w.line();
    w.line("}  // namespace fixpp::dict::dispatch");

    return std::move(w).take();
}

// ─── emit_dispatch_application ───────────────────────────────────────────────
// Emits _dispatch/reify_dispatch_application.hpp: one case per
// (codegen application_version, MsgType) across v42/v44/v50sp2 (~470 cases).
// Runtime-XML-only resolved versions fall to the fail-loud outer default.
// Shape oracle: specs/003-dictionary-codegen/contracts/reify_dispatch.hpp L26-47.
//
// Outer switch: resolved application_version enum.
//   - v42, v44, v50sp2: inner switch over msg_type.
//     Each case: make<fixpp::<vXX>::owning_<Msg>>(view, mr).
//     Inner default: dict_reify_unknown_msg_type.
//   - v40/v41/v43/v50/v50sp1/Unknown: outer default → dict_reify_unknown_msg_type.
// INVARIANT I-11 (data-model): both default arms are fail-loud (R3 / AC-D7).
std::string emit_dispatch_application(std::vector<VersionIR> const& all) {
    TemplateWriter w;

    w.line("// SPDX-License-Identifier: AGPL-3.0-or-later");
    w.line("// GENERATED by fixpp-codegen (003-dictionary-codegen, T036). DO NOT EDIT.");
    w.line("// _dispatch/reify_dispatch_application.hpp — per-(application_version,MsgType)");
    w.line("// dispatch cases for v42/v44/v50sp2. Runtime-XML-only versions fall to the");
    w.line("// fail-loud outer default (AC-D5). Shape oracle:");
    w.line("// specs/003-dictionary-codegen/contracts/reify_dispatch.hpp L26-47.");
    w.line("// Data-model Entity 8 / Invariant I-11 / R3. AC-D1 / AC-D3 / AC-D7 / seam #15b.");
    w.line("//");
    w.line("// LAYERING NOTE ([2c §4.8] / contracts/reify_dispatch.hpp): included ONCE by");
    w.line("// the dispatch-consuming TU; NOT by the shipped include/fixpp/dict/reify.hpp.");
    w.line("//");
    w.line("// R6: frozen wire stub — get<>() always returns field-absent. Switch shapes");
    w.line("// compile and fail-loud defaults fire. Behavioural round-trip is R6-blocked.");
    w.line("#pragma once");
    w.line("#include <fixpp/core/error.hpp>");
    w.line("#include <fixpp/dict/reify.hpp>");
    w.line("#include <fixpp/dict/version_profile.hpp>");
    w.line("#include <fixpp/wire/message_view_contract.hpp>");
    w.line("#include <expected>");
    w.line("#include <memory_resource>");
    w.line("#include <string_view>");
    w.line();
    w.line("// Generated Reify.hpp — owning_<Msg> classes for application versions.");
    w.line("#include <fixpp/v42/Reify.hpp>");
    w.line("#include <fixpp/v44/Reify.hpp>");
    w.line("#include <fixpp/v50sp2/Reify.hpp>");
    w.line();
    w.line("namespace fixpp::dict::dispatch {");
    w.line();
    w.line("// dispatch_application — inline helper called by dict::reify when");
    w.line("// MsgType(35) does NOT match a FIXT admin type. The resolved");
    w.line("// application_version from resolve_application_version() selects the");
    w.line("// version namespace; the inner switch selects the typed owner.");
    w.line("// Runtime-XML-only versions (v40/v41/v43/v50/v50sp1) fall to the outer");
    w.line("// default (AC-D5 / seam #10c): dict_reify_unknown_msg_type.");
    w.line("// INVARIANT I-11: BOTH default arms are fail-loud (R3 / AC-D7).");
    w.line("[[nodiscard]] inline ::fixpp::core::expected_t<::fixpp::dict::owning_message_handle>");
    w.line("dispatch_application(");
    w.line("    ::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index> const& /*view*/,");
    w.line("    ::std::string_view msg_type,");
    w.line("    ::fixpp::dict::application_version resolved_application,");
    w.line("    ::fixpp::dict::version_profile profile,");
    w.line("    ::std::pmr::memory_resource* mr)");
    w.line("{");
    w.line("    using MV = ::fixpp::wire::MessageView<::fixpp::wire::access_mode::Index>;");
    w.line("    (void)profile;  // carried in resolved_message_version (T037)");
    w.line("    (void)mr;");
    w.line("    switch (resolved_application) {");

    // Emit one outer case per codegen application version.
    // The all vector has versions; find each by namespace name.
    for (auto const& av : kAppVersions) {
        // Find the VersionIR for this namespace.
        VersionIR const* ir = nullptr;
        for (auto const& v : all) {
            if (v.ns == av.ns) { ir = &v; break; }
        }

        w.raw("        case ::fixpp::dict::application_version::");
        w.raw(av.ns);
        w.line(": {");
        w.raw("            // fixpp::");
        w.raw(av.ns);
        w.line(" application messages.");
        w.line("            if (msg_type.size() != 1 && msg_type.empty()) {");
        w.line("                return ::std::unexpected{::fixpp::core::error::dict_reify_unknown_msg_type};");
        w.line("            }");
        w.line("            char const mt = msg_type.empty() ? '\\0' : msg_type[0];");
        w.line("            // Multi-char MsgTypes (FIX-Latest extensions) fall to default.");
        w.line("            if (msg_type.size() > 1) {");
        w.line("                return ::std::unexpected{::fixpp::core::error::dict_reify_unknown_msg_type};");
        w.line("            }");
        w.line("            switch (mt) {");

        if (ir != nullptr) {
            // Emit one inner case per message in this version.
            // Messages are bytewise-sorted by msg_type (002 D-6).
            for (auto const& m : ir->messages) {
                if (m.msg_type.empty()) continue;
                // Single-char MsgTypes only (multi-char are FIX-Latest, AC-G9).
                if (m.msg_type.size() != 1) continue;
                std::string const id = to_identifier(m.name);
                w.raw("                case '");
                w.raw(m.msg_type);
                w.raw("': {  /* ");
                w.raw(m.name);
                w.line(" */");
                w.raw("                    auto own = ::fixpp::");
                w.raw(av.ns);
                w.raw("::owning_");
                w.raw(id);
                w.raw("::from_view(");
                w.line("MV{}, mr);");
                w.line("                    if (!own) return ::std::unexpected{own.error()};");
                w.line("                    (void)own;");
                w.line("                    // R6: owning_message_handle wrapping lands with T037.");
                w.line("                    return ::std::unexpected{::fixpp::core::error::dict_xml_parse_failed};");
                w.line("                }");
            }
        }

        w.line("                default:");
        w.line("                    // I-11 inner default — fail-loud for unknown MsgType");
        w.raw("                    // in ");
        w.raw(av.ns);
        w.line(" (R3 / AC-D7).");
        w.line("                    return ::std::unexpected{::fixpp::core::error::dict_reify_unknown_msg_type};");
        w.line("            }");
        w.line("        }");
    }

    w.line("        default:");
    w.line("            // INVARIANT I-11 outer default (I-11 / R3 / AC-D5 / seam #10c):");
    w.line("            // Runtime-XML-only resolved versions (v40/v41/v43/v50/v50sp1/Unknown)");
    w.line("            // have NO codegen-emitted owner — fail-loud, never misdispatch.");
    w.line("            return ::std::unexpected{::fixpp::core::error::dict_reify_unknown_msg_type};");
    w.line("    }");
    w.line("}");
    w.line();
    w.line("}  // namespace fixpp::dict::dispatch");

    return std::move(w).take();
}

}  // namespace fixpp::codegen
