// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v44/messages/BidRequest.validator.cpp -- external-linkage validate_ definition + this message's own top-level traits (data-model.md Entity 4), compiled only into fixpp_validators_<ver>.
#include "BidRequest.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool BidRequestArgs_required_374(::fixpp::v44::BidRequestArgs const& a) noexcept { return a.bid_request_trans_type.has_value(); }
inline bool BidRequestArgs_required_391(::fixpp::v44::BidRequestArgs const& a) noexcept { return a.client_bid_id.has_value(); }
inline bool BidRequestArgs_required_393(::fixpp::v44::BidRequestArgs const& a) noexcept { return a.tot_no_related_sym.has_value(); }
inline bool BidRequestArgs_required_394(::fixpp::v44::BidRequestArgs const& a) noexcept { return a.bid_type.has_value(); }
inline bool BidRequestArgs_required_418(::fixpp::v44::BidRequestArgs const& a) noexcept { return a.bid_trade_type.has_value(); }
inline bool BidRequestArgs_required_419(::fixpp::v44::BidRequestArgs const& a) noexcept { return a.basis_px_type.has_value(); }
inline ::std::optional<::std::size_t> BidRequestArgs_count_bid_descriptors(::fixpp::v44::BidRequestArgs const& a) noexcept { if (!a.bid_descriptors) { return ::std::nullopt; } return a.bid_descriptors->size(); }
inline ::fixpp::core::expected_t<void> BidRequestArgs_validate_entry_bid_descriptors(::fixpp::v44::BidRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.bid_descriptors)[i]); }
inline ::std::optional<::std::size_t> BidRequestArgs_count_bid_components(::fixpp::v44::BidRequestArgs const& a) noexcept { if (!a.bid_components) { return ::std::nullopt; } return a.bid_components->size(); }
inline ::fixpp::core::expected_t<void> BidRequestArgs_validate_entry_bid_components(::fixpp::v44::BidRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.bid_components)[i]); }
template <> struct writer_traits<::fixpp::v44::BidRequestArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::v44::BidRequestArgs>, 6> required_checks = {{
        {374, &BidRequestArgs_required_374},
        {391, &BidRequestArgs_required_391},
        {393, &BidRequestArgs_required_393},
        {394, &BidRequestArgs_required_394},
        {418, &BidRequestArgs_required_418},
        {419, &BidRequestArgs_required_419},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::v44::BidRequestArgs>, 2> group_checks = {{
        {false, &BidRequestArgs_count_bid_descriptors, &BidRequestArgs_validate_entry_bid_descriptors},
        {false, &BidRequestArgs_count_bid_components, &BidRequestArgs_validate_entry_bid_components},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::v44 {

::fixpp::core::expected_t<void> validate_BidRequest(BidRequestArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::v44
