// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v44/messages/CollateralInquiry.builder.inl -- inline build_ body (data-model.md Entity 3); no validator symbol (SC-003).
#pragma once
#include "CollateralInquiry.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::v44 {

inline ::fixpp::core::expected_t<::std::span<::std::byte>> build_CollateralInquiry(::std::span<::std::byte> out, CollateralInquiryArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"BB"};
    if (args.account) {
        auto r = bb.field(1, *args.account);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.cl_ord_id) {
        auto r = bb.field(11, *args.cl_ord_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.currency) {
        auto r = bb.field(15, *args.currency);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_id_source) {
        auto r = bb.field(22, *args.security_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.order_id) {
        auto r = bb.field(37, *args.order_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.price) {
        auto r = bb.field(44, *args.price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_id) {
        auto r = bb.field(48, *args.security_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.quantity) {
        auto r = bb.field(53, *args.quantity);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.side) {
        auto r = bb.field(54, *args.side);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.symbol) {
        auto r = bb.field(55, *args.symbol);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.text) {
        auto r = bb.field(58, *args.text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.settl_date) {
        auto r = bb.field(64, *args.settl_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.symbol_sfx) {
        auto r = bb.field(65, *args.symbol_sfx);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.dlvy_inst) {
        auto gh0 = bb.group_begin(85, 165);
        if (!gh0) return ::std::unexpected(gh0.error());
        for (auto const& item0 : *args.dlvy_inst) {
            auto en0 = gh0->add_entry();
            if (!en0) return ::std::unexpected(en0.error());
            auto& eh0 = *en0;
    if (item0.settl_inst_source) {
        auto r = eh0.set_char(165, *item0.settl_inst_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.dlvy_inst_type) {
        auto r = eh0.set_char(787, *item0.dlvy_inst_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.settl_party_i_ds) {
        auto gh1 = eh0.group_begin(781, 782);
        if (!gh1) return ::std::unexpected(gh1.error());
        for (auto const& item1 : *item0.settl_party_i_ds) {
            auto en1 = gh1->add_entry();
            if (!en1) return ::std::unexpected(en1.error());
            auto& eh1 = *en1;
    if (item1.settl_party_id) {
        auto r = eh1.set_string(782, *item1.settl_party_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item1.settl_party_id_source) {
        auto r = eh1.set_char(783, *item1.settl_party_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item1.settl_party_role) {
        auto r = eh1.set_int(784, *item1.settl_party_role);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item1.settl_party_sub_i_ds) {
        auto gh2 = eh1.group_begin(801, 785);
        if (!gh2) return ::std::unexpected(gh2.error());
        for (auto const& item2 : *item1.settl_party_sub_i_ds) {
            auto en2 = gh2->add_entry();
            if (!en2) return ::std::unexpected(en2.error());
            auto& eh2 = *en2;
    if (item2.settl_party_sub_id) {
        auto r = eh2.set_string(785, *item2.settl_party_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item2.settl_party_sub_id_type) {
        auto r = eh2.set_int(786, *item2.settl_party_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge2 = bb.group_end(*gh2);
        if (!ge2) return ::std::unexpected(ge2.error());
    }
        }
        auto ge1 = bb.group_end(*gh1);
        if (!ge1) return ::std::unexpected(ge1.error());
    }
        }
        auto ge0 = bb.group_end(*gh0);
        if (!ge0) return ::std::unexpected(ge0.error());
    }
    if (args.issuer) {
        auto r = bb.field(106, *args.issuer);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_desc) {
        auto r = bb.field(107, *args.security_desc);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.execs) {
        auto gh3 = bb.group_begin(124, 17);
        if (!gh3) return ::std::unexpected(gh3.error());
        for (auto const& item3 : *args.execs) {
            auto en3 = gh3->add_entry();
            if (!en3) return ::std::unexpected(en3.error());
            auto& eh3 = *en3;
    if (item3.exec_id) {
        auto r = eh3.set_string(17, *item3.exec_id);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge3 = bb.group_end(*gh3);
        if (!ge3) return ::std::unexpected(ge3.error());
    }
    if (args.accrued_interest_amt) {
        auto r = bb.field(159, *args.accrued_interest_amt);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_type) {
        auto r = bb.field(167, *args.security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.stand_inst_db_type) {
        auto r = bb.field(169, *args.stand_inst_db_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.stand_inst_db_name) {
        auto r = bb.field(170, *args.stand_inst_db_name);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.stand_inst_db_id) {
        auto r = bb.field(171, *args.stand_inst_db_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.settl_delivery_type) {
        auto r = bb.field(172, *args.settl_delivery_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.secondary_order_id) {
        auto r = bb.field(198, *args.secondary_order_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.maturity_month_year) {
        auto r = bb.field(200, *args.maturity_month_year);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.put_or_call) {
        auto r = bb.field(201, *args.put_or_call);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.strike_price) {
        auto r = bb.field(202, *args.strike_price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.opt_attribute) {
        auto r = bb.field(206, *args.opt_attribute);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_exchange) {
        auto r = bb.field(207, *args.security_exchange);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.spread) {
        auto r = bb.field(218, *args.spread);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.benchmark_curve_currency) {
        auto r = bb.field(220, *args.benchmark_curve_currency);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.benchmark_curve_name) {
        auto r = bb.field(221, *args.benchmark_curve_name);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.benchmark_curve_point) {
        auto r = bb.field(222, *args.benchmark_curve_point);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.coupon_rate) {
        auto r = bb.field(223, *args.coupon_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.coupon_payment_date) {
        auto r = bb.field(224, *args.coupon_payment_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.issue_date) {
        auto r = bb.field(225, *args.issue_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.repurchase_term) {
        auto r = bb.field(226, *args.repurchase_term);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.repurchase_rate) {
        auto r = bb.field(227, *args.repurchase_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.factor) {
        auto r = bb.field(228, *args.factor);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.contract_multiplier) {
        auto r = bb.field(231, *args.contract_multiplier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.stipulations) {
        auto gh4 = bb.group_begin(232, 233);
        if (!gh4) return ::std::unexpected(gh4.error());
        for (auto const& item4 : *args.stipulations) {
            auto en4 = gh4->add_entry();
            if (!en4) return ::std::unexpected(en4.error());
            auto& eh4 = *en4;
    if (item4.stipulation_type) {
        auto r = eh4.set_string(233, *item4.stipulation_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.stipulation_value) {
        auto r = eh4.set_string(234, *item4.stipulation_value);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge4 = bb.group_end(*gh4);
        if (!ge4) return ::std::unexpected(ge4.error());
    }
    if (args.repo_collateral_security_type) {
        auto r = bb.field(239, *args.repo_collateral_security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.redemption_date) {
        auto r = bb.field(240, *args.redemption_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.credit_rating) {
        auto r = bb.field(255, *args.credit_rating);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.subscription_request_type) {
        auto r = bb.field(263, *args.subscription_request_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.trading_session_id) {
        auto r = bb.field(336, *args.trading_session_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_issuer) {
        auto r_len = bb.field(348, static_cast<::std::int64_t>(args.encoded_issuer->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(349, *args.encoded_issuer);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.encoded_security_desc) {
        auto r_len = bb.field(350, static_cast<::std::int64_t>(args.encoded_security_desc->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(351, *args.encoded_security_desc);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.encoded_text) {
        auto r_len = bb.field(354, static_cast<::std::int64_t>(args.encoded_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(355, *args.encoded_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.price_type) {
        auto r = bb.field(423, *args.price_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.party_i_ds) {
        auto gh5 = bb.group_begin(453, 448);
        if (!gh5) return ::std::unexpected(gh5.error());
        for (auto const& item5 : *args.party_i_ds) {
            auto en5 = gh5->add_entry();
            if (!en5) return ::std::unexpected(en5.error());
            auto& eh5 = *en5;
    if (item5.party_id) {
        auto r = eh5.set_string(448, *item5.party_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item5.party_id_source) {
        auto r = eh5.set_char(447, *item5.party_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item5.party_role) {
        auto r = eh5.set_int(452, *item5.party_role);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item5.party_sub_i_ds) {
        auto gh6 = eh5.group_begin(802, 523);
        if (!gh6) return ::std::unexpected(gh6.error());
        for (auto const& item6 : *item5.party_sub_i_ds) {
            auto en6 = gh6->add_entry();
            if (!en6) return ::std::unexpected(en6.error());
            auto& eh6 = *en6;
    if (item6.party_sub_id) {
        auto r = eh6.set_string(523, *item6.party_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item6.party_sub_id_type) {
        auto r = eh6.set_int(803, *item6.party_sub_id_type);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge6 = bb.group_end(*gh6);
        if (!ge6) return ::std::unexpected(ge6.error());
    }
        }
        auto ge5 = bb.group_end(*gh5);
        if (!ge5) return ::std::unexpected(ge5.error());
    }
    if (args.security_alt_id) {
        auto gh7 = bb.group_begin(454, 455);
        if (!gh7) return ::std::unexpected(gh7.error());
        for (auto const& item7 : *args.security_alt_id) {
            auto en7 = gh7->add_entry();
            if (!en7) return ::std::unexpected(en7.error());
            auto& eh7 = *en7;
    if (item7.security_alt_id) {
        auto r = eh7.set_string(455, *item7.security_alt_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item7.security_alt_id_source) {
        auto r = eh7.set_string(456, *item7.security_alt_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge7 = bb.group_end(*gh7);
        if (!ge7) return ::std::unexpected(ge7.error());
    }
    if (args.product) {
        auto r = bb.field(460, *args.product);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.cfi_code) {
        auto r = bb.field(461, *args.cfi_code);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.country_of_issue) {
        auto r = bb.field(470, *args.country_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.state_or_province_of_issue) {
        auto r = bb.field(471, *args.state_or_province_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.locale_of_issue) {
        auto r = bb.field(472, *args.locale_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.secondary_cl_ord_id) {
        auto r = bb.field(526, *args.secondary_cl_ord_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.maturity_date) {
        auto r = bb.field(541, *args.maturity_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.instr_registry) {
        auto r = bb.field(543, *args.instr_registry);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.legs) {
        auto gh8 = bb.group_begin(555, 600);
        if (!gh8) return ::std::unexpected(gh8.error());
        for (auto const& item8 : *args.legs) {
            auto en8 = gh8->add_entry();
            if (!en8) return ::std::unexpected(en8.error());
            auto& eh8 = *en8;
    if (item8.leg_symbol) {
        auto r = eh8.set_string(600, *item8.leg_symbol);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_symbol_sfx) {
        auto r = eh8.set_string(601, *item8.leg_symbol_sfx);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_security_id) {
        auto r = eh8.set_string(602, *item8.leg_security_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_security_id_source) {
        auto r = eh8.set_string(603, *item8.leg_security_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_security_alt_id) {
        auto gh9 = eh8.group_begin(604, 605);
        if (!gh9) return ::std::unexpected(gh9.error());
        for (auto const& item9 : *item8.leg_security_alt_id) {
            auto en9 = gh9->add_entry();
            if (!en9) return ::std::unexpected(en9.error());
            auto& eh9 = *en9;
    if (item9.leg_security_alt_id) {
        auto r = eh9.set_string(605, *item9.leg_security_alt_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item9.leg_security_alt_id_source) {
        auto r = eh9.set_string(606, *item9.leg_security_alt_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge9 = bb.group_end(*gh9);
        if (!ge9) return ::std::unexpected(ge9.error());
    }
    if (item8.leg_product) {
        auto r = eh8.set_int(607, *item8.leg_product);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_cfi_code) {
        auto r = eh8.set_string(608, *item8.leg_cfi_code);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_security_type) {
        auto r = eh8.set_string(609, *item8.leg_security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_security_sub_type) {
        auto r = eh8.set_string(764, *item8.leg_security_sub_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_maturity_month_year) {
        auto r = eh8.set_string(610, *item8.leg_maturity_month_year);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_maturity_date) {
        auto r = eh8.set_string(611, *item8.leg_maturity_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_coupon_payment_date) {
        auto r = eh8.set_string(248, *item8.leg_coupon_payment_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_issue_date) {
        auto r = eh8.set_string(249, *item8.leg_issue_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_repo_collateral_security_type) {
        auto r = eh8.set_string(250, *item8.leg_repo_collateral_security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_repurchase_term) {
        auto r = eh8.set_int(251, *item8.leg_repurchase_term);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_repurchase_rate) {
        auto r = eh8.set_decimal(252, *item8.leg_repurchase_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_factor) {
        auto r = eh8.set_decimal(253, *item8.leg_factor);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_credit_rating) {
        auto r = eh8.set_string(257, *item8.leg_credit_rating);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_instr_registry) {
        auto r = eh8.set_string(599, *item8.leg_instr_registry);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_country_of_issue) {
        auto r = eh8.set_string(596, *item8.leg_country_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_state_or_province_of_issue) {
        auto r = eh8.set_string(597, *item8.leg_state_or_province_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_locale_of_issue) {
        auto r = eh8.set_string(598, *item8.leg_locale_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_redemption_date) {
        auto r = eh8.set_string(254, *item8.leg_redemption_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_strike_price) {
        auto r = eh8.set_decimal(612, *item8.leg_strike_price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_strike_currency) {
        auto r = eh8.set_string(942, *item8.leg_strike_currency);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_opt_attribute) {
        auto r = eh8.set_char(613, *item8.leg_opt_attribute);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_contract_multiplier) {
        auto r = eh8.set_decimal(614, *item8.leg_contract_multiplier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_coupon_rate) {
        auto r = eh8.set_decimal(615, *item8.leg_coupon_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_security_exchange) {
        auto r = eh8.set_string(616, *item8.leg_security_exchange);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_issuer) {
        auto r = eh8.set_string(617, *item8.leg_issuer);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.encoded_leg_issuer) {
        auto r_len = eh8.set_int(618, static_cast<::std::int64_t>(item8.encoded_leg_issuer->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = eh8.set_string(619, *item8.encoded_leg_issuer);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (item8.leg_security_desc) {
        auto r = eh8.set_string(620, *item8.leg_security_desc);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.encoded_leg_security_desc) {
        auto r_len = eh8.set_int(621, static_cast<::std::int64_t>(item8.encoded_leg_security_desc->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = eh8.set_string(622, *item8.encoded_leg_security_desc);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (item8.leg_ratio_qty) {
        auto r = eh8.set_decimal(623, *item8.leg_ratio_qty);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_side) {
        auto r = eh8.set_char(624, *item8.leg_side);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_currency) {
        auto r = eh8.set_string(556, *item8.leg_currency);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_pool) {
        auto r = eh8.set_string(740, *item8.leg_pool);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_dated_date) {
        auto r = eh8.set_string(739, *item8.leg_dated_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_contract_settl_month) {
        auto r = eh8.set_string(955, *item8.leg_contract_settl_month);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item8.leg_interest_accrual_date) {
        auto r = eh8.set_string(956, *item8.leg_interest_accrual_date);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge8 = bb.group_end(*gh8);
        if (!ge8) return ::std::unexpected(ge8.error());
    }
    if (args.account_type) {
        auto r = bb.field(581, *args.account_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.trading_session_sub_id) {
        auto r = bb.field(625, *args.trading_session_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.benchmark_price) {
        auto r = bb.field(662, *args.benchmark_price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.benchmark_price_type) {
        auto r = bb.field(663, *args.benchmark_price_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.contract_settl_month) {
        auto r = bb.field(667, *args.contract_settl_month);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.pool) {
        auto r = bb.field(691, *args.pool);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.benchmark_security_id) {
        auto r = bb.field(699, *args.benchmark_security_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlyings) {
        auto gh10 = bb.group_begin(711, 311);
        if (!gh10) return ::std::unexpected(gh10.error());
        for (auto const& item10 : *args.underlyings) {
            auto en10 = gh10->add_entry();
            if (!en10) return ::std::unexpected(en10.error());
            auto& eh10 = *en10;
    if (item10.underlying_symbol) {
        auto r = eh10.set_string(311, *item10.underlying_symbol);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_symbol_sfx) {
        auto r = eh10.set_string(312, *item10.underlying_symbol_sfx);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_security_id) {
        auto r = eh10.set_string(309, *item10.underlying_security_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_security_id_source) {
        auto r = eh10.set_string(305, *item10.underlying_security_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_security_alt_id) {
        auto gh11 = eh10.group_begin(457, 458);
        if (!gh11) return ::std::unexpected(gh11.error());
        for (auto const& item11 : *item10.underlying_security_alt_id) {
            auto en11 = gh11->add_entry();
            if (!en11) return ::std::unexpected(en11.error());
            auto& eh11 = *en11;
    if (item11.underlying_security_alt_id) {
        auto r = eh11.set_string(458, *item11.underlying_security_alt_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item11.underlying_security_alt_id_source) {
        auto r = eh11.set_string(459, *item11.underlying_security_alt_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge11 = bb.group_end(*gh11);
        if (!ge11) return ::std::unexpected(ge11.error());
    }
    if (item10.underlying_product) {
        auto r = eh10.set_int(462, *item10.underlying_product);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_cfi_code) {
        auto r = eh10.set_string(463, *item10.underlying_cfi_code);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_security_type) {
        auto r = eh10.set_string(310, *item10.underlying_security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_security_sub_type) {
        auto r = eh10.set_string(763, *item10.underlying_security_sub_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_maturity_month_year) {
        auto r = eh10.set_string(313, *item10.underlying_maturity_month_year);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_maturity_date) {
        auto r = eh10.set_string(542, *item10.underlying_maturity_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_put_or_call) {
        auto r = eh10.set_int(315, *item10.underlying_put_or_call);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_coupon_payment_date) {
        auto r = eh10.set_string(241, *item10.underlying_coupon_payment_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_issue_date) {
        auto r = eh10.set_string(242, *item10.underlying_issue_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_repo_collateral_security_type) {
        auto r = eh10.set_string(243, *item10.underlying_repo_collateral_security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_repurchase_term) {
        auto r = eh10.set_int(244, *item10.underlying_repurchase_term);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_repurchase_rate) {
        auto r = eh10.set_decimal(245, *item10.underlying_repurchase_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_factor) {
        auto r = eh10.set_decimal(246, *item10.underlying_factor);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_credit_rating) {
        auto r = eh10.set_string(256, *item10.underlying_credit_rating);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_instr_registry) {
        auto r = eh10.set_string(595, *item10.underlying_instr_registry);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_country_of_issue) {
        auto r = eh10.set_string(592, *item10.underlying_country_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_state_or_province_of_issue) {
        auto r = eh10.set_string(593, *item10.underlying_state_or_province_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_locale_of_issue) {
        auto r = eh10.set_string(594, *item10.underlying_locale_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_redemption_date) {
        auto r = eh10.set_string(247, *item10.underlying_redemption_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_strike_price) {
        auto r = eh10.set_decimal(316, *item10.underlying_strike_price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_strike_currency) {
        auto r = eh10.set_string(941, *item10.underlying_strike_currency);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_opt_attribute) {
        auto r = eh10.set_char(317, *item10.underlying_opt_attribute);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_contract_multiplier) {
        auto r = eh10.set_decimal(436, *item10.underlying_contract_multiplier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_coupon_rate) {
        auto r = eh10.set_decimal(435, *item10.underlying_coupon_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_security_exchange) {
        auto r = eh10.set_string(308, *item10.underlying_security_exchange);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_issuer) {
        auto r = eh10.set_string(306, *item10.underlying_issuer);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.encoded_underlying_issuer) {
        auto r_len = eh10.set_int(362, static_cast<::std::int64_t>(item10.encoded_underlying_issuer->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = eh10.set_string(363, *item10.encoded_underlying_issuer);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (item10.underlying_security_desc) {
        auto r = eh10.set_string(307, *item10.underlying_security_desc);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.encoded_underlying_security_desc) {
        auto r_len = eh10.set_int(364, static_cast<::std::int64_t>(item10.encoded_underlying_security_desc->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = eh10.set_string(365, *item10.encoded_underlying_security_desc);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (item10.underlying_cp_program) {
        auto r = eh10.set_string(877, *item10.underlying_cp_program);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_cp_reg_type) {
        auto r = eh10.set_string(878, *item10.underlying_cp_reg_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_currency) {
        auto r = eh10.set_string(318, *item10.underlying_currency);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_qty) {
        auto r = eh10.set_decimal(879, *item10.underlying_qty);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_px) {
        auto r = eh10.set_decimal(810, *item10.underlying_px);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_dirty_price) {
        auto r = eh10.set_decimal(882, *item10.underlying_dirty_price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_end_price) {
        auto r = eh10.set_decimal(883, *item10.underlying_end_price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_start_value) {
        auto r = eh10.set_decimal(884, *item10.underlying_start_value);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_current_value) {
        auto r = eh10.set_decimal(885, *item10.underlying_current_value);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_end_value) {
        auto r = eh10.set_decimal(886, *item10.underlying_end_value);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item10.underlying_stips) {
        auto gh12 = eh10.group_begin(887, 888);
        if (!gh12) return ::std::unexpected(gh12.error());
        for (auto const& item12 : *item10.underlying_stips) {
            auto en12 = gh12->add_entry();
            if (!en12) return ::std::unexpected(en12.error());
            auto& eh12 = *en12;
    if (item12.underlying_stip_type) {
        auto r = eh12.set_string(888, *item12.underlying_stip_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item12.underlying_stip_value) {
        auto r = eh12.set_string(889, *item12.underlying_stip_value);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge12 = bb.group_end(*gh12);
        if (!ge12) return ::std::unexpected(ge12.error());
    }
        }
        auto ge10 = bb.group_end(*gh10);
        if (!ge10) return ::std::unexpected(ge10.error());
    }
    if (args.clearing_business_date) {
        auto r = bb.field(715, *args.clearing_business_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.settl_sess_id) {
        auto r = bb.field(716, *args.settl_sess_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.settl_sess_sub_id) {
        auto r = bb.field(717, *args.settl_sess_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.response_transport_type) {
        auto r = bb.field(725, *args.response_transport_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.response_destination) {
        auto r = bb.field(726, *args.response_destination);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.benchmark_security_id_source) {
        auto r = bb.field(761, *args.benchmark_security_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_sub_type) {
        auto r = bb.field(762, *args.security_sub_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.trd_reg_timestamps) {
        auto gh13 = bb.group_begin(768, 769);
        if (!gh13) return ::std::unexpected(gh13.error());
        for (auto const& item13 : *args.trd_reg_timestamps) {
            auto en13 = gh13->add_entry();
            if (!en13) return ::std::unexpected(en13.error());
            auto& eh13 = *en13;
    if (item13.trd_reg_timestamp) {
        auto r = eh13.set_string(769, *item13.trd_reg_timestamp);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item13.trd_reg_timestamp_type) {
        auto r = eh13.set_int(770, *item13.trd_reg_timestamp_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item13.trd_reg_timestamp_origin) {
        auto r = eh13.set_string(771, *item13.trd_reg_timestamp_origin);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge13 = bb.group_end(*gh13);
        if (!ge13) return ::std::unexpected(ge13.error());
    }
    if (args.termination_type) {
        auto r = bb.field(788, *args.termination_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.qty_type) {
        auto r = bb.field(854, *args.qty_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.events) {
        auto gh14 = bb.group_begin(864, 865);
        if (!gh14) return ::std::unexpected(gh14.error());
        for (auto const& item14 : *args.events) {
            auto en14 = gh14->add_entry();
            if (!en14) return ::std::unexpected(en14.error());
            auto& eh14 = *en14;
    if (item14.event_type) {
        auto r = eh14.set_int(865, *item14.event_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item14.event_date) {
        auto r = eh14.set_string(866, *item14.event_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item14.event_px) {
        auto r = eh14.set_decimal(867, *item14.event_px);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item14.event_text) {
        auto r = eh14.set_string(868, *item14.event_text);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge14 = bb.group_end(*gh14);
        if (!ge14) return ::std::unexpected(ge14.error());
    }
    if (args.dated_date) {
        auto r = bb.field(873, *args.dated_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.interest_accrual_date) {
        auto r = bb.field(874, *args.interest_accrual_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.cp_program) {
        auto r = bb.field(875, *args.cp_program);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.cp_reg_type) {
        auto r = bb.field(876, *args.cp_reg_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.trades) {
        auto gh15 = bb.group_begin(897, 571);
        if (!gh15) return ::std::unexpected(gh15.error());
        for (auto const& item15 : *args.trades) {
            auto en15 = gh15->add_entry();
            if (!en15) return ::std::unexpected(en15.error());
            auto& eh15 = *en15;
    if (item15.trade_report_id) {
        auto r = eh15.set_string(571, *item15.trade_report_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item15.secondary_trade_report_id) {
        auto r = eh15.set_string(818, *item15.secondary_trade_report_id);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge15 = bb.group_end(*gh15);
        if (!ge15) return ::std::unexpected(ge15.error());
    }
    if (args.margin_ratio) {
        auto r = bb.field(898, *args.margin_ratio);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.margin_excess) {
        auto r = bb.field(899, *args.margin_excess);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.total_net_value) {
        auto r = bb.field(900, *args.total_net_value);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.cash_outstanding) {
        auto r = bb.field(901, *args.cash_outstanding);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.coll_inquiry_id) {
        auto r = bb.field(909, *args.coll_inquiry_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.agreement_desc) {
        auto r = bb.field(913, *args.agreement_desc);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.agreement_id) {
        auto r = bb.field(914, *args.agreement_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.agreement_date) {
        auto r = bb.field(915, *args.agreement_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.start_date) {
        auto r = bb.field(916, *args.start_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.end_date) {
        auto r = bb.field(917, *args.end_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.agreement_currency) {
        auto r = bb.field(918, *args.agreement_currency);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.delivery_type) {
        auto r = bb.field(919, *args.delivery_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.end_accrued_interest_amt) {
        auto r = bb.field(920, *args.end_accrued_interest_amt);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.start_cash) {
        auto r = bb.field(921, *args.start_cash);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.end_cash) {
        auto r = bb.field(922, *args.end_cash);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.coll_inquiry_qualifier) {
        auto gh16 = bb.group_begin(938, 896);
        if (!gh16) return ::std::unexpected(gh16.error());
        for (auto const& item16 : *args.coll_inquiry_qualifier) {
            auto en16 = gh16->add_entry();
            if (!en16) return ::std::unexpected(en16.error());
            auto& eh16 = *en16;
    if (item16.coll_inquiry_qualifier) {
        auto r = eh16.set_int(896, *item16.coll_inquiry_qualifier);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge16 = bb.group_end(*gh16);
        if (!ge16) return ::std::unexpected(ge16.error());
    }
    if (args.strike_currency) {
        auto r = bb.field(947, *args.strike_currency);
        if (!r) return ::std::unexpected(r.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::v44
