// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v44/messages/ConfirmationAck.validator.inl -- inline validate_ body + this message's own top-level traits (data-model.md Entity 3).
#pragma once
#include "ConfirmationAck.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool ConfirmationAckArgs_required_60(::fixpp::v44::ConfirmationAckArgs const& a) noexcept { return a.transact_time.has_value(); }
inline bool ConfirmationAckArgs_required_75(::fixpp::v44::ConfirmationAckArgs const& a) noexcept { return a.trade_date.has_value(); }
inline bool ConfirmationAckArgs_required_664(::fixpp::v44::ConfirmationAckArgs const& a) noexcept { return a.confirm_id.has_value(); }
inline bool ConfirmationAckArgs_required_940(::fixpp::v44::ConfirmationAckArgs const& a) noexcept { return a.affirm_status.has_value(); }
template <> struct writer_traits<::fixpp::v44::ConfirmationAckArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::v44::ConfirmationAckArgs>, 4> required_checks = {{
        {60, &ConfirmationAckArgs_required_60},
        {75, &ConfirmationAckArgs_required_75},
        {664, &ConfirmationAckArgs_required_664},
        {940, &ConfirmationAckArgs_required_940},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::v44::ConfirmationAckArgs>, 0> group_checks = {};
};

}  // namespace fixpp::wire

namespace fixpp::v44 {

inline ::fixpp::core::expected_t<void> validate_ConfirmationAck(ConfirmationAckArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::v44
