// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v44/messages/DerivativeSecurityList.builder.cpp -- external-linkage build_ definition (data-model.md Entity 4), compiled only into fixpp_builders_<ver>; no validator symbol (SC-003).
#include "DerivativeSecurityList.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::v44 {

::fixpp::core::expected_t<::std::span<::std::byte>> build_DerivativeSecurityList(::std::span<::std::byte> out, DerivativeSecurityListArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"AA"};
    if (args.related_sym) {
        auto gh0 = bb.group_begin(146, 55);
        if (!gh0) return ::std::unexpected(gh0.error());
        for (auto const& item0 : *args.related_sym) {
            auto en0 = gh0->add_entry();
            if (!en0) return ::std::unexpected(en0.error());
            auto& eh0 = *en0;
    if (item0.symbol) {
        auto r = eh0.set_string(55, *item0.symbol);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.symbol_sfx) {
        auto r = eh0.set_string(65, *item0.symbol_sfx);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.security_id) {
        auto r = eh0.set_string(48, *item0.security_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.security_id_source) {
        auto r = eh0.set_string(22, *item0.security_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.security_alt_id) {
        auto gh1 = eh0.group_begin(454, 455);
        if (!gh1) return ::std::unexpected(gh1.error());
        for (auto const& item1 : *item0.security_alt_id) {
            auto en1 = gh1->add_entry();
            if (!en1) return ::std::unexpected(en1.error());
            auto& eh1 = *en1;
    if (item1.security_alt_id) {
        auto r = eh1.set_string(455, *item1.security_alt_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item1.security_alt_id_source) {
        auto r = eh1.set_string(456, *item1.security_alt_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge1 = bb.group_end(*gh1);
        if (!ge1) return ::std::unexpected(ge1.error());
    }
    if (item0.product) {
        auto r = eh0.set_int(460, *item0.product);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.cfi_code) {
        auto r = eh0.set_string(461, *item0.cfi_code);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.security_type) {
        auto r = eh0.set_string(167, *item0.security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.security_sub_type) {
        auto r = eh0.set_string(762, *item0.security_sub_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.maturity_month_year) {
        auto r = eh0.set_string(200, *item0.maturity_month_year);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.maturity_date) {
        auto r = eh0.set_string(541, *item0.maturity_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.put_or_call) {
        auto r = eh0.set_int(201, *item0.put_or_call);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.coupon_payment_date) {
        auto r = eh0.set_string(224, *item0.coupon_payment_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.issue_date) {
        auto r = eh0.set_string(225, *item0.issue_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.repo_collateral_security_type) {
        auto r = eh0.set_string(239, *item0.repo_collateral_security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.repurchase_term) {
        auto r = eh0.set_int(226, *item0.repurchase_term);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.repurchase_rate) {
        auto r = eh0.set_decimal(227, *item0.repurchase_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.factor) {
        auto r = eh0.set_decimal(228, *item0.factor);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.credit_rating) {
        auto r = eh0.set_string(255, *item0.credit_rating);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.instr_registry) {
        auto r = eh0.set_string(543, *item0.instr_registry);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.country_of_issue) {
        auto r = eh0.set_string(470, *item0.country_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.state_or_province_of_issue) {
        auto r = eh0.set_string(471, *item0.state_or_province_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.locale_of_issue) {
        auto r = eh0.set_string(472, *item0.locale_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.redemption_date) {
        auto r = eh0.set_string(240, *item0.redemption_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.strike_price) {
        auto r = eh0.set_decimal(202, *item0.strike_price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.strike_currency) {
        auto r = eh0.set_string(947, *item0.strike_currency);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.opt_attribute) {
        auto r = eh0.set_char(206, *item0.opt_attribute);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.contract_multiplier) {
        auto r = eh0.set_decimal(231, *item0.contract_multiplier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.coupon_rate) {
        auto r = eh0.set_decimal(223, *item0.coupon_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.security_exchange) {
        auto r = eh0.set_string(207, *item0.security_exchange);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.issuer) {
        auto r = eh0.set_string(106, *item0.issuer);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.encoded_issuer) {
        auto r_len = eh0.set_int(348, static_cast<::std::int64_t>(item0.encoded_issuer->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = eh0.set_string(349, *item0.encoded_issuer);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (item0.security_desc) {
        auto r = eh0.set_string(107, *item0.security_desc);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.encoded_security_desc) {
        auto r_len = eh0.set_int(350, static_cast<::std::int64_t>(item0.encoded_security_desc->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = eh0.set_string(351, *item0.encoded_security_desc);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (item0.pool) {
        auto r = eh0.set_string(691, *item0.pool);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.contract_settl_month) {
        auto r = eh0.set_string(667, *item0.contract_settl_month);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.cp_program) {
        auto r = eh0.set_int(875, *item0.cp_program);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.cp_reg_type) {
        auto r = eh0.set_string(876, *item0.cp_reg_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.events) {
        auto gh2 = eh0.group_begin(864, 865);
        if (!gh2) return ::std::unexpected(gh2.error());
        for (auto const& item2 : *item0.events) {
            auto en2 = gh2->add_entry();
            if (!en2) return ::std::unexpected(en2.error());
            auto& eh2 = *en2;
    if (item2.event_type) {
        auto r = eh2.set_int(865, *item2.event_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item2.event_date) {
        auto r = eh2.set_string(866, *item2.event_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item2.event_px) {
        auto r = eh2.set_decimal(867, *item2.event_px);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item2.event_text) {
        auto r = eh2.set_string(868, *item2.event_text);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge2 = bb.group_end(*gh2);
        if (!ge2) return ::std::unexpected(ge2.error());
    }
    if (item0.dated_date) {
        auto r = eh0.set_string(873, *item0.dated_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.interest_accrual_date) {
        auto r = eh0.set_string(874, *item0.interest_accrual_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.currency) {
        auto r = eh0.set_string(15, *item0.currency);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.expiration_cycle) {
        auto r = eh0.set_int(827, *item0.expiration_cycle);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.delivery_form) {
        auto r = eh0.set_int(668, *item0.delivery_form);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.pct_at_risk) {
        auto r = eh0.set_decimal(869, *item0.pct_at_risk);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.instr_attrib) {
        auto gh3 = eh0.group_begin(870, 871);
        if (!gh3) return ::std::unexpected(gh3.error());
        for (auto const& item3 : *item0.instr_attrib) {
            auto en3 = gh3->add_entry();
            if (!en3) return ::std::unexpected(en3.error());
            auto& eh3 = *en3;
    if (item3.instr_attrib_type) {
        auto r = eh3.set_int(871, *item3.instr_attrib_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item3.instr_attrib_value) {
        auto r = eh3.set_string(872, *item3.instr_attrib_value);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge3 = bb.group_end(*gh3);
        if (!ge3) return ::std::unexpected(ge3.error());
    }
    if (item0.legs) {
        auto gh4 = eh0.group_begin(555, 600);
        if (!gh4) return ::std::unexpected(gh4.error());
        for (auto const& item4 : *item0.legs) {
            auto en4 = gh4->add_entry();
            if (!en4) return ::std::unexpected(en4.error());
            auto& eh4 = *en4;
    if (item4.leg_symbol) {
        auto r = eh4.set_string(600, *item4.leg_symbol);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_symbol_sfx) {
        auto r = eh4.set_string(601, *item4.leg_symbol_sfx);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_security_id) {
        auto r = eh4.set_string(602, *item4.leg_security_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_security_id_source) {
        auto r = eh4.set_string(603, *item4.leg_security_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_security_alt_id) {
        auto gh5 = eh4.group_begin(604, 605);
        if (!gh5) return ::std::unexpected(gh5.error());
        for (auto const& item5 : *item4.leg_security_alt_id) {
            auto en5 = gh5->add_entry();
            if (!en5) return ::std::unexpected(en5.error());
            auto& eh5 = *en5;
    if (item5.leg_security_alt_id) {
        auto r = eh5.set_string(605, *item5.leg_security_alt_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item5.leg_security_alt_id_source) {
        auto r = eh5.set_string(606, *item5.leg_security_alt_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge5 = bb.group_end(*gh5);
        if (!ge5) return ::std::unexpected(ge5.error());
    }
    if (item4.leg_product) {
        auto r = eh4.set_int(607, *item4.leg_product);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_cfi_code) {
        auto r = eh4.set_string(608, *item4.leg_cfi_code);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_security_type) {
        auto r = eh4.set_string(609, *item4.leg_security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_security_sub_type) {
        auto r = eh4.set_string(764, *item4.leg_security_sub_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_maturity_month_year) {
        auto r = eh4.set_string(610, *item4.leg_maturity_month_year);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_maturity_date) {
        auto r = eh4.set_string(611, *item4.leg_maturity_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_coupon_payment_date) {
        auto r = eh4.set_string(248, *item4.leg_coupon_payment_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_issue_date) {
        auto r = eh4.set_string(249, *item4.leg_issue_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_repo_collateral_security_type) {
        auto r = eh4.set_string(250, *item4.leg_repo_collateral_security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_repurchase_term) {
        auto r = eh4.set_int(251, *item4.leg_repurchase_term);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_repurchase_rate) {
        auto r = eh4.set_decimal(252, *item4.leg_repurchase_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_factor) {
        auto r = eh4.set_decimal(253, *item4.leg_factor);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_credit_rating) {
        auto r = eh4.set_string(257, *item4.leg_credit_rating);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_instr_registry) {
        auto r = eh4.set_string(599, *item4.leg_instr_registry);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_country_of_issue) {
        auto r = eh4.set_string(596, *item4.leg_country_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_state_or_province_of_issue) {
        auto r = eh4.set_string(597, *item4.leg_state_or_province_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_locale_of_issue) {
        auto r = eh4.set_string(598, *item4.leg_locale_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_redemption_date) {
        auto r = eh4.set_string(254, *item4.leg_redemption_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_strike_price) {
        auto r = eh4.set_decimal(612, *item4.leg_strike_price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_strike_currency) {
        auto r = eh4.set_string(942, *item4.leg_strike_currency);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_opt_attribute) {
        auto r = eh4.set_char(613, *item4.leg_opt_attribute);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_contract_multiplier) {
        auto r = eh4.set_decimal(614, *item4.leg_contract_multiplier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_coupon_rate) {
        auto r = eh4.set_decimal(615, *item4.leg_coupon_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_security_exchange) {
        auto r = eh4.set_string(616, *item4.leg_security_exchange);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_issuer) {
        auto r = eh4.set_string(617, *item4.leg_issuer);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.encoded_leg_issuer) {
        auto r_len = eh4.set_int(618, static_cast<::std::int64_t>(item4.encoded_leg_issuer->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = eh4.set_string(619, *item4.encoded_leg_issuer);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (item4.leg_security_desc) {
        auto r = eh4.set_string(620, *item4.leg_security_desc);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.encoded_leg_security_desc) {
        auto r_len = eh4.set_int(621, static_cast<::std::int64_t>(item4.encoded_leg_security_desc->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = eh4.set_string(622, *item4.encoded_leg_security_desc);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (item4.leg_ratio_qty) {
        auto r = eh4.set_decimal(623, *item4.leg_ratio_qty);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_side) {
        auto r = eh4.set_char(624, *item4.leg_side);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_currency) {
        auto r = eh4.set_string(556, *item4.leg_currency);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_pool) {
        auto r = eh4.set_string(740, *item4.leg_pool);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_dated_date) {
        auto r = eh4.set_string(739, *item4.leg_dated_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_contract_settl_month) {
        auto r = eh4.set_string(955, *item4.leg_contract_settl_month);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item4.leg_interest_accrual_date) {
        auto r = eh4.set_string(956, *item4.leg_interest_accrual_date);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge4 = bb.group_end(*gh4);
        if (!ge4) return ::std::unexpected(ge4.error());
    }
    if (item0.trading_session_id) {
        auto r = eh0.set_string(336, *item0.trading_session_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.trading_session_sub_id) {
        auto r = eh0.set_string(625, *item0.trading_session_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.text) {
        auto r = eh0.set_string(58, *item0.text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.encoded_text) {
        auto r_len = eh0.set_int(354, static_cast<::std::int64_t>(item0.encoded_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = eh0.set_string(355, *item0.encoded_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
        }
        auto ge0 = bb.group_end(*gh0);
        if (!ge0) return ::std::unexpected(ge0.error());
    }
    if (args.underlying_coupon_payment_date) {
        auto r = bb.field(241, *args.underlying_coupon_payment_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_issue_date) {
        auto r = bb.field(242, *args.underlying_issue_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_repo_collateral_security_type) {
        auto r = bb.field(243, *args.underlying_repo_collateral_security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_repurchase_term) {
        auto r = bb.field(244, *args.underlying_repurchase_term);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_repurchase_rate) {
        auto r = bb.field(245, *args.underlying_repurchase_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_factor) {
        auto r = bb.field(246, *args.underlying_factor);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_redemption_date) {
        auto r = bb.field(247, *args.underlying_redemption_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_credit_rating) {
        auto r = bb.field(256, *args.underlying_credit_rating);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_security_id_source) {
        auto r = bb.field(305, *args.underlying_security_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_issuer) {
        auto r = bb.field(306, *args.underlying_issuer);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_security_desc) {
        auto r = bb.field(307, *args.underlying_security_desc);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_security_exchange) {
        auto r = bb.field(308, *args.underlying_security_exchange);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_security_id) {
        auto r = bb.field(309, *args.underlying_security_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_security_type) {
        auto r = bb.field(310, *args.underlying_security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_symbol) {
        auto r = bb.field(311, *args.underlying_symbol);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_symbol_sfx) {
        auto r = bb.field(312, *args.underlying_symbol_sfx);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_maturity_month_year) {
        auto r = bb.field(313, *args.underlying_maturity_month_year);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_put_or_call) {
        auto r = bb.field(315, *args.underlying_put_or_call);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_strike_price) {
        auto r = bb.field(316, *args.underlying_strike_price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_opt_attribute) {
        auto r = bb.field(317, *args.underlying_opt_attribute);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_currency) {
        auto r = bb.field(318, *args.underlying_currency);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_req_id) {
        auto r = bb.field(320, *args.security_req_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_response_id) {
        auto r = bb.field(322, *args.security_response_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_underlying_issuer) {
        auto r_len = bb.field(362, static_cast<::std::int64_t>(args.encoded_underlying_issuer->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(363, *args.encoded_underlying_issuer);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.encoded_underlying_security_desc) {
        auto r_len = bb.field(364, static_cast<::std::int64_t>(args.encoded_underlying_security_desc->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(365, *args.encoded_underlying_security_desc);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.tot_no_related_sym) {
        auto r = bb.field(393, *args.tot_no_related_sym);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_coupon_rate) {
        auto r = bb.field(435, *args.underlying_coupon_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_contract_multiplier) {
        auto r = bb.field(436, *args.underlying_contract_multiplier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_security_alt_id) {
        auto gh6 = bb.group_begin(457, 458);
        if (!gh6) return ::std::unexpected(gh6.error());
        for (auto const& item6 : *args.underlying_security_alt_id) {
            auto en6 = gh6->add_entry();
            if (!en6) return ::std::unexpected(en6.error());
            auto& eh6 = *en6;
    if (item6.underlying_security_alt_id) {
        auto r = eh6.set_string(458, *item6.underlying_security_alt_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item6.underlying_security_alt_id_source) {
        auto r = eh6.set_string(459, *item6.underlying_security_alt_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge6 = bb.group_end(*gh6);
        if (!ge6) return ::std::unexpected(ge6.error());
    }
    if (args.underlying_product) {
        auto r = bb.field(462, *args.underlying_product);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_cfi_code) {
        auto r = bb.field(463, *args.underlying_cfi_code);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_maturity_date) {
        auto r = bb.field(542, *args.underlying_maturity_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_request_result) {
        auto r = bb.field(560, *args.security_request_result);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_country_of_issue) {
        auto r = bb.field(592, *args.underlying_country_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_state_or_province_of_issue) {
        auto r = bb.field(593, *args.underlying_state_or_province_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_locale_of_issue) {
        auto r = bb.field(594, *args.underlying_locale_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_instr_registry) {
        auto r = bb.field(595, *args.underlying_instr_registry);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_security_sub_type) {
        auto r = bb.field(763, *args.underlying_security_sub_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_px) {
        auto r = bb.field(810, *args.underlying_px);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_cp_program) {
        auto r = bb.field(877, *args.underlying_cp_program);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_cp_reg_type) {
        auto r = bb.field(878, *args.underlying_cp_reg_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_qty) {
        auto r = bb.field(879, *args.underlying_qty);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_dirty_price) {
        auto r = bb.field(882, *args.underlying_dirty_price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_end_price) {
        auto r = bb.field(883, *args.underlying_end_price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_start_value) {
        auto r = bb.field(884, *args.underlying_start_value);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_current_value) {
        auto r = bb.field(885, *args.underlying_current_value);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_end_value) {
        auto r = bb.field(886, *args.underlying_end_value);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_stips) {
        auto gh7 = bb.group_begin(887, 888);
        if (!gh7) return ::std::unexpected(gh7.error());
        for (auto const& item7 : *args.underlying_stips) {
            auto en7 = gh7->add_entry();
            if (!en7) return ::std::unexpected(en7.error());
            auto& eh7 = *en7;
    if (item7.underlying_stip_type) {
        auto r = eh7.set_string(888, *item7.underlying_stip_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item7.underlying_stip_value) {
        auto r = eh7.set_string(889, *item7.underlying_stip_value);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge7 = bb.group_end(*gh7);
        if (!ge7) return ::std::unexpected(ge7.error());
    }
    if (args.last_fragment) {
        auto r = bb.field(893, (*args.last_fragment) ? 'Y' : 'N');
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_strike_currency) {
        auto r = bb.field(941, *args.underlying_strike_currency);
        if (!r) return ::std::unexpected(r.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::v44
