// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v44/messages/DerivativeSecurityListRequest.validator.inl -- inline validate_ body + this message's own top-level traits (data-model.md Entity 3).
#pragma once
#include "DerivativeSecurityListRequest.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool DerivativeSecurityListRequestArgs_required_320(::fixpp::v44::DerivativeSecurityListRequestArgs const& a) noexcept { return a.security_req_id.has_value(); }
inline bool DerivativeSecurityListRequestArgs_required_559(::fixpp::v44::DerivativeSecurityListRequestArgs const& a) noexcept { return a.security_list_request_type.has_value(); }
inline ::std::optional<::std::size_t> DerivativeSecurityListRequestArgs_count_underlying_security_alt_id(::fixpp::v44::DerivativeSecurityListRequestArgs const& a) noexcept { if (!a.underlying_security_alt_id) { return ::std::nullopt; } return a.underlying_security_alt_id->size(); }
inline ::fixpp::core::expected_t<void> DerivativeSecurityListRequestArgs_validate_entry_underlying_security_alt_id(::fixpp::v44::DerivativeSecurityListRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.underlying_security_alt_id)[i]); }
inline ::std::optional<::std::size_t> DerivativeSecurityListRequestArgs_count_underlying_stips(::fixpp::v44::DerivativeSecurityListRequestArgs const& a) noexcept { if (!a.underlying_stips) { return ::std::nullopt; } return a.underlying_stips->size(); }
inline ::fixpp::core::expected_t<void> DerivativeSecurityListRequestArgs_validate_entry_underlying_stips(::fixpp::v44::DerivativeSecurityListRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.underlying_stips)[i]); }
template <> struct writer_traits<::fixpp::v44::DerivativeSecurityListRequestArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::v44::DerivativeSecurityListRequestArgs>, 2> required_checks = {{
        {320, &DerivativeSecurityListRequestArgs_required_320},
        {559, &DerivativeSecurityListRequestArgs_required_559},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::v44::DerivativeSecurityListRequestArgs>, 2> group_checks = {{
        {false, &DerivativeSecurityListRequestArgs_count_underlying_security_alt_id, &DerivativeSecurityListRequestArgs_validate_entry_underlying_security_alt_id},
        {false, &DerivativeSecurityListRequestArgs_count_underlying_stips, &DerivativeSecurityListRequestArgs_validate_entry_underlying_stips},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::v44 {

inline ::fixpp::core::expected_t<void> validate_DerivativeSecurityListRequest(DerivativeSecurityListRequestArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::v44
