// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v44/messages/MarketDataRequestReject.validator.cpp -- external-linkage validate_ definition + this message's own top-level traits (data-model.md Entity 4), compiled only into fixpp_validators_<ver>.
#include "MarketDataRequestReject.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool MarketDataRequestRejectArgs_required_262(::fixpp::v44::MarketDataRequestRejectArgs const& a) noexcept { return a.md_req_id.has_value(); }
inline ::std::optional<::std::size_t> MarketDataRequestRejectArgs_count_alt_md_source(::fixpp::v44::MarketDataRequestRejectArgs const& a) noexcept { if (!a.alt_md_source) { return ::std::nullopt; } return a.alt_md_source->size(); }
inline ::fixpp::core::expected_t<void> MarketDataRequestRejectArgs_validate_entry_alt_md_source(::fixpp::v44::MarketDataRequestRejectArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.alt_md_source)[i]); }
template <> struct writer_traits<::fixpp::v44::MarketDataRequestRejectArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::v44::MarketDataRequestRejectArgs>, 1> required_checks = {{
        {262, &MarketDataRequestRejectArgs_required_262},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::v44::MarketDataRequestRejectArgs>, 1> group_checks = {{
        {false, &MarketDataRequestRejectArgs_count_alt_md_source, &MarketDataRequestRejectArgs_validate_entry_alt_md_source},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::v44 {

::fixpp::core::expected_t<void> validate_MarketDataRequestReject(MarketDataRequestRejectArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::v44
