// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v44/messages/MarketDataIncrementalRefresh.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include "../groups/G_268_2Args.hpp"
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::v44 {

struct MarketDataIncrementalRefreshArgs {
    ::std::optional<::std::string_view> md_req_id{};
    ::std::span<const groups::G_268_2Args> md_entries{};
    ::std::optional<::std::int64_t> appl_queue_depth{};
    ::std::optional<::std::int64_t> appl_queue_resolution{};
};

}  // namespace fixpp::v44

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_MarketDataIncrementalRefresh)
#include "MarketDataIncrementalRefresh.builder.inl"
#else
namespace fixpp::v44 {
::fixpp::core::expected_t<::std::span<::std::byte>> build_MarketDataIncrementalRefresh(::std::span<::std::byte> out, MarketDataIncrementalRefreshArgs const& args) noexcept;
}  // namespace fixpp::v44
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_MarketDataIncrementalRefresh)
#include "MarketDataIncrementalRefresh.validator.inl"
#else
namespace fixpp::v44 {
::fixpp::core::expected_t<void> validate_MarketDataIncrementalRefresh(MarketDataIncrementalRefreshArgs const& args) noexcept;
}  // namespace fixpp::v44
#endif
