// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v44/messages/NewOrderSingle.validator.cpp -- external-linkage validate_ definition + this message's own top-level traits (data-model.md Entity 4), compiled only into fixpp_validators_<ver>.
#include "NewOrderSingle.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool NewOrderSingleArgs_required_11(::fixpp::v44::NewOrderSingleArgs const& a) noexcept { return a.cl_ord_id.has_value(); }
inline bool NewOrderSingleArgs_required_40(::fixpp::v44::NewOrderSingleArgs const& a) noexcept { return a.ord_type.has_value(); }
inline bool NewOrderSingleArgs_required_54(::fixpp::v44::NewOrderSingleArgs const& a) noexcept { return a.side.has_value(); }
inline bool NewOrderSingleArgs_required_60(::fixpp::v44::NewOrderSingleArgs const& a) noexcept { return a.transact_time.has_value(); }
inline ::std::optional<::std::size_t> NewOrderSingleArgs_count_allocs(::fixpp::v44::NewOrderSingleArgs const& a) noexcept { if (!a.allocs) { return ::std::nullopt; } return a.allocs->size(); }
inline ::fixpp::core::expected_t<void> NewOrderSingleArgs_validate_entry_allocs(::fixpp::v44::NewOrderSingleArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.allocs)[i]); }
inline ::std::optional<::std::size_t> NewOrderSingleArgs_count_stipulations(::fixpp::v44::NewOrderSingleArgs const& a) noexcept { if (!a.stipulations) { return ::std::nullopt; } return a.stipulations->size(); }
inline ::fixpp::core::expected_t<void> NewOrderSingleArgs_validate_entry_stipulations(::fixpp::v44::NewOrderSingleArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.stipulations)[i]); }
inline ::std::optional<::std::size_t> NewOrderSingleArgs_count_trading_sessions(::fixpp::v44::NewOrderSingleArgs const& a) noexcept { if (!a.trading_sessions) { return ::std::nullopt; } return a.trading_sessions->size(); }
inline ::fixpp::core::expected_t<void> NewOrderSingleArgs_validate_entry_trading_sessions(::fixpp::v44::NewOrderSingleArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.trading_sessions)[i]); }
inline ::std::optional<::std::size_t> NewOrderSingleArgs_count_party_i_ds(::fixpp::v44::NewOrderSingleArgs const& a) noexcept { if (!a.party_i_ds) { return ::std::nullopt; } return a.party_i_ds->size(); }
inline ::fixpp::core::expected_t<void> NewOrderSingleArgs_validate_entry_party_i_ds(::fixpp::v44::NewOrderSingleArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.party_i_ds)[i]); }
inline ::std::optional<::std::size_t> NewOrderSingleArgs_count_security_alt_id(::fixpp::v44::NewOrderSingleArgs const& a) noexcept { if (!a.security_alt_id) { return ::std::nullopt; } return a.security_alt_id->size(); }
inline ::fixpp::core::expected_t<void> NewOrderSingleArgs_validate_entry_security_alt_id(::fixpp::v44::NewOrderSingleArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.security_alt_id)[i]); }
inline ::std::optional<::std::size_t> NewOrderSingleArgs_count_underlyings(::fixpp::v44::NewOrderSingleArgs const& a) noexcept { if (!a.underlyings) { return ::std::nullopt; } return a.underlyings->size(); }
inline ::fixpp::core::expected_t<void> NewOrderSingleArgs_validate_entry_underlyings(::fixpp::v44::NewOrderSingleArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.underlyings)[i]); }
inline ::std::optional<::std::size_t> NewOrderSingleArgs_count_events(::fixpp::v44::NewOrderSingleArgs const& a) noexcept { if (!a.events) { return ::std::nullopt; } return a.events->size(); }
inline ::fixpp::core::expected_t<void> NewOrderSingleArgs_validate_entry_events(::fixpp::v44::NewOrderSingleArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.events)[i]); }
template <> struct writer_traits<::fixpp::v44::NewOrderSingleArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::v44::NewOrderSingleArgs>, 4> required_checks = {{
        {11, &NewOrderSingleArgs_required_11},
        {40, &NewOrderSingleArgs_required_40},
        {54, &NewOrderSingleArgs_required_54},
        {60, &NewOrderSingleArgs_required_60},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::v44::NewOrderSingleArgs>, 7> group_checks = {{
        {false, &NewOrderSingleArgs_count_allocs, &NewOrderSingleArgs_validate_entry_allocs},
        {false, &NewOrderSingleArgs_count_stipulations, &NewOrderSingleArgs_validate_entry_stipulations},
        {false, &NewOrderSingleArgs_count_trading_sessions, &NewOrderSingleArgs_validate_entry_trading_sessions},
        {false, &NewOrderSingleArgs_count_party_i_ds, &NewOrderSingleArgs_validate_entry_party_i_ds},
        {false, &NewOrderSingleArgs_count_security_alt_id, &NewOrderSingleArgs_validate_entry_security_alt_id},
        {false, &NewOrderSingleArgs_count_underlyings, &NewOrderSingleArgs_validate_entry_underlyings},
        {false, &NewOrderSingleArgs_count_events, &NewOrderSingleArgs_validate_entry_events},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::v44 {

::fixpp::core::expected_t<void> validate_NewOrderSingle(NewOrderSingleArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::v44
