// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v44/messages/OrderCancelReplaceRequest.validator.cpp -- external-linkage validate_ definition + this message's own top-level traits (data-model.md Entity 4), compiled only into fixpp_validators_<ver>.
#include "OrderCancelReplaceRequest.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool OrderCancelReplaceRequestArgs_required_11(::fixpp::v44::OrderCancelReplaceRequestArgs const& a) noexcept { return a.cl_ord_id.has_value(); }
inline bool OrderCancelReplaceRequestArgs_required_40(::fixpp::v44::OrderCancelReplaceRequestArgs const& a) noexcept { return a.ord_type.has_value(); }
inline bool OrderCancelReplaceRequestArgs_required_41(::fixpp::v44::OrderCancelReplaceRequestArgs const& a) noexcept { return a.orig_cl_ord_id.has_value(); }
inline bool OrderCancelReplaceRequestArgs_required_54(::fixpp::v44::OrderCancelReplaceRequestArgs const& a) noexcept { return a.side.has_value(); }
inline bool OrderCancelReplaceRequestArgs_required_60(::fixpp::v44::OrderCancelReplaceRequestArgs const& a) noexcept { return a.transact_time.has_value(); }
inline ::std::optional<::std::size_t> OrderCancelReplaceRequestArgs_count_allocs(::fixpp::v44::OrderCancelReplaceRequestArgs const& a) noexcept { if (!a.allocs) { return ::std::nullopt; } return a.allocs->size(); }
inline ::fixpp::core::expected_t<void> OrderCancelReplaceRequestArgs_validate_entry_allocs(::fixpp::v44::OrderCancelReplaceRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.allocs)[i]); }
inline ::std::optional<::std::size_t> OrderCancelReplaceRequestArgs_count_trading_sessions(::fixpp::v44::OrderCancelReplaceRequestArgs const& a) noexcept { if (!a.trading_sessions) { return ::std::nullopt; } return a.trading_sessions->size(); }
inline ::fixpp::core::expected_t<void> OrderCancelReplaceRequestArgs_validate_entry_trading_sessions(::fixpp::v44::OrderCancelReplaceRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.trading_sessions)[i]); }
inline ::std::optional<::std::size_t> OrderCancelReplaceRequestArgs_count_party_i_ds(::fixpp::v44::OrderCancelReplaceRequestArgs const& a) noexcept { if (!a.party_i_ds) { return ::std::nullopt; } return a.party_i_ds->size(); }
inline ::fixpp::core::expected_t<void> OrderCancelReplaceRequestArgs_validate_entry_party_i_ds(::fixpp::v44::OrderCancelReplaceRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.party_i_ds)[i]); }
inline ::std::optional<::std::size_t> OrderCancelReplaceRequestArgs_count_security_alt_id(::fixpp::v44::OrderCancelReplaceRequestArgs const& a) noexcept { if (!a.security_alt_id) { return ::std::nullopt; } return a.security_alt_id->size(); }
inline ::fixpp::core::expected_t<void> OrderCancelReplaceRequestArgs_validate_entry_security_alt_id(::fixpp::v44::OrderCancelReplaceRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.security_alt_id)[i]); }
inline ::std::optional<::std::size_t> OrderCancelReplaceRequestArgs_count_underlyings(::fixpp::v44::OrderCancelReplaceRequestArgs const& a) noexcept { if (!a.underlyings) { return ::std::nullopt; } return a.underlyings->size(); }
inline ::fixpp::core::expected_t<void> OrderCancelReplaceRequestArgs_validate_entry_underlyings(::fixpp::v44::OrderCancelReplaceRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.underlyings)[i]); }
inline ::std::optional<::std::size_t> OrderCancelReplaceRequestArgs_count_events(::fixpp::v44::OrderCancelReplaceRequestArgs const& a) noexcept { if (!a.events) { return ::std::nullopt; } return a.events->size(); }
inline ::fixpp::core::expected_t<void> OrderCancelReplaceRequestArgs_validate_entry_events(::fixpp::v44::OrderCancelReplaceRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.events)[i]); }
template <> struct writer_traits<::fixpp::v44::OrderCancelReplaceRequestArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::v44::OrderCancelReplaceRequestArgs>, 5> required_checks = {{
        {11, &OrderCancelReplaceRequestArgs_required_11},
        {40, &OrderCancelReplaceRequestArgs_required_40},
        {41, &OrderCancelReplaceRequestArgs_required_41},
        {54, &OrderCancelReplaceRequestArgs_required_54},
        {60, &OrderCancelReplaceRequestArgs_required_60},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::v44::OrderCancelReplaceRequestArgs>, 6> group_checks = {{
        {false, &OrderCancelReplaceRequestArgs_count_allocs, &OrderCancelReplaceRequestArgs_validate_entry_allocs},
        {false, &OrderCancelReplaceRequestArgs_count_trading_sessions, &OrderCancelReplaceRequestArgs_validate_entry_trading_sessions},
        {false, &OrderCancelReplaceRequestArgs_count_party_i_ds, &OrderCancelReplaceRequestArgs_validate_entry_party_i_ds},
        {false, &OrderCancelReplaceRequestArgs_count_security_alt_id, &OrderCancelReplaceRequestArgs_validate_entry_security_alt_id},
        {false, &OrderCancelReplaceRequestArgs_count_underlyings, &OrderCancelReplaceRequestArgs_validate_entry_underlyings},
        {false, &OrderCancelReplaceRequestArgs_count_events, &OrderCancelReplaceRequestArgs_validate_entry_events},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::v44 {

::fixpp::core::expected_t<void> validate_OrderCancelReplaceRequest(OrderCancelReplaceRequestArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::v44
