// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v44/messages/OrderMassCancelRequest.builder.cpp -- external-linkage build_ definition (data-model.md Entity 4), compiled only into fixpp_builders_<ver>; no validator symbol (SC-003).
#include "OrderMassCancelRequest.hpp"
#include <fixpp/wire/body_builder.hpp>

namespace fixpp::v44 {

::fixpp::core::expected_t<::std::span<::std::byte>> build_OrderMassCancelRequest(::std::span<::std::byte> out, OrderMassCancelRequestArgs const& args) noexcept {
    ::fixpp::wire::body_builder bb{"q"};
    if (args.cl_ord_id) {
        auto r = bb.field(11, *args.cl_ord_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_id_source) {
        auto r = bb.field(22, *args.security_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_id) {
        auto r = bb.field(48, *args.security_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.side) {
        auto r = bb.field(54, *args.side);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.symbol) {
        auto r = bb.field(55, *args.symbol);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.text) {
        auto r = bb.field(58, *args.text);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.transact_time) {
        auto r = bb.field(60, *args.transact_time);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.symbol_sfx) {
        auto r = bb.field(65, *args.symbol_sfx);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.issuer) {
        auto r = bb.field(106, *args.issuer);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_desc) {
        auto r = bb.field(107, *args.security_desc);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_type) {
        auto r = bb.field(167, *args.security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.maturity_month_year) {
        auto r = bb.field(200, *args.maturity_month_year);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.put_or_call) {
        auto r = bb.field(201, *args.put_or_call);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.strike_price) {
        auto r = bb.field(202, *args.strike_price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.opt_attribute) {
        auto r = bb.field(206, *args.opt_attribute);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_exchange) {
        auto r = bb.field(207, *args.security_exchange);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.coupon_rate) {
        auto r = bb.field(223, *args.coupon_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.coupon_payment_date) {
        auto r = bb.field(224, *args.coupon_payment_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.issue_date) {
        auto r = bb.field(225, *args.issue_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.repurchase_term) {
        auto r = bb.field(226, *args.repurchase_term);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.repurchase_rate) {
        auto r = bb.field(227, *args.repurchase_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.factor) {
        auto r = bb.field(228, *args.factor);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.contract_multiplier) {
        auto r = bb.field(231, *args.contract_multiplier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.repo_collateral_security_type) {
        auto r = bb.field(239, *args.repo_collateral_security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.redemption_date) {
        auto r = bb.field(240, *args.redemption_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_coupon_payment_date) {
        auto r = bb.field(241, *args.underlying_coupon_payment_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_issue_date) {
        auto r = bb.field(242, *args.underlying_issue_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_repo_collateral_security_type) {
        auto r = bb.field(243, *args.underlying_repo_collateral_security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_repurchase_term) {
        auto r = bb.field(244, *args.underlying_repurchase_term);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_repurchase_rate) {
        auto r = bb.field(245, *args.underlying_repurchase_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_factor) {
        auto r = bb.field(246, *args.underlying_factor);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_redemption_date) {
        auto r = bb.field(247, *args.underlying_redemption_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.credit_rating) {
        auto r = bb.field(255, *args.credit_rating);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_credit_rating) {
        auto r = bb.field(256, *args.underlying_credit_rating);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_security_id_source) {
        auto r = bb.field(305, *args.underlying_security_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_issuer) {
        auto r = bb.field(306, *args.underlying_issuer);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_security_desc) {
        auto r = bb.field(307, *args.underlying_security_desc);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_security_exchange) {
        auto r = bb.field(308, *args.underlying_security_exchange);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_security_id) {
        auto r = bb.field(309, *args.underlying_security_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_security_type) {
        auto r = bb.field(310, *args.underlying_security_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_symbol) {
        auto r = bb.field(311, *args.underlying_symbol);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_symbol_sfx) {
        auto r = bb.field(312, *args.underlying_symbol_sfx);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_maturity_month_year) {
        auto r = bb.field(313, *args.underlying_maturity_month_year);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_put_or_call) {
        auto r = bb.field(315, *args.underlying_put_or_call);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_strike_price) {
        auto r = bb.field(316, *args.underlying_strike_price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_opt_attribute) {
        auto r = bb.field(317, *args.underlying_opt_attribute);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_currency) {
        auto r = bb.field(318, *args.underlying_currency);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.trading_session_id) {
        auto r = bb.field(336, *args.trading_session_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.encoded_issuer) {
        auto r_len = bb.field(348, static_cast<::std::int64_t>(args.encoded_issuer->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(349, *args.encoded_issuer);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.encoded_security_desc) {
        auto r_len = bb.field(350, static_cast<::std::int64_t>(args.encoded_security_desc->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(351, *args.encoded_security_desc);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.encoded_text) {
        auto r_len = bb.field(354, static_cast<::std::int64_t>(args.encoded_text->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(355, *args.encoded_text);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.encoded_underlying_issuer) {
        auto r_len = bb.field(362, static_cast<::std::int64_t>(args.encoded_underlying_issuer->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(363, *args.encoded_underlying_issuer);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.encoded_underlying_security_desc) {
        auto r_len = bb.field(364, static_cast<::std::int64_t>(args.encoded_underlying_security_desc->size()));
        if (!r_len) return ::std::unexpected(r_len.error());
        auto r_data = bb.field(365, *args.encoded_underlying_security_desc);
        if (!r_data) return ::std::unexpected(r_data.error());
    }
    if (args.underlying_coupon_rate) {
        auto r = bb.field(435, *args.underlying_coupon_rate);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_contract_multiplier) {
        auto r = bb.field(436, *args.underlying_contract_multiplier);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_alt_id) {
        auto gh0 = bb.group_begin(454, 455);
        if (!gh0) return ::std::unexpected(gh0.error());
        for (auto const& item0 : *args.security_alt_id) {
            auto en0 = gh0->add_entry();
            if (!en0) return ::std::unexpected(en0.error());
            auto& eh0 = *en0;
    if (item0.security_alt_id) {
        auto r = eh0.set_string(455, *item0.security_alt_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item0.security_alt_id_source) {
        auto r = eh0.set_string(456, *item0.security_alt_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge0 = bb.group_end(*gh0);
        if (!ge0) return ::std::unexpected(ge0.error());
    }
    if (args.underlying_security_alt_id) {
        auto gh1 = bb.group_begin(457, 458);
        if (!gh1) return ::std::unexpected(gh1.error());
        for (auto const& item1 : *args.underlying_security_alt_id) {
            auto en1 = gh1->add_entry();
            if (!en1) return ::std::unexpected(en1.error());
            auto& eh1 = *en1;
    if (item1.underlying_security_alt_id) {
        auto r = eh1.set_string(458, *item1.underlying_security_alt_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item1.underlying_security_alt_id_source) {
        auto r = eh1.set_string(459, *item1.underlying_security_alt_id_source);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge1 = bb.group_end(*gh1);
        if (!ge1) return ::std::unexpected(ge1.error());
    }
    if (args.product) {
        auto r = bb.field(460, *args.product);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.cfi_code) {
        auto r = bb.field(461, *args.cfi_code);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_product) {
        auto r = bb.field(462, *args.underlying_product);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_cfi_code) {
        auto r = bb.field(463, *args.underlying_cfi_code);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.country_of_issue) {
        auto r = bb.field(470, *args.country_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.state_or_province_of_issue) {
        auto r = bb.field(471, *args.state_or_province_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.locale_of_issue) {
        auto r = bb.field(472, *args.locale_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.secondary_cl_ord_id) {
        auto r = bb.field(526, *args.secondary_cl_ord_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.mass_cancel_request_type) {
        auto r = bb.field(530, *args.mass_cancel_request_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.maturity_date) {
        auto r = bb.field(541, *args.maturity_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_maturity_date) {
        auto r = bb.field(542, *args.underlying_maturity_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.instr_registry) {
        auto r = bb.field(543, *args.instr_registry);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_country_of_issue) {
        auto r = bb.field(592, *args.underlying_country_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_state_or_province_of_issue) {
        auto r = bb.field(593, *args.underlying_state_or_province_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_locale_of_issue) {
        auto r = bb.field(594, *args.underlying_locale_of_issue);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_instr_registry) {
        auto r = bb.field(595, *args.underlying_instr_registry);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.trading_session_sub_id) {
        auto r = bb.field(625, *args.trading_session_sub_id);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.contract_settl_month) {
        auto r = bb.field(667, *args.contract_settl_month);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.pool) {
        auto r = bb.field(691, *args.pool);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.security_sub_type) {
        auto r = bb.field(762, *args.security_sub_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_security_sub_type) {
        auto r = bb.field(763, *args.underlying_security_sub_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_px) {
        auto r = bb.field(810, *args.underlying_px);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.events) {
        auto gh2 = bb.group_begin(864, 865);
        if (!gh2) return ::std::unexpected(gh2.error());
        for (auto const& item2 : *args.events) {
            auto en2 = gh2->add_entry();
            if (!en2) return ::std::unexpected(en2.error());
            auto& eh2 = *en2;
    if (item2.event_type) {
        auto r = eh2.set_int(865, *item2.event_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item2.event_date) {
        auto r = eh2.set_string(866, *item2.event_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item2.event_px) {
        auto r = eh2.set_decimal(867, *item2.event_px);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item2.event_text) {
        auto r = eh2.set_string(868, *item2.event_text);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge2 = bb.group_end(*gh2);
        if (!ge2) return ::std::unexpected(ge2.error());
    }
    if (args.dated_date) {
        auto r = bb.field(873, *args.dated_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.interest_accrual_date) {
        auto r = bb.field(874, *args.interest_accrual_date);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.cp_program) {
        auto r = bb.field(875, *args.cp_program);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.cp_reg_type) {
        auto r = bb.field(876, *args.cp_reg_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_cp_program) {
        auto r = bb.field(877, *args.underlying_cp_program);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_cp_reg_type) {
        auto r = bb.field(878, *args.underlying_cp_reg_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_qty) {
        auto r = bb.field(879, *args.underlying_qty);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_dirty_price) {
        auto r = bb.field(882, *args.underlying_dirty_price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_end_price) {
        auto r = bb.field(883, *args.underlying_end_price);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_start_value) {
        auto r = bb.field(884, *args.underlying_start_value);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_current_value) {
        auto r = bb.field(885, *args.underlying_current_value);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_end_value) {
        auto r = bb.field(886, *args.underlying_end_value);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.underlying_stips) {
        auto gh3 = bb.group_begin(887, 888);
        if (!gh3) return ::std::unexpected(gh3.error());
        for (auto const& item3 : *args.underlying_stips) {
            auto en3 = gh3->add_entry();
            if (!en3) return ::std::unexpected(en3.error());
            auto& eh3 = *en3;
    if (item3.underlying_stip_type) {
        auto r = eh3.set_string(888, *item3.underlying_stip_type);
        if (!r) return ::std::unexpected(r.error());
    }
    if (item3.underlying_stip_value) {
        auto r = eh3.set_string(889, *item3.underlying_stip_value);
        if (!r) return ::std::unexpected(r.error());
    }
        }
        auto ge3 = bb.group_end(*gh3);
        if (!ge3) return ::std::unexpected(ge3.error());
    }
    if (args.underlying_strike_currency) {
        auto r = bb.field(941, *args.underlying_strike_currency);
        if (!r) return ::std::unexpected(r.error());
    }
    if (args.strike_currency) {
        auto r = bb.field(947, *args.strike_currency);
        if (!r) return ::std::unexpected(r.error());
    }
    return bb.commit(out);
}

}  // namespace fixpp::v44
