// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v44/messages/PositionMaintenanceReport.validator.cpp -- external-linkage validate_ definition + this message's own top-level traits (data-model.md Entity 4), compiled only into fixpp_validators_<ver>.
#include "PositionMaintenanceReport.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool PositionMaintenanceReportArgs_required_1(::fixpp::v44::PositionMaintenanceReportArgs const& a) noexcept { return a.account.has_value(); }
inline bool PositionMaintenanceReportArgs_required_60(::fixpp::v44::PositionMaintenanceReportArgs const& a) noexcept { return a.transact_time.has_value(); }
inline bool PositionMaintenanceReportArgs_required_581(::fixpp::v44::PositionMaintenanceReportArgs const& a) noexcept { return a.account_type.has_value(); }
inline bool PositionMaintenanceReportArgs_required_709(::fixpp::v44::PositionMaintenanceReportArgs const& a) noexcept { return a.pos_trans_type.has_value(); }
inline bool PositionMaintenanceReportArgs_required_712(::fixpp::v44::PositionMaintenanceReportArgs const& a) noexcept { return a.pos_maint_action.has_value(); }
inline bool PositionMaintenanceReportArgs_required_713(::fixpp::v44::PositionMaintenanceReportArgs const& a) noexcept { return a.orig_pos_req_ref_id.has_value(); }
inline bool PositionMaintenanceReportArgs_required_715(::fixpp::v44::PositionMaintenanceReportArgs const& a) noexcept { return a.clearing_business_date.has_value(); }
inline bool PositionMaintenanceReportArgs_required_721(::fixpp::v44::PositionMaintenanceReportArgs const& a) noexcept { return a.pos_maint_rpt_id.has_value(); }
inline bool PositionMaintenanceReportArgs_required_722(::fixpp::v44::PositionMaintenanceReportArgs const& a) noexcept { return a.pos_maint_status.has_value(); }
inline ::std::optional<::std::size_t> PositionMaintenanceReportArgs_count_trading_sessions(::fixpp::v44::PositionMaintenanceReportArgs const& a) noexcept { if (!a.trading_sessions) { return ::std::nullopt; } return a.trading_sessions->size(); }
inline ::fixpp::core::expected_t<void> PositionMaintenanceReportArgs_validate_entry_trading_sessions(::fixpp::v44::PositionMaintenanceReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.trading_sessions)[i]); }
inline ::std::optional<::std::size_t> PositionMaintenanceReportArgs_count_party_i_ds(::fixpp::v44::PositionMaintenanceReportArgs const& a) noexcept { if (!a.party_i_ds) { return ::std::nullopt; } return a.party_i_ds->size(); }
inline ::fixpp::core::expected_t<void> PositionMaintenanceReportArgs_validate_entry_party_i_ds(::fixpp::v44::PositionMaintenanceReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.party_i_ds)[i]); }
inline ::std::optional<::std::size_t> PositionMaintenanceReportArgs_count_security_alt_id(::fixpp::v44::PositionMaintenanceReportArgs const& a) noexcept { if (!a.security_alt_id) { return ::std::nullopt; } return a.security_alt_id->size(); }
inline ::fixpp::core::expected_t<void> PositionMaintenanceReportArgs_validate_entry_security_alt_id(::fixpp::v44::PositionMaintenanceReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.security_alt_id)[i]); }
inline ::std::optional<::std::size_t> PositionMaintenanceReportArgs_count_legs(::fixpp::v44::PositionMaintenanceReportArgs const& a) noexcept { if (!a.legs) { return ::std::nullopt; } return a.legs->size(); }
inline ::fixpp::core::expected_t<void> PositionMaintenanceReportArgs_validate_entry_legs(::fixpp::v44::PositionMaintenanceReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.legs)[i]); }
inline ::std::optional<::std::size_t> PositionMaintenanceReportArgs_count_positions(::fixpp::v44::PositionMaintenanceReportArgs const& a) noexcept { if (!a.positions) { return ::std::nullopt; } return a.positions->size(); }
inline ::fixpp::core::expected_t<void> PositionMaintenanceReportArgs_validate_entry_positions(::fixpp::v44::PositionMaintenanceReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.positions)[i]); }
inline ::std::optional<::std::size_t> PositionMaintenanceReportArgs_count_underlyings(::fixpp::v44::PositionMaintenanceReportArgs const& a) noexcept { if (!a.underlyings) { return ::std::nullopt; } return a.underlyings->size(); }
inline ::fixpp::core::expected_t<void> PositionMaintenanceReportArgs_validate_entry_underlyings(::fixpp::v44::PositionMaintenanceReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.underlyings)[i]); }
inline ::std::optional<::std::size_t> PositionMaintenanceReportArgs_count_pos_amt(::fixpp::v44::PositionMaintenanceReportArgs const& a) noexcept { if (!a.pos_amt) { return ::std::nullopt; } return a.pos_amt->size(); }
inline ::fixpp::core::expected_t<void> PositionMaintenanceReportArgs_validate_entry_pos_amt(::fixpp::v44::PositionMaintenanceReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.pos_amt)[i]); }
inline ::std::optional<::std::size_t> PositionMaintenanceReportArgs_count_events(::fixpp::v44::PositionMaintenanceReportArgs const& a) noexcept { if (!a.events) { return ::std::nullopt; } return a.events->size(); }
inline ::fixpp::core::expected_t<void> PositionMaintenanceReportArgs_validate_entry_events(::fixpp::v44::PositionMaintenanceReportArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.events)[i]); }
template <> struct writer_traits<::fixpp::v44::PositionMaintenanceReportArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::v44::PositionMaintenanceReportArgs>, 9> required_checks = {{
        {1, &PositionMaintenanceReportArgs_required_1},
        {60, &PositionMaintenanceReportArgs_required_60},
        {581, &PositionMaintenanceReportArgs_required_581},
        {709, &PositionMaintenanceReportArgs_required_709},
        {712, &PositionMaintenanceReportArgs_required_712},
        {713, &PositionMaintenanceReportArgs_required_713},
        {715, &PositionMaintenanceReportArgs_required_715},
        {721, &PositionMaintenanceReportArgs_required_721},
        {722, &PositionMaintenanceReportArgs_required_722},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::v44::PositionMaintenanceReportArgs>, 8> group_checks = {{
        {false, &PositionMaintenanceReportArgs_count_trading_sessions, &PositionMaintenanceReportArgs_validate_entry_trading_sessions},
        {false, &PositionMaintenanceReportArgs_count_party_i_ds, &PositionMaintenanceReportArgs_validate_entry_party_i_ds},
        {false, &PositionMaintenanceReportArgs_count_security_alt_id, &PositionMaintenanceReportArgs_validate_entry_security_alt_id},
        {false, &PositionMaintenanceReportArgs_count_legs, &PositionMaintenanceReportArgs_validate_entry_legs},
        {false, &PositionMaintenanceReportArgs_count_positions, &PositionMaintenanceReportArgs_validate_entry_positions},
        {false, &PositionMaintenanceReportArgs_count_underlyings, &PositionMaintenanceReportArgs_validate_entry_underlyings},
        {false, &PositionMaintenanceReportArgs_count_pos_amt, &PositionMaintenanceReportArgs_validate_entry_pos_amt},
        {false, &PositionMaintenanceReportArgs_count_events, &PositionMaintenanceReportArgs_validate_entry_events},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::v44 {

::fixpp::core::expected_t<void> validate_PositionMaintenanceReport(PositionMaintenanceReportArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::v44
