// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v44/messages/QuoteRequest.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include "../groups/G_146_5Args.hpp"
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::v44 {

struct QuoteRequestArgs {
    ::std::optional<::std::string_view> cl_ord_id{};
    ::std::optional<::std::string_view> text{};
    ::std::optional<::std::string_view> quote_req_id{};
    ::std::span<const groups::G_146_5Args> related_sym{};
    ::std::optional<::std::string_view> encoded_text{};
    ::std::optional<char> order_capacity{};
    ::std::optional<::std::string_view> rfq_req_id{};
};

}  // namespace fixpp::v44

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_QuoteRequest)
#include "QuoteRequest.builder.inl"
#else
namespace fixpp::v44 {
::fixpp::core::expected_t<::std::span<::std::byte>> build_QuoteRequest(::std::span<::std::byte> out, QuoteRequestArgs const& args) noexcept;
}  // namespace fixpp::v44
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_QuoteRequest)
#include "QuoteRequest.validator.inl"
#else
namespace fixpp::v44 {
::fixpp::core::expected_t<void> validate_QuoteRequest(QuoteRequestArgs const& args) noexcept;
}  // namespace fixpp::v44
#endif
