// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v44/messages/TradingSessionStatusRequest.validator.inl -- inline validate_ body + this message's own top-level traits (data-model.md Entity 3).
#pragma once
#include "TradingSessionStatusRequest.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool TradingSessionStatusRequestArgs_required_263(::fixpp::v44::TradingSessionStatusRequestArgs const& a) noexcept { return a.subscription_request_type.has_value(); }
inline bool TradingSessionStatusRequestArgs_required_335(::fixpp::v44::TradingSessionStatusRequestArgs const& a) noexcept { return a.trad_ses_req_id.has_value(); }
template <> struct writer_traits<::fixpp::v44::TradingSessionStatusRequestArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::v44::TradingSessionStatusRequestArgs>, 2> required_checks = {{
        {263, &TradingSessionStatusRequestArgs_required_263},
        {335, &TradingSessionStatusRequestArgs_required_335},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::v44::TradingSessionStatusRequestArgs>, 0> group_checks = {};
};

}  // namespace fixpp::wire

namespace fixpp::v44 {

inline ::fixpp::core::expected_t<void> validate_TradingSessionStatusRequest(TradingSessionStatusRequestArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::v44
