#!/usr/bin/env bash
# Regression pin for ci/pump-census.sh (#289).
#
# Wired into the `ci-script-pins` job, the only pre-merge signal these scripts
# get: all three tier matrices skip until both gate labels land, so a checker
# exercised only by the matrix is unexercised at review time.
#
# This repo's rule for instruments is that a passing run proves nothing until
# the instrument has been shown able to FAIL, for the stated reason, on a tree
# where the defect is present. Every numbered case below drives a deliberately
# WRONG fixture or a deliberately WRONG pin through the real script and
# requires it to redden for the named reason — not just any reason. Two of
# these are load-bearing in a way the others are not: the added-site and
# removed-site cases prove EXACT SET equality (not a floor, and not a
# ceiling) — a count-only comparison would pass a fixture that lost one site
# and gained a different one, and an upward-only comparison would leave a
# stale pin permanently green after a legitimate downward migration.
#
# Usage:  bash ci/test-pump-census.sh
set -uo pipefail

fail() {
    echo "FAIL: $*" >&2
    exit 1
}

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$here/.." && pwd)"
script="$here/pump-census.sh"
production_pin="$here/expected-pump-sites.txt"

[ -f "$script" ] || fail "missing census script: $script"
[ -s "$production_pin" ] || fail "production pin is missing or empty"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

checks=0
expected_checks=16
pass() { checks=$((checks + 1)); }

run_capture() {
    output="$("$@" 2>&1)"
    status=$?
}

# ── 1-3: production control, invoked from a deliberately unrelated cwd ──────
# Proves the script resolves the repo root from its OWN location, not from
# the caller's cwd (Q2 assertion 9), and that the production pin the script
# ships with is exactly what the live tree produces (Q2 assertion 10 — the
# "nonempty, sorted, unique, and exactly equal to production output" half is
# proven implicitly: pump-census.sh itself refuses a malformed/duplicate pin
# before it ever compares, so an exit 0 here already implies that shape).
#
# ⚠️ THIS CHECK DEPENDS ON ci/expected-pump-sites.txt MATCHING THE LIVE TREE
# AT THE INSTANT THIS RUNS. That is intentional — it is the production gate,
# not a synthetic fixture — but it means this check goes RED (loudly, with
# the exact `path:line` diff) whenever an unrelated concurrent edit shifts a
# line number in a file the census also matches. That is the pin's job
# working correctly, not a defect in this harness: a stale pin must fail
# loudly rather than being silently tolerated. See #289 batch B3 hand-off —
# the pin was generated once from the tree as found and is regenerated by
# the orchestrator after all migration batches land, not by this script.
output="$(cd "$tmp" && bash "$script" 2>&1)"
status=$?
[ "$status" -eq 0 ] ||
    fail "production census failed from a different cwd: $output"
pass

[ -n "$output" ] ||
    fail "production census passed with empty output"
pass

production_count="$(printf '%s\n' "$output" | wc -l | tr -d '[:space:]')"
pin_count="$(wc -l <"$production_pin" | tr -d '[:space:]')"
[ "$production_count" = "$pin_count" ] ||
    fail "production output count $production_count != pin count $pin_count"
pass

# ── fixture: a known-good site, a comment/string decoy, and a too-far decoy ─
fixture="$tmp/fixture"
mkdir -p "$fixture/tests"

cat >"$fixture/tests/a.cpp" <<'EOF'
void baseline() {
    ioc.run_for(1ms);
    ioc.restart();
    fut.get();
}

/* ioc.run_for(1ms);
   ignored.get(); */
const char* text = "ioc.run_for(1ms); ignored.get();";

void too_far() {
    ioc.run_for(1ms);
    one();
    two();
    three();
    four();
    five();
    six();
    late.get();
}
EOF

baseline_pin="$tmp/baseline.pin"
printf '%s\n' 'tests/a.cpp:2' >"$baseline_pin"

# ── 4-5: known-good fixture produces EXACTLY the expected path:line ─────────
run_capture bash "$script" --root "$fixture" --expected "$baseline_pin"
[ "$status" -eq 0 ] ||
    fail "known-good fixture failed: $output"
pass

[ "$output" = "tests/a.cpp:2" ] ||
    fail "fixture matched the wrong set (comment/string/7-lines-away decoys must NOT match): $output"
pass

# ── 6-7: comments, string literals, and a .get() 7 lines away — implicit ────
# in check 5 above (the ONLY line in the output is tests/a.cpp:2), but pinned
# explicitly here too: the fixture's decoys are named, and if any of them
# leaked into the output, check 5's exact-string comparison would already
# have failed with a DIFFERENT (wrong) line list, not just a wrong count.
printf '%s\n' "$output" | grep -Fq 'a.cpp:7' &&
    fail "block-comment decoy matched (should be blanked)"
pass
printf '%s\n' "$output" | grep -Fq 'a.cpp:9' &&
    fail "string-literal decoy matched (should be blanked)"
pass

# ── add a genuine header site: proves hpp scope and upward drift ────────────
cat >"$fixture/tests/b.hpp" <<'EOF'
void added() { ioc.run_for(1ms);
    added_future.get();
}
EOF

# ── 8-10: an ADDED site makes the census exit nonzero, naming the site ──────
run_capture bash "$script" --root "$fixture" --expected "$baseline_pin"
[ "$status" -ne 0 ] ||
    fail "added .hpp site did not make the census RED"
pass

printf '%s\n' "$output" | grep -Fq \
    'pump-census: error: census differs from pin' ||
    fail "added-site mutant failed without the census-mismatch diagnostic"
pass

printf '%s\n' "$output" | grep -Fq '+tests/b.hpp:1' ||
    fail "added-site mutant did not identify tests/b.hpp:1 — .hpp scope or diff naming broken"
pass

# ── 11-12: a stale (too-high) pin also fails — proves downward ratcheting ───
# (Q3: exact-set equality forces a legitimate migration's pin down, not just
# a floor that only catches upward drift.)
stale_pin="$tmp/stale.pin"
printf '%s\n' \
    'tests/a.cpp:2' \
    'tests/b.hpp:1' >"$stale_pin"

rm "$fixture/tests/b.hpp"

run_capture bash "$script" --root "$fixture" --expected "$stale_pin"
[ "$status" -ne 0 ] ||
    fail "stale high pin passed after a site was removed"
pass

printf '%s\n' "$output" | grep -Fq -- '-tests/b.hpp:1' ||
    fail "downward mutant did not identify the stale pinned site"
pass

# ── 13-14: zero-match tree is an instrument-liveness failure, not "clean" ───
zero="$tmp/zero"
mkdir -p "$zero/tests"
printf '%s\n' 'int no_candidate;' >"$zero/tests/empty.cpp"

run_capture bash "$script" --root "$zero" --expected "$baseline_pin"
[ "$status" -ne 0 ] ||
    fail "zero-match tree passed"
pass

printf '%s\n' "$output" | grep -Fq \
    'instrument produced zero sites' ||
    fail "zero-match failure was not attributed to instrument liveness"
pass

# ── 15-16: missing/wrongly-rooted tests/ fails loudly, not silently-empty ───
run_capture bash "$script" \
    --root "$tmp/does-not-exist" \
    --expected "$baseline_pin"

[ "$status" -ne 0 ] ||
    fail "missing scan root passed"
pass

printf '%s\n' "$output" | grep -Fq 'tests directory not found' ||
    fail "missing-root failure lacked an attributed diagnostic"
pass

# ── self-assert the declared assertion count (Q2 assertion 11) ──────────────
# Not itself counted in $checks: a check that increments its own tally after
# reading it would compare against a total that has not yet included itself.
[ "$checks" -eq "$expected_checks" ] ||
    fail "ran $checks assertions; declared $expected_checks"

echo "PASS: $checks pump-census assertions"
