// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v50sp2/groups/G_1310_1Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include "G_1205Args.hpp"
#include "G_1234Args.hpp"
#include "G_2550Args.hpp"
#include "G_2558Args.hpp"
#include "G_1309Args.hpp"
#include "G_1312Args.hpp"
#include "G_1201Args.hpp"
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::v50sp2::groups {

struct G_1310_1Args {
    ::std::optional<::std::string_view> market_id{};
    ::std::optional<::std::string_view> market_segment_id{};
    ::std::optional<::std::span<const G_1205Args>> tick_rules{};
    ::std::optional<::std::span<const G_1234Args>> lot_type_rules{};
    ::std::optional<::std::int64_t> price_limit_type{};
    ::std::optional<::fixpp::decimal_t> low_limit_price{};
    ::std::optional<::fixpp::decimal_t> high_limit_price{};
    ::std::optional<::fixpp::decimal_t> trading_reference_price{};
    ::std::optional<::std::span<const G_2550Args>> price_range_rules{};
    ::std::optional<::std::span<const G_2558Args>> quote_size_rules{};
    ::std::optional<::std::int64_t> expiration_cycle{};
    ::std::optional<::std::int64_t> trade_vol_type{};
    ::std::optional<::fixpp::decimal_t> min_trade_vol{};
    ::std::optional<::fixpp::decimal_t> max_trade_vol{};
    ::std::optional<::fixpp::decimal_t> max_price_variation{};
    ::std::optional<::std::int64_t> implied_market_indicator{};
    ::std::optional<::std::string_view> trading_currency{};
    ::std::optional<::std::string_view> trading_currency_code_source{};
    ::std::optional<::fixpp::decimal_t> round_lot{};
    ::std::optional<::std::int64_t> multileg_model{};
    ::std::optional<::std::int64_t> multileg_price_method{};
    ::std::optional<::std::int64_t> price_type{};
    ::std::optional<::fixpp::decimal_t> fast_market_percentage{};
    ::std::optional<bool> quote_side_indicator{};
    ::std::optional<::std::span<const G_1309Args>> trading_session_rules{};
    ::std::optional<::std::span<const G_1312Args>> nested_instr_attrib{};
    ::std::optional<::std::span<const G_1201Args>> strike_rules{};
};

}  // namespace fixpp::v50sp2::groups
