// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v50sp2/groups/G_1844Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::v50sp2::groups {

struct G_1844Args {
    ::std::optional<::std::string_view> trade_alloc_amt_type{};
    ::std::optional<::fixpp::decimal_t> trade_alloc_amt{};
    ::std::optional<::std::string_view> trade_alloc_currency{};
    ::std::optional<::std::string_view> trade_alloc_currency_code_source{};
    ::std::optional<::std::int64_t> trade_alloc_amt_reason{};
};

}  // namespace fixpp::v50sp2::groups
