// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/v50sp2/groups/G_41227Args.hpp -- one shared repeating-group Args struct (data-model.md Entity 1); DATA-ONLY, no validator traits; includes only this plan's direct child group headers.
#pragma once
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::v50sp2::groups {

struct G_41227Args {
    ::std::optional<::std::int64_t> payment_stream_pricing_day_of_week{};
    ::std::optional<::std::int64_t> payment_stream_pricing_day_number{};
};

}  // namespace fixpp::v50sp2::groups
