// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/CollateralResponse.validator.inl -- inline validate_ body + this message's own top-level traits (data-model.md Entity 3).
#pragma once
#include "CollateralResponse.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool CollateralResponseArgs_required_60(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { return a.transact_time.has_value(); }
inline bool CollateralResponseArgs_required_904(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { return a.coll_resp_id.has_value(); }
inline bool CollateralResponseArgs_required_905(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { return a.coll_asgn_resp_type.has_value(); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_execs(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.execs) { return ::std::nullopt; } return a.execs->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_execs(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.execs)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_misc_fees(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.misc_fees) { return ::std::nullopt; } return a.misc_fees->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_misc_fees(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.misc_fees)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_stipulations(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.stipulations) { return ::std::nullopt; } return a.stipulations->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_stipulations(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.stipulations)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_party_i_ds(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.party_i_ds) { return ::std::nullopt; } return a.party_i_ds->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_party_i_ds(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.party_i_ds)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_security_alt_id(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.security_alt_id) { return ::std::nullopt; } return a.security_alt_id->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_security_alt_id(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.security_alt_id)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_legs(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.legs) { return ::std::nullopt; } return a.legs->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_legs(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.legs)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_underlyings(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.underlyings) { return ::std::nullopt; } return a.underlyings->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_underlyings(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.underlyings)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_trd_reg_timestamps(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.trd_reg_timestamps) { return ::std::nullopt; } return a.trd_reg_timestamps->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_trd_reg_timestamps(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.trd_reg_timestamps)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_events(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.events) { return ::std::nullopt; } return a.events->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_events(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.events)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_trades(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.trades) { return ::std::nullopt; } return a.trades->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_trades(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.trades)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_instrument_parties(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.instrument_parties) { return ::std::nullopt; } return a.instrument_parties->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_instrument_parties(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.instrument_parties)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_complex_events(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.complex_events) { return ::std::nullopt; } return a.complex_events->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_complex_events(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.complex_events)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_collateral_amounts(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.collateral_amounts) { return ::std::nullopt; } return a.collateral_amounts->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_collateral_amounts(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.collateral_amounts)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_secondary_asset_classes(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.secondary_asset_classes) { return ::std::nullopt; } return a.secondary_asset_classes->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_secondary_asset_classes(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.secondary_asset_classes)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_asset_attributes(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.asset_attributes) { return ::std::nullopt; } return a.asset_attributes->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_asset_attributes(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.asset_attributes)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_additional_terms(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.additional_terms) { return ::std::nullopt; } return a.additional_terms->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_additional_terms(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.additional_terms)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_cash_settl_terms(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.cash_settl_terms) { return ::std::nullopt; } return a.cash_settl_terms->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_cash_settl_terms(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.cash_settl_terms)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_contractual_definitions(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.contractual_definitions) { return ::std::nullopt; } return a.contractual_definitions->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_contractual_definitions(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.contractual_definitions)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_contractual_matrices(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.contractual_matrices) { return ::std::nullopt; } return a.contractual_matrices->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_contractual_matrices(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.contractual_matrices)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_financing_term_supplements(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.financing_term_supplements) { return ::std::nullopt; } return a.financing_term_supplements->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_financing_term_supplements(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.financing_term_supplements)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_streams(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.streams) { return ::std::nullopt; } return a.streams->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_streams(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.streams)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_provisions(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.provisions) { return ::std::nullopt; } return a.provisions->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_provisions(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.provisions)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_protection_terms(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.protection_terms) { return ::std::nullopt; } return a.protection_terms->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_protection_terms(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.protection_terms)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_physical_settl_terms(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.physical_settl_terms) { return ::std::nullopt; } return a.physical_settl_terms->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_physical_settl_terms(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.physical_settl_terms)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_business_centers(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.business_centers) { return ::std::nullopt; } return a.business_centers->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_business_centers(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.business_centers)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_market_disruption_events(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.market_disruption_events) { return ::std::nullopt; } return a.market_disruption_events->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_market_disruption_events(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.market_disruption_events)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_market_disruption_fallbacks(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.market_disruption_fallbacks) { return ::std::nullopt; } return a.market_disruption_fallbacks->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_market_disruption_fallbacks(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.market_disruption_fallbacks)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_market_disruption_fallback_reference_prices(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.market_disruption_fallback_reference_prices) { return ::std::nullopt; } return a.market_disruption_fallback_reference_prices->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_market_disruption_fallback_reference_prices(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.market_disruption_fallback_reference_prices)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_option_exercise_business_centers(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.option_exercise_business_centers) { return ::std::nullopt; } return a.option_exercise_business_centers->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_option_exercise_business_centers(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.option_exercise_business_centers)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_option_exercise_dates(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.option_exercise_dates) { return ::std::nullopt; } return a.option_exercise_dates->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_option_exercise_dates(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.option_exercise_dates)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_option_exercise_expiration_date_business_centers(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.option_exercise_expiration_date_business_centers) { return ::std::nullopt; } return a.option_exercise_expiration_date_business_centers->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_option_exercise_expiration_date_business_centers(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.option_exercise_expiration_date_business_centers)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_option_exercise_expiration_dates(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.option_exercise_expiration_dates) { return ::std::nullopt; } return a.option_exercise_expiration_dates->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_option_exercise_expiration_dates(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.option_exercise_expiration_dates)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_pricing_date_business_centers(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.pricing_date_business_centers) { return ::std::nullopt; } return a.pricing_date_business_centers->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_pricing_date_business_centers(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.pricing_date_business_centers)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_extraordinary_events(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.extraordinary_events) { return ::std::nullopt; } return a.extraordinary_events->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_extraordinary_events(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.extraordinary_events)[i]); }
inline ::std::optional<::std::size_t> CollateralResponseArgs_count_settl_method_election_date_business_centers(::fixpp::vlatest::CollateralResponseArgs const& a) noexcept { if (!a.settl_method_election_date_business_centers) { return ::std::nullopt; } return a.settl_method_election_date_business_centers->size(); }
inline ::fixpp::core::expected_t<void> CollateralResponseArgs_validate_entry_settl_method_election_date_business_centers(::fixpp::vlatest::CollateralResponseArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.settl_method_election_date_business_centers)[i]); }
template <> struct writer_traits<::fixpp::vlatest::CollateralResponseArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::vlatest::CollateralResponseArgs>, 3> required_checks = {{
        {60, &CollateralResponseArgs_required_60},
        {904, &CollateralResponseArgs_required_904},
        {905, &CollateralResponseArgs_required_905},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::vlatest::CollateralResponseArgs>, 35> group_checks = {{
        {false, &CollateralResponseArgs_count_execs, &CollateralResponseArgs_validate_entry_execs},
        {false, &CollateralResponseArgs_count_misc_fees, &CollateralResponseArgs_validate_entry_misc_fees},
        {false, &CollateralResponseArgs_count_stipulations, &CollateralResponseArgs_validate_entry_stipulations},
        {false, &CollateralResponseArgs_count_party_i_ds, &CollateralResponseArgs_validate_entry_party_i_ds},
        {false, &CollateralResponseArgs_count_security_alt_id, &CollateralResponseArgs_validate_entry_security_alt_id},
        {false, &CollateralResponseArgs_count_legs, &CollateralResponseArgs_validate_entry_legs},
        {false, &CollateralResponseArgs_count_underlyings, &CollateralResponseArgs_validate_entry_underlyings},
        {false, &CollateralResponseArgs_count_trd_reg_timestamps, &CollateralResponseArgs_validate_entry_trd_reg_timestamps},
        {false, &CollateralResponseArgs_count_events, &CollateralResponseArgs_validate_entry_events},
        {false, &CollateralResponseArgs_count_trades, &CollateralResponseArgs_validate_entry_trades},
        {false, &CollateralResponseArgs_count_instrument_parties, &CollateralResponseArgs_validate_entry_instrument_parties},
        {false, &CollateralResponseArgs_count_complex_events, &CollateralResponseArgs_validate_entry_complex_events},
        {false, &CollateralResponseArgs_count_collateral_amounts, &CollateralResponseArgs_validate_entry_collateral_amounts},
        {false, &CollateralResponseArgs_count_secondary_asset_classes, &CollateralResponseArgs_validate_entry_secondary_asset_classes},
        {false, &CollateralResponseArgs_count_asset_attributes, &CollateralResponseArgs_validate_entry_asset_attributes},
        {false, &CollateralResponseArgs_count_additional_terms, &CollateralResponseArgs_validate_entry_additional_terms},
        {false, &CollateralResponseArgs_count_cash_settl_terms, &CollateralResponseArgs_validate_entry_cash_settl_terms},
        {false, &CollateralResponseArgs_count_contractual_definitions, &CollateralResponseArgs_validate_entry_contractual_definitions},
        {false, &CollateralResponseArgs_count_contractual_matrices, &CollateralResponseArgs_validate_entry_contractual_matrices},
        {false, &CollateralResponseArgs_count_financing_term_supplements, &CollateralResponseArgs_validate_entry_financing_term_supplements},
        {false, &CollateralResponseArgs_count_streams, &CollateralResponseArgs_validate_entry_streams},
        {false, &CollateralResponseArgs_count_provisions, &CollateralResponseArgs_validate_entry_provisions},
        {false, &CollateralResponseArgs_count_protection_terms, &CollateralResponseArgs_validate_entry_protection_terms},
        {false, &CollateralResponseArgs_count_physical_settl_terms, &CollateralResponseArgs_validate_entry_physical_settl_terms},
        {false, &CollateralResponseArgs_count_business_centers, &CollateralResponseArgs_validate_entry_business_centers},
        {false, &CollateralResponseArgs_count_market_disruption_events, &CollateralResponseArgs_validate_entry_market_disruption_events},
        {false, &CollateralResponseArgs_count_market_disruption_fallbacks, &CollateralResponseArgs_validate_entry_market_disruption_fallbacks},
        {false, &CollateralResponseArgs_count_market_disruption_fallback_reference_prices, &CollateralResponseArgs_validate_entry_market_disruption_fallback_reference_prices},
        {false, &CollateralResponseArgs_count_option_exercise_business_centers, &CollateralResponseArgs_validate_entry_option_exercise_business_centers},
        {false, &CollateralResponseArgs_count_option_exercise_dates, &CollateralResponseArgs_validate_entry_option_exercise_dates},
        {false, &CollateralResponseArgs_count_option_exercise_expiration_date_business_centers, &CollateralResponseArgs_validate_entry_option_exercise_expiration_date_business_centers},
        {false, &CollateralResponseArgs_count_option_exercise_expiration_dates, &CollateralResponseArgs_validate_entry_option_exercise_expiration_dates},
        {false, &CollateralResponseArgs_count_pricing_date_business_centers, &CollateralResponseArgs_validate_entry_pricing_date_business_centers},
        {false, &CollateralResponseArgs_count_extraordinary_events, &CollateralResponseArgs_validate_entry_extraordinary_events},
        {false, &CollateralResponseArgs_count_settl_method_election_date_business_centers, &CollateralResponseArgs_validate_entry_settl_method_election_date_business_centers},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::vlatest {

inline ::fixpp::core::expected_t<void> validate_CollateralResponse(CollateralResponseArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::vlatest
