// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/Confirmation.validator.cpp -- external-linkage validate_ definition + this message's own top-level traits (data-model.md Entity 4), compiled only into fixpp_validators_<ver>.
#include "Confirmation.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool ConfirmationArgs_required_6(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { return a.avg_px.has_value(); }
inline bool ConfirmationArgs_required_54(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { return a.side.has_value(); }
inline bool ConfirmationArgs_required_60(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { return a.transact_time.has_value(); }
inline bool ConfirmationArgs_required_75(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { return a.trade_date.has_value(); }
inline bool ConfirmationArgs_required_79(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { return a.alloc_account.has_value(); }
inline bool ConfirmationArgs_required_80(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { return a.alloc_qty.has_value(); }
inline bool ConfirmationArgs_required_118(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { return a.net_money.has_value(); }
inline bool ConfirmationArgs_required_381(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { return a.gross_trade_amt.has_value(); }
inline bool ConfirmationArgs_required_664(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { return a.confirm_id.has_value(); }
inline bool ConfirmationArgs_required_665(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { return a.confirm_status.has_value(); }
inline bool ConfirmationArgs_required_666(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { return a.confirm_trans_type.has_value(); }
inline bool ConfirmationArgs_required_773(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { return a.confirm_type.has_value(); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_orders(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.orders) { return ::std::nullopt; } return a.orders->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_orders(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.orders)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_dlvy_inst(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.dlvy_inst) { return ::std::nullopt; } return a.dlvy_inst->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_dlvy_inst(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.dlvy_inst)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_execs(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.execs) { return ::std::nullopt; } return a.execs->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_execs(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.execs)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_misc_fees(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.misc_fees) { return ::std::nullopt; } return a.misc_fees->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_misc_fees(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.misc_fees)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_stipulations(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.stipulations) { return ::std::nullopt; } return a.stipulations->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_stipulations(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.stipulations)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_party_i_ds(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.party_i_ds) { return ::std::nullopt; } return a.party_i_ds->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_party_i_ds(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.party_i_ds)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_security_alt_id(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.security_alt_id) { return ::std::nullopt; } return a.security_alt_id->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_security_alt_id(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.security_alt_id)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_legs(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.legs) { return ::std::nullopt; } return a.legs->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_legs(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.legs)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_underlyings(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.underlyings) { return ::std::nullopt; } return a.underlyings->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_underlyings(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.underlyings)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_trd_reg_timestamps(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.trd_reg_timestamps) { return ::std::nullopt; } return a.trd_reg_timestamps->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_trd_reg_timestamps(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.trd_reg_timestamps)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_capacities(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { return a.capacities.size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_capacities(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required(a.capacities[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_events(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.events) { return ::std::nullopt; } return a.events->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_events(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.events)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_instr_attrib(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.instr_attrib) { return ::std::nullopt; } return a.instr_attrib->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_instr_attrib(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.instr_attrib)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_instrument_parties(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.instrument_parties) { return ::std::nullopt; } return a.instrument_parties->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_instrument_parties(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.instrument_parties)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_complex_events(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.complex_events) { return ::std::nullopt; } return a.complex_events->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_complex_events(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.complex_events)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_regulatory_trade_i_ds(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.regulatory_trade_i_ds) { return ::std::nullopt; } return a.regulatory_trade_i_ds->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_regulatory_trade_i_ds(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.regulatory_trade_i_ds)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_secondary_asset_classes(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.secondary_asset_classes) { return ::std::nullopt; } return a.secondary_asset_classes->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_secondary_asset_classes(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.secondary_asset_classes)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_asset_attributes(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.asset_attributes) { return ::std::nullopt; } return a.asset_attributes->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_asset_attributes(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.asset_attributes)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_commissions(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.commissions) { return ::std::nullopt; } return a.commissions->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_commissions(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.commissions)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_price_qualifiers(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.price_qualifiers) { return ::std::nullopt; } return a.price_qualifiers->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_price_qualifiers(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.price_qualifiers)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_index_roll_months(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.index_roll_months) { return ::std::nullopt; } return a.index_roll_months->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_index_roll_months(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.index_roll_months)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_reference_data_dates(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.reference_data_dates) { return ::std::nullopt; } return a.reference_data_dates->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_reference_data_dates(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.reference_data_dates)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_match_exceptions(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.match_exceptions) { return ::std::nullopt; } return a.match_exceptions->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_match_exceptions(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.match_exceptions)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_matching_data_points(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.matching_data_points) { return ::std::nullopt; } return a.matching_data_points->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_matching_data_points(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.matching_data_points)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_additional_terms(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.additional_terms) { return ::std::nullopt; } return a.additional_terms->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_additional_terms(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.additional_terms)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_cash_settl_terms(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.cash_settl_terms) { return ::std::nullopt; } return a.cash_settl_terms->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_cash_settl_terms(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.cash_settl_terms)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_contractual_definitions(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.contractual_definitions) { return ::std::nullopt; } return a.contractual_definitions->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_contractual_definitions(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.contractual_definitions)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_contractual_matrices(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.contractual_matrices) { return ::std::nullopt; } return a.contractual_matrices->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_contractual_matrices(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.contractual_matrices)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_financing_term_supplements(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.financing_term_supplements) { return ::std::nullopt; } return a.financing_term_supplements->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_financing_term_supplements(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.financing_term_supplements)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_streams(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.streams) { return ::std::nullopt; } return a.streams->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_streams(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.streams)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_provisions(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.provisions) { return ::std::nullopt; } return a.provisions->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_provisions(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.provisions)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_protection_terms(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.protection_terms) { return ::std::nullopt; } return a.protection_terms->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_protection_terms(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.protection_terms)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_physical_settl_terms(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.physical_settl_terms) { return ::std::nullopt; } return a.physical_settl_terms->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_physical_settl_terms(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.physical_settl_terms)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_business_centers(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.business_centers) { return ::std::nullopt; } return a.business_centers->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_business_centers(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.business_centers)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_market_disruption_events(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.market_disruption_events) { return ::std::nullopt; } return a.market_disruption_events->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_market_disruption_events(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.market_disruption_events)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_market_disruption_fallbacks(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.market_disruption_fallbacks) { return ::std::nullopt; } return a.market_disruption_fallbacks->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_market_disruption_fallbacks(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.market_disruption_fallbacks)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_market_disruption_fallback_reference_prices(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.market_disruption_fallback_reference_prices) { return ::std::nullopt; } return a.market_disruption_fallback_reference_prices->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_market_disruption_fallback_reference_prices(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.market_disruption_fallback_reference_prices)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_option_exercise_business_centers(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.option_exercise_business_centers) { return ::std::nullopt; } return a.option_exercise_business_centers->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_option_exercise_business_centers(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.option_exercise_business_centers)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_option_exercise_dates(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.option_exercise_dates) { return ::std::nullopt; } return a.option_exercise_dates->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_option_exercise_dates(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.option_exercise_dates)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_option_exercise_expiration_date_business_centers(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.option_exercise_expiration_date_business_centers) { return ::std::nullopt; } return a.option_exercise_expiration_date_business_centers->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_option_exercise_expiration_date_business_centers(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.option_exercise_expiration_date_business_centers)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_option_exercise_expiration_dates(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.option_exercise_expiration_dates) { return ::std::nullopt; } return a.option_exercise_expiration_dates->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_option_exercise_expiration_dates(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.option_exercise_expiration_dates)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_pricing_date_business_centers(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.pricing_date_business_centers) { return ::std::nullopt; } return a.pricing_date_business_centers->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_pricing_date_business_centers(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.pricing_date_business_centers)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_extraordinary_events(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.extraordinary_events) { return ::std::nullopt; } return a.extraordinary_events->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_extraordinary_events(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.extraordinary_events)[i]); }
inline ::std::optional<::std::size_t> ConfirmationArgs_count_settl_method_election_date_business_centers(::fixpp::vlatest::ConfirmationArgs const& a) noexcept { if (!a.settl_method_election_date_business_centers) { return ::std::nullopt; } return a.settl_method_election_date_business_centers->size(); }
inline ::fixpp::core::expected_t<void> ConfirmationArgs_validate_entry_settl_method_election_date_business_centers(::fixpp::vlatest::ConfirmationArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.settl_method_election_date_business_centers)[i]); }
template <> struct writer_traits<::fixpp::vlatest::ConfirmationArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::vlatest::ConfirmationArgs>, 12> required_checks = {{
        {6, &ConfirmationArgs_required_6},
        {54, &ConfirmationArgs_required_54},
        {60, &ConfirmationArgs_required_60},
        {75, &ConfirmationArgs_required_75},
        {79, &ConfirmationArgs_required_79},
        {80, &ConfirmationArgs_required_80},
        {118, &ConfirmationArgs_required_118},
        {381, &ConfirmationArgs_required_381},
        {664, &ConfirmationArgs_required_664},
        {665, &ConfirmationArgs_required_665},
        {666, &ConfirmationArgs_required_666},
        {773, &ConfirmationArgs_required_773},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::vlatest::ConfirmationArgs>, 44> group_checks = {{
        {false, &ConfirmationArgs_count_orders, &ConfirmationArgs_validate_entry_orders},
        {false, &ConfirmationArgs_count_dlvy_inst, &ConfirmationArgs_validate_entry_dlvy_inst},
        {false, &ConfirmationArgs_count_execs, &ConfirmationArgs_validate_entry_execs},
        {false, &ConfirmationArgs_count_misc_fees, &ConfirmationArgs_validate_entry_misc_fees},
        {false, &ConfirmationArgs_count_stipulations, &ConfirmationArgs_validate_entry_stipulations},
        {false, &ConfirmationArgs_count_party_i_ds, &ConfirmationArgs_validate_entry_party_i_ds},
        {false, &ConfirmationArgs_count_security_alt_id, &ConfirmationArgs_validate_entry_security_alt_id},
        {false, &ConfirmationArgs_count_legs, &ConfirmationArgs_validate_entry_legs},
        {false, &ConfirmationArgs_count_underlyings, &ConfirmationArgs_validate_entry_underlyings},
        {false, &ConfirmationArgs_count_trd_reg_timestamps, &ConfirmationArgs_validate_entry_trd_reg_timestamps},
        {true, &ConfirmationArgs_count_capacities, &ConfirmationArgs_validate_entry_capacities},
        {false, &ConfirmationArgs_count_events, &ConfirmationArgs_validate_entry_events},
        {false, &ConfirmationArgs_count_instr_attrib, &ConfirmationArgs_validate_entry_instr_attrib},
        {false, &ConfirmationArgs_count_instrument_parties, &ConfirmationArgs_validate_entry_instrument_parties},
        {false, &ConfirmationArgs_count_complex_events, &ConfirmationArgs_validate_entry_complex_events},
        {false, &ConfirmationArgs_count_regulatory_trade_i_ds, &ConfirmationArgs_validate_entry_regulatory_trade_i_ds},
        {false, &ConfirmationArgs_count_secondary_asset_classes, &ConfirmationArgs_validate_entry_secondary_asset_classes},
        {false, &ConfirmationArgs_count_asset_attributes, &ConfirmationArgs_validate_entry_asset_attributes},
        {false, &ConfirmationArgs_count_commissions, &ConfirmationArgs_validate_entry_commissions},
        {false, &ConfirmationArgs_count_price_qualifiers, &ConfirmationArgs_validate_entry_price_qualifiers},
        {false, &ConfirmationArgs_count_index_roll_months, &ConfirmationArgs_validate_entry_index_roll_months},
        {false, &ConfirmationArgs_count_reference_data_dates, &ConfirmationArgs_validate_entry_reference_data_dates},
        {false, &ConfirmationArgs_count_match_exceptions, &ConfirmationArgs_validate_entry_match_exceptions},
        {false, &ConfirmationArgs_count_matching_data_points, &ConfirmationArgs_validate_entry_matching_data_points},
        {false, &ConfirmationArgs_count_additional_terms, &ConfirmationArgs_validate_entry_additional_terms},
        {false, &ConfirmationArgs_count_cash_settl_terms, &ConfirmationArgs_validate_entry_cash_settl_terms},
        {false, &ConfirmationArgs_count_contractual_definitions, &ConfirmationArgs_validate_entry_contractual_definitions},
        {false, &ConfirmationArgs_count_contractual_matrices, &ConfirmationArgs_validate_entry_contractual_matrices},
        {false, &ConfirmationArgs_count_financing_term_supplements, &ConfirmationArgs_validate_entry_financing_term_supplements},
        {false, &ConfirmationArgs_count_streams, &ConfirmationArgs_validate_entry_streams},
        {false, &ConfirmationArgs_count_provisions, &ConfirmationArgs_validate_entry_provisions},
        {false, &ConfirmationArgs_count_protection_terms, &ConfirmationArgs_validate_entry_protection_terms},
        {false, &ConfirmationArgs_count_physical_settl_terms, &ConfirmationArgs_validate_entry_physical_settl_terms},
        {false, &ConfirmationArgs_count_business_centers, &ConfirmationArgs_validate_entry_business_centers},
        {false, &ConfirmationArgs_count_market_disruption_events, &ConfirmationArgs_validate_entry_market_disruption_events},
        {false, &ConfirmationArgs_count_market_disruption_fallbacks, &ConfirmationArgs_validate_entry_market_disruption_fallbacks},
        {false, &ConfirmationArgs_count_market_disruption_fallback_reference_prices, &ConfirmationArgs_validate_entry_market_disruption_fallback_reference_prices},
        {false, &ConfirmationArgs_count_option_exercise_business_centers, &ConfirmationArgs_validate_entry_option_exercise_business_centers},
        {false, &ConfirmationArgs_count_option_exercise_dates, &ConfirmationArgs_validate_entry_option_exercise_dates},
        {false, &ConfirmationArgs_count_option_exercise_expiration_date_business_centers, &ConfirmationArgs_validate_entry_option_exercise_expiration_date_business_centers},
        {false, &ConfirmationArgs_count_option_exercise_expiration_dates, &ConfirmationArgs_validate_entry_option_exercise_expiration_dates},
        {false, &ConfirmationArgs_count_pricing_date_business_centers, &ConfirmationArgs_validate_entry_pricing_date_business_centers},
        {false, &ConfirmationArgs_count_extraordinary_events, &ConfirmationArgs_validate_entry_extraordinary_events},
        {false, &ConfirmationArgs_count_settl_method_election_date_business_centers, &ConfirmationArgs_validate_entry_settl_method_election_date_business_centers},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::vlatest {

::fixpp::core::expected_t<void> validate_Confirmation(ConfirmationArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::vlatest
