// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/MarketDataIncrementalRefresh.validator.cpp -- external-linkage validate_ definition + this message's own top-level traits (data-model.md Entity 4), compiled only into fixpp_validators_<ver>.
#include "MarketDataIncrementalRefresh.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline ::std::optional<::std::size_t> MarketDataIncrementalRefreshArgs_count_routing_i_ds(::fixpp::vlatest::MarketDataIncrementalRefreshArgs const& a) noexcept { if (!a.routing_i_ds) { return ::std::nullopt; } return a.routing_i_ds->size(); }
inline ::fixpp::core::expected_t<void> MarketDataIncrementalRefreshArgs_validate_entry_routing_i_ds(::fixpp::vlatest::MarketDataIncrementalRefreshArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.routing_i_ds)[i]); }
inline ::std::optional<::std::size_t> MarketDataIncrementalRefreshArgs_count_md_entries(::fixpp::vlatest::MarketDataIncrementalRefreshArgs const& a) noexcept { return a.md_entries.size(); }
inline ::fixpp::core::expected_t<void> MarketDataIncrementalRefreshArgs_validate_entry_md_entries(::fixpp::vlatest::MarketDataIncrementalRefreshArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required(a.md_entries[i]); }
template <> struct writer_traits<::fixpp::vlatest::MarketDataIncrementalRefreshArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::vlatest::MarketDataIncrementalRefreshArgs>, 0> required_checks = {};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::vlatest::MarketDataIncrementalRefreshArgs>, 2> group_checks = {{
        {false, &MarketDataIncrementalRefreshArgs_count_routing_i_ds, &MarketDataIncrementalRefreshArgs_validate_entry_routing_i_ds},
        {true, &MarketDataIncrementalRefreshArgs_count_md_entries, &MarketDataIncrementalRefreshArgs_validate_entry_md_entries},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::vlatest {

::fixpp::core::expected_t<void> validate_MarketDataIncrementalRefresh(MarketDataIncrementalRefreshArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::vlatest
