// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/MarketDefinitionRequest.hpp -- slim per-message declaration header (data-model.md Entity 2).
#pragma once
#include <cstddef>
#include <cstdint>
#include <fixpp/core/decimal_alias.hpp>
#include <fixpp/core/error.hpp>
#include <optional>
#include <span>
#include <string_view>

namespace fixpp::vlatest {

struct MarketDefinitionRequestArgs {
    ::std::optional<char> subscription_request_type{};
    ::std::optional<::std::string_view> market_segment_id{};
    ::std::optional<::std::string_view> market_id{};
    ::std::optional<::std::string_view> parent_mkt_segm_id{};
    ::std::optional<::std::string_view> market_req_id{};
};

}  // namespace fixpp::vlatest

#if defined(FIXPP_BUILDERS_HEADER_ONLY) || defined(FIXPP_BUILDERS_HEADER_ONLY_MarketDefinitionRequest)
#include "MarketDefinitionRequest.builder.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<::std::span<::std::byte>> build_MarketDefinitionRequest(::std::span<::std::byte> out, MarketDefinitionRequestArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif

#if defined(FIXPP_VALIDATORS_HEADER_ONLY) || defined(FIXPP_VALIDATORS_HEADER_ONLY_MarketDefinitionRequest)
#include "MarketDefinitionRequest.validator.inl"
#else
namespace fixpp::vlatest {
::fixpp::core::expected_t<void> validate_MarketDefinitionRequest(MarketDefinitionRequestArgs const& args) noexcept;
}  // namespace fixpp::vlatest
#endif
