// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/NewOrderList.validator.cpp -- external-linkage validate_ definition + this message's own top-level traits (data-model.md Entity 4), compiled only into fixpp_validators_<ver>.
#include "NewOrderList.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool NewOrderListArgs_required_66(::fixpp::vlatest::NewOrderListArgs const& a) noexcept { return a.list_id.has_value(); }
inline bool NewOrderListArgs_required_68(::fixpp::vlatest::NewOrderListArgs const& a) noexcept { return a.tot_no_orders.has_value(); }
inline bool NewOrderListArgs_required_394(::fixpp::vlatest::NewOrderListArgs const& a) noexcept { return a.bid_type.has_value(); }
inline ::std::optional<::std::size_t> NewOrderListArgs_count_orders(::fixpp::vlatest::NewOrderListArgs const& a) noexcept { return a.orders.size(); }
inline ::fixpp::core::expected_t<void> NewOrderListArgs_validate_entry_orders(::fixpp::vlatest::NewOrderListArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required(a.orders[i]); }
inline ::std::optional<::std::size_t> NewOrderListArgs_count_root_party_i_ds(::fixpp::vlatest::NewOrderListArgs const& a) noexcept { if (!a.root_party_i_ds) { return ::std::nullopt; } return a.root_party_i_ds->size(); }
inline ::fixpp::core::expected_t<void> NewOrderListArgs_validate_entry_root_party_i_ds(::fixpp::vlatest::NewOrderListArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.root_party_i_ds)[i]); }
template <> struct writer_traits<::fixpp::vlatest::NewOrderListArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::vlatest::NewOrderListArgs>, 3> required_checks = {{
        {66, &NewOrderListArgs_required_66},
        {68, &NewOrderListArgs_required_68},
        {394, &NewOrderListArgs_required_394},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::vlatest::NewOrderListArgs>, 2> group_checks = {{
        {true, &NewOrderListArgs_count_orders, &NewOrderListArgs_validate_entry_orders},
        {false, &NewOrderListArgs_count_root_party_i_ds, &NewOrderListArgs_validate_entry_root_party_i_ds},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::vlatest {

::fixpp::core::expected_t<void> validate_NewOrderList(NewOrderListArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::vlatest
