// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/QuoteRequestReject.validator.inl -- inline validate_ body + this message's own top-level traits (data-model.md Entity 3).
#pragma once
#include "QuoteRequestReject.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool QuoteRequestRejectArgs_required_131(::fixpp::vlatest::QuoteRequestRejectArgs const& a) noexcept { return a.quote_req_id.has_value(); }
inline bool QuoteRequestRejectArgs_required_658(::fixpp::vlatest::QuoteRequestRejectArgs const& a) noexcept { return a.quote_request_reject_reason.has_value(); }
inline ::std::optional<::std::size_t> QuoteRequestRejectArgs_count_related_sym(::fixpp::vlatest::QuoteRequestRejectArgs const& a) noexcept { return a.related_sym.size(); }
inline ::fixpp::core::expected_t<void> QuoteRequestRejectArgs_validate_entry_related_sym(::fixpp::vlatest::QuoteRequestRejectArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required(a.related_sym[i]); }
inline ::std::optional<::std::size_t> QuoteRequestRejectArgs_count_root_party_i_ds(::fixpp::vlatest::QuoteRequestRejectArgs const& a) noexcept { if (!a.root_party_i_ds) { return ::std::nullopt; } return a.root_party_i_ds->size(); }
inline ::fixpp::core::expected_t<void> QuoteRequestRejectArgs_validate_entry_root_party_i_ds(::fixpp::vlatest::QuoteRequestRejectArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.root_party_i_ds)[i]); }
template <> struct writer_traits<::fixpp::vlatest::QuoteRequestRejectArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::vlatest::QuoteRequestRejectArgs>, 2> required_checks = {{
        {131, &QuoteRequestRejectArgs_required_131},
        {658, &QuoteRequestRejectArgs_required_658},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::vlatest::QuoteRequestRejectArgs>, 2> group_checks = {{
        {true, &QuoteRequestRejectArgs_count_related_sym, &QuoteRequestRejectArgs_validate_entry_related_sym},
        {false, &QuoteRequestRejectArgs_count_root_party_i_ds, &QuoteRequestRejectArgs_validate_entry_root_party_i_ds},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::vlatest {

inline ::fixpp::core::expected_t<void> validate_QuoteRequestReject(QuoteRequestRejectArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::vlatest
