// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/RegistrationInstructions.validator.cpp -- external-linkage validate_ definition + this message's own top-level traits (data-model.md Entity 4), compiled only into fixpp_validators_<ver>.
#include "RegistrationInstructions.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool RegistrationInstructionsArgs_required_508(::fixpp::vlatest::RegistrationInstructionsArgs const& a) noexcept { return a.regist_ref_id.has_value(); }
inline bool RegistrationInstructionsArgs_required_513(::fixpp::vlatest::RegistrationInstructionsArgs const& a) noexcept { return a.regist_id.has_value(); }
inline bool RegistrationInstructionsArgs_required_514(::fixpp::vlatest::RegistrationInstructionsArgs const& a) noexcept { return a.regist_trans_type.has_value(); }
inline ::std::optional<::std::size_t> RegistrationInstructionsArgs_count_party_i_ds(::fixpp::vlatest::RegistrationInstructionsArgs const& a) noexcept { if (!a.party_i_ds) { return ::std::nullopt; } return a.party_i_ds->size(); }
inline ::fixpp::core::expected_t<void> RegistrationInstructionsArgs_validate_entry_party_i_ds(::fixpp::vlatest::RegistrationInstructionsArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.party_i_ds)[i]); }
inline ::std::optional<::std::size_t> RegistrationInstructionsArgs_count_regist_dtls(::fixpp::vlatest::RegistrationInstructionsArgs const& a) noexcept { if (!a.regist_dtls) { return ::std::nullopt; } return a.regist_dtls->size(); }
inline ::fixpp::core::expected_t<void> RegistrationInstructionsArgs_validate_entry_regist_dtls(::fixpp::vlatest::RegistrationInstructionsArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.regist_dtls)[i]); }
inline ::std::optional<::std::size_t> RegistrationInstructionsArgs_count_distrib_insts(::fixpp::vlatest::RegistrationInstructionsArgs const& a) noexcept { if (!a.distrib_insts) { return ::std::nullopt; } return a.distrib_insts->size(); }
inline ::fixpp::core::expected_t<void> RegistrationInstructionsArgs_validate_entry_distrib_insts(::fixpp::vlatest::RegistrationInstructionsArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.distrib_insts)[i]); }
template <> struct writer_traits<::fixpp::vlatest::RegistrationInstructionsArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::vlatest::RegistrationInstructionsArgs>, 3> required_checks = {{
        {508, &RegistrationInstructionsArgs_required_508},
        {513, &RegistrationInstructionsArgs_required_513},
        {514, &RegistrationInstructionsArgs_required_514},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::vlatest::RegistrationInstructionsArgs>, 3> group_checks = {{
        {false, &RegistrationInstructionsArgs_count_party_i_ds, &RegistrationInstructionsArgs_validate_entry_party_i_ds},
        {false, &RegistrationInstructionsArgs_count_regist_dtls, &RegistrationInstructionsArgs_validate_entry_regist_dtls},
        {false, &RegistrationInstructionsArgs_count_distrib_insts, &RegistrationInstructionsArgs_validate_entry_distrib_insts},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::vlatest {

::fixpp::core::expected_t<void> validate_RegistrationInstructions(RegistrationInstructionsArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::vlatest
