// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/SecurityMassStatus.validator.inl -- inline validate_ body + this message's own top-level traits (data-model.md Entity 3).
#pragma once
#include "SecurityMassStatus.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline ::std::optional<::std::size_t> SecurityMassStatusArgs_count_related_sym(::fixpp::vlatest::SecurityMassStatusArgs const& a) noexcept { if (!a.related_sym) { return ::std::nullopt; } return a.related_sym->size(); }
inline ::fixpp::core::expected_t<void> SecurityMassStatusArgs_validate_entry_related_sym(::fixpp::vlatest::SecurityMassStatusArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.related_sym)[i]); }
inline ::std::optional<::std::size_t> SecurityMassStatusArgs_count_instrument_scope_security_alt_id(::fixpp::vlatest::SecurityMassStatusArgs const& a) noexcept { if (!a.instrument_scope_security_alt_id) { return ::std::nullopt; } return a.instrument_scope_security_alt_id->size(); }
inline ::fixpp::core::expected_t<void> SecurityMassStatusArgs_validate_entry_instrument_scope_security_alt_id(::fixpp::vlatest::SecurityMassStatusArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.instrument_scope_security_alt_id)[i]); }
template <> struct writer_traits<::fixpp::vlatest::SecurityMassStatusArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::vlatest::SecurityMassStatusArgs>, 0> required_checks = {};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::vlatest::SecurityMassStatusArgs>, 2> group_checks = {{
        {false, &SecurityMassStatusArgs_count_related_sym, &SecurityMassStatusArgs_validate_entry_related_sym},
        {false, &SecurityMassStatusArgs_count_instrument_scope_security_alt_id, &SecurityMassStatusArgs_validate_entry_instrument_scope_security_alt_id},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::vlatest {

inline ::fixpp::core::expected_t<void> validate_SecurityMassStatus(SecurityMassStatusArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::vlatest
