// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/TestSuiteDefinitionRequestAck.validator.inl -- inline validate_ body + this message's own top-level traits (data-model.md Entity 3).
#pragma once
#include "TestSuiteDefinitionRequestAck.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool TestSuiteDefinitionRequestAckArgs_required_3062(::fixpp::vlatest::TestSuiteDefinitionRequestAckArgs const& a) noexcept { return a.test_suite_request_id.has_value(); }
inline bool TestSuiteDefinitionRequestAckArgs_required_3065(::fixpp::vlatest::TestSuiteDefinitionRequestAckArgs const& a) noexcept { return a.test_suite_request_status.has_value(); }
inline ::std::optional<::std::size_t> TestSuiteDefinitionRequestAckArgs_count_test_gateway_details(::fixpp::vlatest::TestSuiteDefinitionRequestAckArgs const& a) noexcept { if (!a.test_gateway_details) { return ::std::nullopt; } return a.test_gateway_details->size(); }
inline ::fixpp::core::expected_t<void> TestSuiteDefinitionRequestAckArgs_validate_entry_test_gateway_details(::fixpp::vlatest::TestSuiteDefinitionRequestAckArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.test_gateway_details)[i]); }
template <> struct writer_traits<::fixpp::vlatest::TestSuiteDefinitionRequestAckArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::vlatest::TestSuiteDefinitionRequestAckArgs>, 2> required_checks = {{
        {3062, &TestSuiteDefinitionRequestAckArgs_required_3062},
        {3065, &TestSuiteDefinitionRequestAckArgs_required_3065},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::vlatest::TestSuiteDefinitionRequestAckArgs>, 1> group_checks = {{
        {false, &TestSuiteDefinitionRequestAckArgs_count_test_gateway_details, &TestSuiteDefinitionRequestAckArgs_validate_entry_test_gateway_details},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::vlatest {

inline ::fixpp::core::expected_t<void> validate_TestSuiteDefinitionRequestAck(TestSuiteDefinitionRequestAckArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::vlatest
