// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by fixpp-codegen (078-precompiled-builder-libs). DO NOT EDIT.
// fixpp/vlatest/messages/TestSuiteDefinitionRequest.validator.cpp -- external-linkage validate_ definition + this message's own top-level traits (data-model.md Entity 4), compiled only into fixpp_validators_<ver>.
#include "TestSuiteDefinitionRequest.hpp"
#include "../validators/traits.hpp"

namespace fixpp::wire {

inline bool TestSuiteDefinitionRequestArgs_required_60(::fixpp::vlatest::TestSuiteDefinitionRequestArgs const& a) noexcept { return a.transact_time.has_value(); }
inline bool TestSuiteDefinitionRequestArgs_required_3062(::fixpp::vlatest::TestSuiteDefinitionRequestArgs const& a) noexcept { return a.test_suite_request_id.has_value(); }
inline bool TestSuiteDefinitionRequestArgs_required_3064(::fixpp::vlatest::TestSuiteDefinitionRequestArgs const& a) noexcept { return a.test_suite_request_trans_type.has_value(); }
inline ::std::optional<::std::size_t> TestSuiteDefinitionRequestArgs_count_party_i_ds(::fixpp::vlatest::TestSuiteDefinitionRequestArgs const& a) noexcept { if (!a.party_i_ds) { return ::std::nullopt; } return a.party_i_ds->size(); }
inline ::fixpp::core::expected_t<void> TestSuiteDefinitionRequestArgs_validate_entry_party_i_ds(::fixpp::vlatest::TestSuiteDefinitionRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.party_i_ds)[i]); }
inline ::std::optional<::std::size_t> TestSuiteDefinitionRequestArgs_count_strategy_parameters(::fixpp::vlatest::TestSuiteDefinitionRequestArgs const& a) noexcept { if (!a.strategy_parameters) { return ::std::nullopt; } return a.strategy_parameters->size(); }
inline ::fixpp::core::expected_t<void> TestSuiteDefinitionRequestArgs_validate_entry_strategy_parameters(::fixpp::vlatest::TestSuiteDefinitionRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.strategy_parameters)[i]); }
inline ::std::optional<::std::size_t> TestSuiteDefinitionRequestArgs_count_algo_system_modules(::fixpp::vlatest::TestSuiteDefinitionRequestArgs const& a) noexcept { if (!a.algo_system_modules) { return ::std::nullopt; } return a.algo_system_modules->size(); }
inline ::fixpp::core::expected_t<void> TestSuiteDefinitionRequestArgs_validate_entry_algo_system_modules(::fixpp::vlatest::TestSuiteDefinitionRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.algo_system_modules)[i]); }
inline ::std::optional<::std::size_t> TestSuiteDefinitionRequestArgs_count_test_scenarios(::fixpp::vlatest::TestSuiteDefinitionRequestArgs const& a) noexcept { return a.test_scenarios.size(); }
inline ::fixpp::core::expected_t<void> TestSuiteDefinitionRequestArgs_validate_entry_test_scenarios(::fixpp::vlatest::TestSuiteDefinitionRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required(a.test_scenarios[i]); }
inline ::std::optional<::std::size_t> TestSuiteDefinitionRequestArgs_count_test_suite_parameters(::fixpp::vlatest::TestSuiteDefinitionRequestArgs const& a) noexcept { if (!a.test_suite_parameters) { return ::std::nullopt; } return a.test_suite_parameters->size(); }
inline ::fixpp::core::expected_t<void> TestSuiteDefinitionRequestArgs_validate_entry_test_suite_parameters(::fixpp::vlatest::TestSuiteDefinitionRequestArgs const& a, ::std::size_t i) noexcept { return ::fixpp::wire::validate_required((*a.test_suite_parameters)[i]); }
template <> struct writer_traits<::fixpp::vlatest::TestSuiteDefinitionRequestArgs> {
    static constexpr ::std::array<::fixpp::wire::required_check<::fixpp::vlatest::TestSuiteDefinitionRequestArgs>, 3> required_checks = {{
        {60, &TestSuiteDefinitionRequestArgs_required_60},
        {3062, &TestSuiteDefinitionRequestArgs_required_3062},
        {3064, &TestSuiteDefinitionRequestArgs_required_3064},
    }};
    static constexpr ::std::array<::fixpp::wire::group_check<::fixpp::vlatest::TestSuiteDefinitionRequestArgs>, 5> group_checks = {{
        {false, &TestSuiteDefinitionRequestArgs_count_party_i_ds, &TestSuiteDefinitionRequestArgs_validate_entry_party_i_ds},
        {false, &TestSuiteDefinitionRequestArgs_count_strategy_parameters, &TestSuiteDefinitionRequestArgs_validate_entry_strategy_parameters},
        {false, &TestSuiteDefinitionRequestArgs_count_algo_system_modules, &TestSuiteDefinitionRequestArgs_validate_entry_algo_system_modules},
        {true, &TestSuiteDefinitionRequestArgs_count_test_scenarios, &TestSuiteDefinitionRequestArgs_validate_entry_test_scenarios},
        {false, &TestSuiteDefinitionRequestArgs_count_test_suite_parameters, &TestSuiteDefinitionRequestArgs_validate_entry_test_suite_parameters},
    }};
};

}  // namespace fixpp::wire

namespace fixpp::vlatest {

::fixpp::core::expected_t<void> validate_TestSuiteDefinitionRequest(TestSuiteDefinitionRequestArgs const& args) noexcept {
    return ::fixpp::wire::validate_required(args);
}
}  // namespace fixpp::vlatest
